// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/ldm2060/axonhub/internal/ent/channelusagemonitorbinding"
	"github.com/ldm2060/axonhub/internal/ent/predicate"
	"github.com/ldm2060/axonhub/internal/objects"
)

// ChannelUsageMonitorBindingUpdate is the builder for updating ChannelUsageMonitorBinding entities.
type ChannelUsageMonitorBindingUpdate struct {
	config
	hooks     []Hook
	mutation  *ChannelUsageMonitorBindingMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ChannelUsageMonitorBindingUpdate builder.
func (_u *ChannelUsageMonitorBindingUpdate) Where(ps ...predicate.ChannelUsageMonitorBinding) *ChannelUsageMonitorBindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelUsageMonitorBindingUpdate) SetUpdatedAt(v time.Time) *ChannelUsageMonitorBindingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ChannelUsageMonitorBindingUpdate) SetDeletedAt(v int) *ChannelUsageMonitorBindingUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ChannelUsageMonitorBindingUpdate) SetNillableDeletedAt(v *int) *ChannelUsageMonitorBindingUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *ChannelUsageMonitorBindingUpdate) AddDeletedAt(v int) *ChannelUsageMonitorBindingUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ChannelUsageMonitorBindingUpdate) SetEnabled(v bool) *ChannelUsageMonitorBindingUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ChannelUsageMonitorBindingUpdate) SetNillableEnabled(v *bool) *ChannelUsageMonitorBindingUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetTriggerStatuses sets the "trigger_statuses" field.
func (_u *ChannelUsageMonitorBindingUpdate) SetTriggerStatuses(v []string) *ChannelUsageMonitorBindingUpdate {
	_u.mutation.SetTriggerStatuses(v)
	return _u
}

// AppendTriggerStatuses appends value to the "trigger_statuses" field.
func (_u *ChannelUsageMonitorBindingUpdate) AppendTriggerStatuses(v []string) *ChannelUsageMonitorBindingUpdate {
	_u.mutation.AppendTriggerStatuses(v)
	return _u
}

// SetConditions sets the "conditions" field.
func (_u *ChannelUsageMonitorBindingUpdate) SetConditions(v []objects.QuotaMonitorBindingCondition) *ChannelUsageMonitorBindingUpdate {
	_u.mutation.SetConditions(v)
	return _u
}

// AppendConditions appends value to the "conditions" field.
func (_u *ChannelUsageMonitorBindingUpdate) AppendConditions(v []objects.QuotaMonitorBindingCondition) *ChannelUsageMonitorBindingUpdate {
	_u.mutation.AppendConditions(v)
	return _u
}

// SetLastTriggeredAt sets the "last_triggered_at" field.
func (_u *ChannelUsageMonitorBindingUpdate) SetLastTriggeredAt(v time.Time) *ChannelUsageMonitorBindingUpdate {
	_u.mutation.SetLastTriggeredAt(v)
	return _u
}

// SetNillableLastTriggeredAt sets the "last_triggered_at" field if the given value is not nil.
func (_u *ChannelUsageMonitorBindingUpdate) SetNillableLastTriggeredAt(v *time.Time) *ChannelUsageMonitorBindingUpdate {
	if v != nil {
		_u.SetLastTriggeredAt(*v)
	}
	return _u
}

// ClearLastTriggeredAt clears the value of the "last_triggered_at" field.
func (_u *ChannelUsageMonitorBindingUpdate) ClearLastTriggeredAt() *ChannelUsageMonitorBindingUpdate {
	_u.mutation.ClearLastTriggeredAt()
	return _u
}

// SetLastTriggerReason sets the "last_trigger_reason" field.
func (_u *ChannelUsageMonitorBindingUpdate) SetLastTriggerReason(v string) *ChannelUsageMonitorBindingUpdate {
	_u.mutation.SetLastTriggerReason(v)
	return _u
}

// SetNillableLastTriggerReason sets the "last_trigger_reason" field if the given value is not nil.
func (_u *ChannelUsageMonitorBindingUpdate) SetNillableLastTriggerReason(v *string) *ChannelUsageMonitorBindingUpdate {
	if v != nil {
		_u.SetLastTriggerReason(*v)
	}
	return _u
}

// ClearLastTriggerReason clears the value of the "last_trigger_reason" field.
func (_u *ChannelUsageMonitorBindingUpdate) ClearLastTriggerReason() *ChannelUsageMonitorBindingUpdate {
	_u.mutation.ClearLastTriggerReason()
	return _u
}

// Mutation returns the ChannelUsageMonitorBindingMutation object of the builder.
func (_u *ChannelUsageMonitorBindingUpdate) Mutation() *ChannelUsageMonitorBindingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelUsageMonitorBindingUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelUsageMonitorBindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelUsageMonitorBindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelUsageMonitorBindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelUsageMonitorBindingUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if channelusagemonitorbinding.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized channelusagemonitorbinding.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := channelusagemonitorbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelUsageMonitorBindingUpdate) check() error {
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelUsageMonitorBinding.channel"`)
	}
	if _u.mutation.UsageMonitorChannelCleared() && len(_u.mutation.UsageMonitorChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelUsageMonitorBinding.usage_monitor_channel"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ChannelUsageMonitorBindingUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ChannelUsageMonitorBindingUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ChannelUsageMonitorBindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelusagemonitorbinding.Table, channelusagemonitorbinding.Columns, sqlgraph.NewFieldSpec(channelusagemonitorbinding.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channelusagemonitorbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(channelusagemonitorbinding.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(channelusagemonitorbinding.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(channelusagemonitorbinding.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TriggerStatuses(); ok {
		_spec.SetField(channelusagemonitorbinding.FieldTriggerStatuses, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTriggerStatuses(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, channelusagemonitorbinding.FieldTriggerStatuses, value)
		})
	}
	if value, ok := _u.mutation.Conditions(); ok {
		_spec.SetField(channelusagemonitorbinding.FieldConditions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedConditions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, channelusagemonitorbinding.FieldConditions, value)
		})
	}
	if value, ok := _u.mutation.LastTriggeredAt(); ok {
		_spec.SetField(channelusagemonitorbinding.FieldLastTriggeredAt, field.TypeTime, value)
	}
	if _u.mutation.LastTriggeredAtCleared() {
		_spec.ClearField(channelusagemonitorbinding.FieldLastTriggeredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastTriggerReason(); ok {
		_spec.SetField(channelusagemonitorbinding.FieldLastTriggerReason, field.TypeString, value)
	}
	if _u.mutation.LastTriggerReasonCleared() {
		_spec.ClearField(channelusagemonitorbinding.FieldLastTriggerReason, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelusagemonitorbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelUsageMonitorBindingUpdateOne is the builder for updating a single ChannelUsageMonitorBinding entity.
type ChannelUsageMonitorBindingUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ChannelUsageMonitorBindingMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelUsageMonitorBindingUpdateOne) SetUpdatedAt(v time.Time) *ChannelUsageMonitorBindingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ChannelUsageMonitorBindingUpdateOne) SetDeletedAt(v int) *ChannelUsageMonitorBindingUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ChannelUsageMonitorBindingUpdateOne) SetNillableDeletedAt(v *int) *ChannelUsageMonitorBindingUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *ChannelUsageMonitorBindingUpdateOne) AddDeletedAt(v int) *ChannelUsageMonitorBindingUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ChannelUsageMonitorBindingUpdateOne) SetEnabled(v bool) *ChannelUsageMonitorBindingUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ChannelUsageMonitorBindingUpdateOne) SetNillableEnabled(v *bool) *ChannelUsageMonitorBindingUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetTriggerStatuses sets the "trigger_statuses" field.
func (_u *ChannelUsageMonitorBindingUpdateOne) SetTriggerStatuses(v []string) *ChannelUsageMonitorBindingUpdateOne {
	_u.mutation.SetTriggerStatuses(v)
	return _u
}

// AppendTriggerStatuses appends value to the "trigger_statuses" field.
func (_u *ChannelUsageMonitorBindingUpdateOne) AppendTriggerStatuses(v []string) *ChannelUsageMonitorBindingUpdateOne {
	_u.mutation.AppendTriggerStatuses(v)
	return _u
}

// SetConditions sets the "conditions" field.
func (_u *ChannelUsageMonitorBindingUpdateOne) SetConditions(v []objects.QuotaMonitorBindingCondition) *ChannelUsageMonitorBindingUpdateOne {
	_u.mutation.SetConditions(v)
	return _u
}

// AppendConditions appends value to the "conditions" field.
func (_u *ChannelUsageMonitorBindingUpdateOne) AppendConditions(v []objects.QuotaMonitorBindingCondition) *ChannelUsageMonitorBindingUpdateOne {
	_u.mutation.AppendConditions(v)
	return _u
}

// SetLastTriggeredAt sets the "last_triggered_at" field.
func (_u *ChannelUsageMonitorBindingUpdateOne) SetLastTriggeredAt(v time.Time) *ChannelUsageMonitorBindingUpdateOne {
	_u.mutation.SetLastTriggeredAt(v)
	return _u
}

// SetNillableLastTriggeredAt sets the "last_triggered_at" field if the given value is not nil.
func (_u *ChannelUsageMonitorBindingUpdateOne) SetNillableLastTriggeredAt(v *time.Time) *ChannelUsageMonitorBindingUpdateOne {
	if v != nil {
		_u.SetLastTriggeredAt(*v)
	}
	return _u
}

// ClearLastTriggeredAt clears the value of the "last_triggered_at" field.
func (_u *ChannelUsageMonitorBindingUpdateOne) ClearLastTriggeredAt() *ChannelUsageMonitorBindingUpdateOne {
	_u.mutation.ClearLastTriggeredAt()
	return _u
}

// SetLastTriggerReason sets the "last_trigger_reason" field.
func (_u *ChannelUsageMonitorBindingUpdateOne) SetLastTriggerReason(v string) *ChannelUsageMonitorBindingUpdateOne {
	_u.mutation.SetLastTriggerReason(v)
	return _u
}

// SetNillableLastTriggerReason sets the "last_trigger_reason" field if the given value is not nil.
func (_u *ChannelUsageMonitorBindingUpdateOne) SetNillableLastTriggerReason(v *string) *ChannelUsageMonitorBindingUpdateOne {
	if v != nil {
		_u.SetLastTriggerReason(*v)
	}
	return _u
}

// ClearLastTriggerReason clears the value of the "last_trigger_reason" field.
func (_u *ChannelUsageMonitorBindingUpdateOne) ClearLastTriggerReason() *ChannelUsageMonitorBindingUpdateOne {
	_u.mutation.ClearLastTriggerReason()
	return _u
}

// Mutation returns the ChannelUsageMonitorBindingMutation object of the builder.
func (_u *ChannelUsageMonitorBindingUpdateOne) Mutation() *ChannelUsageMonitorBindingMutation {
	return _u.mutation
}

// Where appends a list predicates to the ChannelUsageMonitorBindingUpdate builder.
func (_u *ChannelUsageMonitorBindingUpdateOne) Where(ps ...predicate.ChannelUsageMonitorBinding) *ChannelUsageMonitorBindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelUsageMonitorBindingUpdateOne) Select(field string, fields ...string) *ChannelUsageMonitorBindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChannelUsageMonitorBinding entity.
func (_u *ChannelUsageMonitorBindingUpdateOne) Save(ctx context.Context) (*ChannelUsageMonitorBinding, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelUsageMonitorBindingUpdateOne) SaveX(ctx context.Context) *ChannelUsageMonitorBinding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelUsageMonitorBindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelUsageMonitorBindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelUsageMonitorBindingUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if channelusagemonitorbinding.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized channelusagemonitorbinding.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := channelusagemonitorbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelUsageMonitorBindingUpdateOne) check() error {
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelUsageMonitorBinding.channel"`)
	}
	if _u.mutation.UsageMonitorChannelCleared() && len(_u.mutation.UsageMonitorChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelUsageMonitorBinding.usage_monitor_channel"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ChannelUsageMonitorBindingUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ChannelUsageMonitorBindingUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ChannelUsageMonitorBindingUpdateOne) sqlSave(ctx context.Context) (_node *ChannelUsageMonitorBinding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelusagemonitorbinding.Table, channelusagemonitorbinding.Columns, sqlgraph.NewFieldSpec(channelusagemonitorbinding.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChannelUsageMonitorBinding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channelusagemonitorbinding.FieldID)
		for _, f := range fields {
			if !channelusagemonitorbinding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channelusagemonitorbinding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channelusagemonitorbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(channelusagemonitorbinding.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(channelusagemonitorbinding.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(channelusagemonitorbinding.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TriggerStatuses(); ok {
		_spec.SetField(channelusagemonitorbinding.FieldTriggerStatuses, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTriggerStatuses(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, channelusagemonitorbinding.FieldTriggerStatuses, value)
		})
	}
	if value, ok := _u.mutation.Conditions(); ok {
		_spec.SetField(channelusagemonitorbinding.FieldConditions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedConditions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, channelusagemonitorbinding.FieldConditions, value)
		})
	}
	if value, ok := _u.mutation.LastTriggeredAt(); ok {
		_spec.SetField(channelusagemonitorbinding.FieldLastTriggeredAt, field.TypeTime, value)
	}
	if _u.mutation.LastTriggeredAtCleared() {
		_spec.ClearField(channelusagemonitorbinding.FieldLastTriggeredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastTriggerReason(); ok {
		_spec.SetField(channelusagemonitorbinding.FieldLastTriggerReason, field.TypeString, value)
	}
	if _u.mutation.LastTriggerReasonCleared() {
		_spec.ClearField(channelusagemonitorbinding.FieldLastTriggerReason, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ChannelUsageMonitorBinding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelusagemonitorbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
