// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ldm2060/axonhub/internal/ent/channelusagemonitorbinding"
	"github.com/ldm2060/axonhub/internal/ent/predicate"
)

// ChannelUsageMonitorBindingDelete is the builder for deleting a ChannelUsageMonitorBinding entity.
type ChannelUsageMonitorBindingDelete struct {
	config
	hooks    []Hook
	mutation *ChannelUsageMonitorBindingMutation
}

// Where appends a list predicates to the ChannelUsageMonitorBindingDelete builder.
func (_d *ChannelUsageMonitorBindingDelete) Where(ps ...predicate.ChannelUsageMonitorBinding) *ChannelUsageMonitorBindingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ChannelUsageMonitorBindingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChannelUsageMonitorBindingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ChannelUsageMonitorBindingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(channelusagemonitorbinding.Table, sqlgraph.NewFieldSpec(channelusagemonitorbinding.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ChannelUsageMonitorBindingDeleteOne is the builder for deleting a single ChannelUsageMonitorBinding entity.
type ChannelUsageMonitorBindingDeleteOne struct {
	_d *ChannelUsageMonitorBindingDelete
}

// Where appends a list predicates to the ChannelUsageMonitorBindingDelete builder.
func (_d *ChannelUsageMonitorBindingDeleteOne) Where(ps ...predicate.ChannelUsageMonitorBinding) *ChannelUsageMonitorBindingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ChannelUsageMonitorBindingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{channelusagemonitorbinding.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChannelUsageMonitorBindingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
