// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ldm2060/axonhub/internal/ent/emailtoken"
	"github.com/ldm2060/axonhub/internal/ent/user"
)

// EmailTokenCreate is the builder for creating a EmailToken entity.
type EmailTokenCreate struct {
	config
	mutation *EmailTokenMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *EmailTokenCreate) SetCreatedAt(v time.Time) *EmailTokenCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EmailTokenCreate) SetNillableCreatedAt(v *time.Time) *EmailTokenCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EmailTokenCreate) SetUpdatedAt(v time.Time) *EmailTokenCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EmailTokenCreate) SetNillableUpdatedAt(v *time.Time) *EmailTokenCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetToken sets the "token" field.
func (_c *EmailTokenCreate) SetToken(v string) *EmailTokenCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetType sets the "type" field.
func (_c *EmailTokenCreate) SetType(v emailtoken.Type) *EmailTokenCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *EmailTokenCreate) SetEmail(v string) *EmailTokenCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *EmailTokenCreate) SetNillableEmail(v *string) *EmailTokenCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *EmailTokenCreate) SetExpiresAt(v time.Time) *EmailTokenCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetConsumedAt sets the "consumed_at" field.
func (_c *EmailTokenCreate) SetConsumedAt(v time.Time) *EmailTokenCreate {
	_c.mutation.SetConsumedAt(v)
	return _c
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_c *EmailTokenCreate) SetNillableConsumedAt(v *time.Time) *EmailTokenCreate {
	if v != nil {
		_c.SetConsumedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *EmailTokenCreate) SetUserID(v int) *EmailTokenCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *EmailTokenCreate) SetNillableUserID(v *int) *EmailTokenCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *EmailTokenCreate) SetUser(v *User) *EmailTokenCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the EmailTokenMutation object of the builder.
func (_c *EmailTokenCreate) Mutation() *EmailTokenMutation {
	return _c.mutation
}

// Save creates the EmailToken in the database.
func (_c *EmailTokenCreate) Save(ctx context.Context) (*EmailToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EmailTokenCreate) SaveX(ctx context.Context) *EmailToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EmailTokenCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := emailtoken.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := emailtoken.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EmailTokenCreate) check() error {
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "EmailToken.token"`)}
	}
	if v, ok := _c.mutation.Token(); ok {
		if err := emailtoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "EmailToken.token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "EmailToken.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := emailtoken.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "EmailToken.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "EmailToken.expires_at"`)}
	}
	return nil
}

func (_c *EmailTokenCreate) sqlSave(ctx context.Context) (*EmailToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EmailTokenCreate) createSpec() (*EmailToken, *sqlgraph.CreateSpec) {
	var (
		_node = &EmailToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(emailtoken.Table, sqlgraph.NewFieldSpec(emailtoken.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(emailtoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(emailtoken.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(emailtoken.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(emailtoken.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(emailtoken.FieldEmail, field.TypeString, value)
		_node.Email = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(emailtoken.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.ConsumedAt(); ok {
		_spec.SetField(emailtoken.FieldConsumedAt, field.TypeTime, value)
		_node.ConsumedAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   emailtoken.UserTable,
			Columns: []string{emailtoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EmailToken.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EmailTokenUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EmailTokenCreate) OnConflict(opts ...sql.ConflictOption) *EmailTokenUpsertOne {
	_c.conflict = opts
	return &EmailTokenUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EmailToken.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EmailTokenCreate) OnConflictColumns(columns ...string) *EmailTokenUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EmailTokenUpsertOne{
		create: _c,
	}
}

type (
	// EmailTokenUpsertOne is the builder for "upsert"-ing
	//  one EmailToken node.
	EmailTokenUpsertOne struct {
		create *EmailTokenCreate
	}

	// EmailTokenUpsert is the "OnConflict" setter.
	EmailTokenUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *EmailTokenUpsert) SetUpdatedAt(v time.Time) *EmailTokenUpsert {
	u.Set(emailtoken.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EmailTokenUpsert) UpdateUpdatedAt() *EmailTokenUpsert {
	u.SetExcluded(emailtoken.FieldUpdatedAt)
	return u
}

// SetToken sets the "token" field.
func (u *EmailTokenUpsert) SetToken(v string) *EmailTokenUpsert {
	u.Set(emailtoken.FieldToken, v)
	return u
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *EmailTokenUpsert) UpdateToken() *EmailTokenUpsert {
	u.SetExcluded(emailtoken.FieldToken)
	return u
}

// SetType sets the "type" field.
func (u *EmailTokenUpsert) SetType(v emailtoken.Type) *EmailTokenUpsert {
	u.Set(emailtoken.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *EmailTokenUpsert) UpdateType() *EmailTokenUpsert {
	u.SetExcluded(emailtoken.FieldType)
	return u
}

// SetEmail sets the "email" field.
func (u *EmailTokenUpsert) SetEmail(v string) *EmailTokenUpsert {
	u.Set(emailtoken.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *EmailTokenUpsert) UpdateEmail() *EmailTokenUpsert {
	u.SetExcluded(emailtoken.FieldEmail)
	return u
}

// ClearEmail clears the value of the "email" field.
func (u *EmailTokenUpsert) ClearEmail() *EmailTokenUpsert {
	u.SetNull(emailtoken.FieldEmail)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *EmailTokenUpsert) SetExpiresAt(v time.Time) *EmailTokenUpsert {
	u.Set(emailtoken.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *EmailTokenUpsert) UpdateExpiresAt() *EmailTokenUpsert {
	u.SetExcluded(emailtoken.FieldExpiresAt)
	return u
}

// SetConsumedAt sets the "consumed_at" field.
func (u *EmailTokenUpsert) SetConsumedAt(v time.Time) *EmailTokenUpsert {
	u.Set(emailtoken.FieldConsumedAt, v)
	return u
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *EmailTokenUpsert) UpdateConsumedAt() *EmailTokenUpsert {
	u.SetExcluded(emailtoken.FieldConsumedAt)
	return u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *EmailTokenUpsert) ClearConsumedAt() *EmailTokenUpsert {
	u.SetNull(emailtoken.FieldConsumedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *EmailTokenUpsert) SetUserID(v int) *EmailTokenUpsert {
	u.Set(emailtoken.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EmailTokenUpsert) UpdateUserID() *EmailTokenUpsert {
	u.SetExcluded(emailtoken.FieldUserID)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *EmailTokenUpsert) ClearUserID() *EmailTokenUpsert {
	u.SetNull(emailtoken.FieldUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EmailToken.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EmailTokenUpsertOne) UpdateNewValues() *EmailTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(emailtoken.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EmailToken.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EmailTokenUpsertOne) Ignore() *EmailTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EmailTokenUpsertOne) DoNothing() *EmailTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EmailTokenCreate.OnConflict
// documentation for more info.
func (u *EmailTokenUpsertOne) Update(set func(*EmailTokenUpsert)) *EmailTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EmailTokenUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EmailTokenUpsertOne) SetUpdatedAt(v time.Time) *EmailTokenUpsertOne {
	return u.Update(func(s *EmailTokenUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EmailTokenUpsertOne) UpdateUpdatedAt() *EmailTokenUpsertOne {
	return u.Update(func(s *EmailTokenUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetToken sets the "token" field.
func (u *EmailTokenUpsertOne) SetToken(v string) *EmailTokenUpsertOne {
	return u.Update(func(s *EmailTokenUpsert) {
		s.SetToken(v)
	})
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *EmailTokenUpsertOne) UpdateToken() *EmailTokenUpsertOne {
	return u.Update(func(s *EmailTokenUpsert) {
		s.UpdateToken()
	})
}

// SetType sets the "type" field.
func (u *EmailTokenUpsertOne) SetType(v emailtoken.Type) *EmailTokenUpsertOne {
	return u.Update(func(s *EmailTokenUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *EmailTokenUpsertOne) UpdateType() *EmailTokenUpsertOne {
	return u.Update(func(s *EmailTokenUpsert) {
		s.UpdateType()
	})
}

// SetEmail sets the "email" field.
func (u *EmailTokenUpsertOne) SetEmail(v string) *EmailTokenUpsertOne {
	return u.Update(func(s *EmailTokenUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *EmailTokenUpsertOne) UpdateEmail() *EmailTokenUpsertOne {
	return u.Update(func(s *EmailTokenUpsert) {
		s.UpdateEmail()
	})
}

// ClearEmail clears the value of the "email" field.
func (u *EmailTokenUpsertOne) ClearEmail() *EmailTokenUpsertOne {
	return u.Update(func(s *EmailTokenUpsert) {
		s.ClearEmail()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *EmailTokenUpsertOne) SetExpiresAt(v time.Time) *EmailTokenUpsertOne {
	return u.Update(func(s *EmailTokenUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *EmailTokenUpsertOne) UpdateExpiresAt() *EmailTokenUpsertOne {
	return u.Update(func(s *EmailTokenUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *EmailTokenUpsertOne) SetConsumedAt(v time.Time) *EmailTokenUpsertOne {
	return u.Update(func(s *EmailTokenUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *EmailTokenUpsertOne) UpdateConsumedAt() *EmailTokenUpsertOne {
	return u.Update(func(s *EmailTokenUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *EmailTokenUpsertOne) ClearConsumedAt() *EmailTokenUpsertOne {
	return u.Update(func(s *EmailTokenUpsert) {
		s.ClearConsumedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *EmailTokenUpsertOne) SetUserID(v int) *EmailTokenUpsertOne {
	return u.Update(func(s *EmailTokenUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EmailTokenUpsertOne) UpdateUserID() *EmailTokenUpsertOne {
	return u.Update(func(s *EmailTokenUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *EmailTokenUpsertOne) ClearUserID() *EmailTokenUpsertOne {
	return u.Update(func(s *EmailTokenUpsert) {
		s.ClearUserID()
	})
}

// Exec executes the query.
func (u *EmailTokenUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EmailTokenCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EmailTokenUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EmailTokenUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EmailTokenUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EmailTokenCreateBulk is the builder for creating many EmailToken entities in bulk.
type EmailTokenCreateBulk struct {
	config
	err      error
	builders []*EmailTokenCreate
	conflict []sql.ConflictOption
}

// Save creates the EmailToken entities in the database.
func (_c *EmailTokenCreateBulk) Save(ctx context.Context) ([]*EmailToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EmailToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmailTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EmailTokenCreateBulk) SaveX(ctx context.Context) []*EmailToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EmailToken.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EmailTokenUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EmailTokenCreateBulk) OnConflict(opts ...sql.ConflictOption) *EmailTokenUpsertBulk {
	_c.conflict = opts
	return &EmailTokenUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EmailToken.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EmailTokenCreateBulk) OnConflictColumns(columns ...string) *EmailTokenUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EmailTokenUpsertBulk{
		create: _c,
	}
}

// EmailTokenUpsertBulk is the builder for "upsert"-ing
// a bulk of EmailToken nodes.
type EmailTokenUpsertBulk struct {
	create *EmailTokenCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EmailToken.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EmailTokenUpsertBulk) UpdateNewValues() *EmailTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(emailtoken.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EmailToken.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EmailTokenUpsertBulk) Ignore() *EmailTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EmailTokenUpsertBulk) DoNothing() *EmailTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EmailTokenCreateBulk.OnConflict
// documentation for more info.
func (u *EmailTokenUpsertBulk) Update(set func(*EmailTokenUpsert)) *EmailTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EmailTokenUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EmailTokenUpsertBulk) SetUpdatedAt(v time.Time) *EmailTokenUpsertBulk {
	return u.Update(func(s *EmailTokenUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EmailTokenUpsertBulk) UpdateUpdatedAt() *EmailTokenUpsertBulk {
	return u.Update(func(s *EmailTokenUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetToken sets the "token" field.
func (u *EmailTokenUpsertBulk) SetToken(v string) *EmailTokenUpsertBulk {
	return u.Update(func(s *EmailTokenUpsert) {
		s.SetToken(v)
	})
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *EmailTokenUpsertBulk) UpdateToken() *EmailTokenUpsertBulk {
	return u.Update(func(s *EmailTokenUpsert) {
		s.UpdateToken()
	})
}

// SetType sets the "type" field.
func (u *EmailTokenUpsertBulk) SetType(v emailtoken.Type) *EmailTokenUpsertBulk {
	return u.Update(func(s *EmailTokenUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *EmailTokenUpsertBulk) UpdateType() *EmailTokenUpsertBulk {
	return u.Update(func(s *EmailTokenUpsert) {
		s.UpdateType()
	})
}

// SetEmail sets the "email" field.
func (u *EmailTokenUpsertBulk) SetEmail(v string) *EmailTokenUpsertBulk {
	return u.Update(func(s *EmailTokenUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *EmailTokenUpsertBulk) UpdateEmail() *EmailTokenUpsertBulk {
	return u.Update(func(s *EmailTokenUpsert) {
		s.UpdateEmail()
	})
}

// ClearEmail clears the value of the "email" field.
func (u *EmailTokenUpsertBulk) ClearEmail() *EmailTokenUpsertBulk {
	return u.Update(func(s *EmailTokenUpsert) {
		s.ClearEmail()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *EmailTokenUpsertBulk) SetExpiresAt(v time.Time) *EmailTokenUpsertBulk {
	return u.Update(func(s *EmailTokenUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *EmailTokenUpsertBulk) UpdateExpiresAt() *EmailTokenUpsertBulk {
	return u.Update(func(s *EmailTokenUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *EmailTokenUpsertBulk) SetConsumedAt(v time.Time) *EmailTokenUpsertBulk {
	return u.Update(func(s *EmailTokenUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *EmailTokenUpsertBulk) UpdateConsumedAt() *EmailTokenUpsertBulk {
	return u.Update(func(s *EmailTokenUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *EmailTokenUpsertBulk) ClearConsumedAt() *EmailTokenUpsertBulk {
	return u.Update(func(s *EmailTokenUpsert) {
		s.ClearConsumedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *EmailTokenUpsertBulk) SetUserID(v int) *EmailTokenUpsertBulk {
	return u.Update(func(s *EmailTokenUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EmailTokenUpsertBulk) UpdateUserID() *EmailTokenUpsertBulk {
	return u.Update(func(s *EmailTokenUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *EmailTokenUpsertBulk) ClearUserID() *EmailTokenUpsertBulk {
	return u.Update(func(s *EmailTokenUpsert) {
		s.ClearUserID()
	})
}

// Exec executes the query.
func (u *EmailTokenUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EmailTokenCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EmailTokenCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EmailTokenUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
