// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ldm2060/axonhub/internal/ent/publishrequest"
	"github.com/ldm2060/axonhub/internal/ent/user"
)

// PublishRequestCreate is the builder for creating a PublishRequest entity.
type PublishRequestCreate struct {
	config
	mutation *PublishRequestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PublishRequestCreate) SetCreatedAt(v time.Time) *PublishRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PublishRequestCreate) SetNillableCreatedAt(v *time.Time) *PublishRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PublishRequestCreate) SetUpdatedAt(v time.Time) *PublishRequestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PublishRequestCreate) SetNillableUpdatedAt(v *time.Time) *PublishRequestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *PublishRequestCreate) SetDeletedAt(v int) *PublishRequestCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *PublishRequestCreate) SetNillableDeletedAt(v *int) *PublishRequestCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetResourceType sets the "resource_type" field.
func (_c *PublishRequestCreate) SetResourceType(v publishrequest.ResourceType) *PublishRequestCreate {
	_c.mutation.SetResourceType(v)
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *PublishRequestCreate) SetResourceID(v int) *PublishRequestCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetRequesterID sets the "requester_id" field.
func (_c *PublishRequestCreate) SetRequesterID(v int) *PublishRequestCreate {
	_c.mutation.SetRequesterID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *PublishRequestCreate) SetStatus(v publishrequest.Status) *PublishRequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PublishRequestCreate) SetNillableStatus(v *publishrequest.Status) *PublishRequestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetReviewerID sets the "reviewer_id" field.
func (_c *PublishRequestCreate) SetReviewerID(v int) *PublishRequestCreate {
	_c.mutation.SetReviewerID(v)
	return _c
}

// SetNillableReviewerID sets the "reviewer_id" field if the given value is not nil.
func (_c *PublishRequestCreate) SetNillableReviewerID(v *int) *PublishRequestCreate {
	if v != nil {
		_c.SetReviewerID(*v)
	}
	return _c
}

// SetReviewComment sets the "review_comment" field.
func (_c *PublishRequestCreate) SetReviewComment(v string) *PublishRequestCreate {
	_c.mutation.SetReviewComment(v)
	return _c
}

// SetNillableReviewComment sets the "review_comment" field if the given value is not nil.
func (_c *PublishRequestCreate) SetNillableReviewComment(v *string) *PublishRequestCreate {
	if v != nil {
		_c.SetReviewComment(*v)
	}
	return _c
}

// SetRequestComment sets the "request_comment" field.
func (_c *PublishRequestCreate) SetRequestComment(v string) *PublishRequestCreate {
	_c.mutation.SetRequestComment(v)
	return _c
}

// SetNillableRequestComment sets the "request_comment" field if the given value is not nil.
func (_c *PublishRequestCreate) SetNillableRequestComment(v *string) *PublishRequestCreate {
	if v != nil {
		_c.SetRequestComment(*v)
	}
	return _c
}

// SetRequester sets the "requester" edge to the User entity.
func (_c *PublishRequestCreate) SetRequester(v *User) *PublishRequestCreate {
	return _c.SetRequesterID(v.ID)
}

// SetReviewer sets the "reviewer" edge to the User entity.
func (_c *PublishRequestCreate) SetReviewer(v *User) *PublishRequestCreate {
	return _c.SetReviewerID(v.ID)
}

// Mutation returns the PublishRequestMutation object of the builder.
func (_c *PublishRequestCreate) Mutation() *PublishRequestMutation {
	return _c.mutation
}

// Save creates the PublishRequest in the database.
func (_c *PublishRequestCreate) Save(ctx context.Context) (*PublishRequest, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PublishRequestCreate) SaveX(ctx context.Context) *PublishRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PublishRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PublishRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PublishRequestCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if publishrequest.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized publishrequest.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := publishrequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if publishrequest.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized publishrequest.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := publishrequest.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := publishrequest.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := publishrequest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *PublishRequestCreate) check() error {
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "PublishRequest.deleted_at"`)}
	}
	if _, ok := _c.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "PublishRequest.resource_type"`)}
	}
	if v, ok := _c.mutation.ResourceType(); ok {
		if err := publishrequest.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "PublishRequest.resource_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "PublishRequest.resource_id"`)}
	}
	if _, ok := _c.mutation.RequesterID(); !ok {
		return &ValidationError{Name: "requester_id", err: errors.New(`ent: missing required field "PublishRequest.requester_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PublishRequest.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := publishrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PublishRequest.status": %w`, err)}
		}
	}
	if len(_c.mutation.RequesterIDs()) == 0 {
		return &ValidationError{Name: "requester", err: errors.New(`ent: missing required edge "PublishRequest.requester"`)}
	}
	return nil
}

func (_c *PublishRequestCreate) sqlSave(ctx context.Context) (*PublishRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PublishRequestCreate) createSpec() (*PublishRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &PublishRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(publishrequest.Table, sqlgraph.NewFieldSpec(publishrequest.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(publishrequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(publishrequest.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(publishrequest.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.ResourceType(); ok {
		_spec.SetField(publishrequest.FieldResourceType, field.TypeEnum, value)
		_node.ResourceType = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(publishrequest.FieldResourceID, field.TypeInt, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(publishrequest.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ReviewComment(); ok {
		_spec.SetField(publishrequest.FieldReviewComment, field.TypeString, value)
		_node.ReviewComment = &value
	}
	if value, ok := _c.mutation.RequestComment(); ok {
		_spec.SetField(publishrequest.FieldRequestComment, field.TypeString, value)
		_node.RequestComment = &value
	}
	if nodes := _c.mutation.RequesterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   publishrequest.RequesterTable,
			Columns: []string{publishrequest.RequesterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RequesterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReviewerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   publishrequest.ReviewerTable,
			Columns: []string{publishrequest.ReviewerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ReviewerID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PublishRequest.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PublishRequestUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PublishRequestCreate) OnConflict(opts ...sql.ConflictOption) *PublishRequestUpsertOne {
	_c.conflict = opts
	return &PublishRequestUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PublishRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PublishRequestCreate) OnConflictColumns(columns ...string) *PublishRequestUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PublishRequestUpsertOne{
		create: _c,
	}
}

type (
	// PublishRequestUpsertOne is the builder for "upsert"-ing
	//  one PublishRequest node.
	PublishRequestUpsertOne struct {
		create *PublishRequestCreate
	}

	// PublishRequestUpsert is the "OnConflict" setter.
	PublishRequestUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PublishRequestUpsert) SetUpdatedAt(v time.Time) *PublishRequestUpsert {
	u.Set(publishrequest.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PublishRequestUpsert) UpdateUpdatedAt() *PublishRequestUpsert {
	u.SetExcluded(publishrequest.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PublishRequestUpsert) SetDeletedAt(v int) *PublishRequestUpsert {
	u.Set(publishrequest.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PublishRequestUpsert) UpdateDeletedAt() *PublishRequestUpsert {
	u.SetExcluded(publishrequest.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *PublishRequestUpsert) AddDeletedAt(v int) *PublishRequestUpsert {
	u.Add(publishrequest.FieldDeletedAt, v)
	return u
}

// SetStatus sets the "status" field.
func (u *PublishRequestUpsert) SetStatus(v publishrequest.Status) *PublishRequestUpsert {
	u.Set(publishrequest.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PublishRequestUpsert) UpdateStatus() *PublishRequestUpsert {
	u.SetExcluded(publishrequest.FieldStatus)
	return u
}

// SetReviewerID sets the "reviewer_id" field.
func (u *PublishRequestUpsert) SetReviewerID(v int) *PublishRequestUpsert {
	u.Set(publishrequest.FieldReviewerID, v)
	return u
}

// UpdateReviewerID sets the "reviewer_id" field to the value that was provided on create.
func (u *PublishRequestUpsert) UpdateReviewerID() *PublishRequestUpsert {
	u.SetExcluded(publishrequest.FieldReviewerID)
	return u
}

// ClearReviewerID clears the value of the "reviewer_id" field.
func (u *PublishRequestUpsert) ClearReviewerID() *PublishRequestUpsert {
	u.SetNull(publishrequest.FieldReviewerID)
	return u
}

// SetReviewComment sets the "review_comment" field.
func (u *PublishRequestUpsert) SetReviewComment(v string) *PublishRequestUpsert {
	u.Set(publishrequest.FieldReviewComment, v)
	return u
}

// UpdateReviewComment sets the "review_comment" field to the value that was provided on create.
func (u *PublishRequestUpsert) UpdateReviewComment() *PublishRequestUpsert {
	u.SetExcluded(publishrequest.FieldReviewComment)
	return u
}

// ClearReviewComment clears the value of the "review_comment" field.
func (u *PublishRequestUpsert) ClearReviewComment() *PublishRequestUpsert {
	u.SetNull(publishrequest.FieldReviewComment)
	return u
}

// SetRequestComment sets the "request_comment" field.
func (u *PublishRequestUpsert) SetRequestComment(v string) *PublishRequestUpsert {
	u.Set(publishrequest.FieldRequestComment, v)
	return u
}

// UpdateRequestComment sets the "request_comment" field to the value that was provided on create.
func (u *PublishRequestUpsert) UpdateRequestComment() *PublishRequestUpsert {
	u.SetExcluded(publishrequest.FieldRequestComment)
	return u
}

// ClearRequestComment clears the value of the "request_comment" field.
func (u *PublishRequestUpsert) ClearRequestComment() *PublishRequestUpsert {
	u.SetNull(publishrequest.FieldRequestComment)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PublishRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PublishRequestUpsertOne) UpdateNewValues() *PublishRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(publishrequest.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.ResourceType(); exists {
			s.SetIgnore(publishrequest.FieldResourceType)
		}
		if _, exists := u.create.mutation.ResourceID(); exists {
			s.SetIgnore(publishrequest.FieldResourceID)
		}
		if _, exists := u.create.mutation.RequesterID(); exists {
			s.SetIgnore(publishrequest.FieldRequesterID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PublishRequest.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PublishRequestUpsertOne) Ignore() *PublishRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PublishRequestUpsertOne) DoNothing() *PublishRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PublishRequestCreate.OnConflict
// documentation for more info.
func (u *PublishRequestUpsertOne) Update(set func(*PublishRequestUpsert)) *PublishRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PublishRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PublishRequestUpsertOne) SetUpdatedAt(v time.Time) *PublishRequestUpsertOne {
	return u.Update(func(s *PublishRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PublishRequestUpsertOne) UpdateUpdatedAt() *PublishRequestUpsertOne {
	return u.Update(func(s *PublishRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PublishRequestUpsertOne) SetDeletedAt(v int) *PublishRequestUpsertOne {
	return u.Update(func(s *PublishRequestUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *PublishRequestUpsertOne) AddDeletedAt(v int) *PublishRequestUpsertOne {
	return u.Update(func(s *PublishRequestUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PublishRequestUpsertOne) UpdateDeletedAt() *PublishRequestUpsertOne {
	return u.Update(func(s *PublishRequestUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetStatus sets the "status" field.
func (u *PublishRequestUpsertOne) SetStatus(v publishrequest.Status) *PublishRequestUpsertOne {
	return u.Update(func(s *PublishRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PublishRequestUpsertOne) UpdateStatus() *PublishRequestUpsertOne {
	return u.Update(func(s *PublishRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetReviewerID sets the "reviewer_id" field.
func (u *PublishRequestUpsertOne) SetReviewerID(v int) *PublishRequestUpsertOne {
	return u.Update(func(s *PublishRequestUpsert) {
		s.SetReviewerID(v)
	})
}

// UpdateReviewerID sets the "reviewer_id" field to the value that was provided on create.
func (u *PublishRequestUpsertOne) UpdateReviewerID() *PublishRequestUpsertOne {
	return u.Update(func(s *PublishRequestUpsert) {
		s.UpdateReviewerID()
	})
}

// ClearReviewerID clears the value of the "reviewer_id" field.
func (u *PublishRequestUpsertOne) ClearReviewerID() *PublishRequestUpsertOne {
	return u.Update(func(s *PublishRequestUpsert) {
		s.ClearReviewerID()
	})
}

// SetReviewComment sets the "review_comment" field.
func (u *PublishRequestUpsertOne) SetReviewComment(v string) *PublishRequestUpsertOne {
	return u.Update(func(s *PublishRequestUpsert) {
		s.SetReviewComment(v)
	})
}

// UpdateReviewComment sets the "review_comment" field to the value that was provided on create.
func (u *PublishRequestUpsertOne) UpdateReviewComment() *PublishRequestUpsertOne {
	return u.Update(func(s *PublishRequestUpsert) {
		s.UpdateReviewComment()
	})
}

// ClearReviewComment clears the value of the "review_comment" field.
func (u *PublishRequestUpsertOne) ClearReviewComment() *PublishRequestUpsertOne {
	return u.Update(func(s *PublishRequestUpsert) {
		s.ClearReviewComment()
	})
}

// SetRequestComment sets the "request_comment" field.
func (u *PublishRequestUpsertOne) SetRequestComment(v string) *PublishRequestUpsertOne {
	return u.Update(func(s *PublishRequestUpsert) {
		s.SetRequestComment(v)
	})
}

// UpdateRequestComment sets the "request_comment" field to the value that was provided on create.
func (u *PublishRequestUpsertOne) UpdateRequestComment() *PublishRequestUpsertOne {
	return u.Update(func(s *PublishRequestUpsert) {
		s.UpdateRequestComment()
	})
}

// ClearRequestComment clears the value of the "request_comment" field.
func (u *PublishRequestUpsertOne) ClearRequestComment() *PublishRequestUpsertOne {
	return u.Update(func(s *PublishRequestUpsert) {
		s.ClearRequestComment()
	})
}

// Exec executes the query.
func (u *PublishRequestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PublishRequestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PublishRequestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PublishRequestUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PublishRequestUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PublishRequestCreateBulk is the builder for creating many PublishRequest entities in bulk.
type PublishRequestCreateBulk struct {
	config
	err      error
	builders []*PublishRequestCreate
	conflict []sql.ConflictOption
}

// Save creates the PublishRequest entities in the database.
func (_c *PublishRequestCreateBulk) Save(ctx context.Context) ([]*PublishRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PublishRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PublishRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PublishRequestCreateBulk) SaveX(ctx context.Context) []*PublishRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PublishRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PublishRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PublishRequest.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PublishRequestUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PublishRequestCreateBulk) OnConflict(opts ...sql.ConflictOption) *PublishRequestUpsertBulk {
	_c.conflict = opts
	return &PublishRequestUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PublishRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PublishRequestCreateBulk) OnConflictColumns(columns ...string) *PublishRequestUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PublishRequestUpsertBulk{
		create: _c,
	}
}

// PublishRequestUpsertBulk is the builder for "upsert"-ing
// a bulk of PublishRequest nodes.
type PublishRequestUpsertBulk struct {
	create *PublishRequestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PublishRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PublishRequestUpsertBulk) UpdateNewValues() *PublishRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(publishrequest.FieldCreatedAt)
			}
			if _, exists := b.mutation.ResourceType(); exists {
				s.SetIgnore(publishrequest.FieldResourceType)
			}
			if _, exists := b.mutation.ResourceID(); exists {
				s.SetIgnore(publishrequest.FieldResourceID)
			}
			if _, exists := b.mutation.RequesterID(); exists {
				s.SetIgnore(publishrequest.FieldRequesterID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PublishRequest.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PublishRequestUpsertBulk) Ignore() *PublishRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PublishRequestUpsertBulk) DoNothing() *PublishRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PublishRequestCreateBulk.OnConflict
// documentation for more info.
func (u *PublishRequestUpsertBulk) Update(set func(*PublishRequestUpsert)) *PublishRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PublishRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PublishRequestUpsertBulk) SetUpdatedAt(v time.Time) *PublishRequestUpsertBulk {
	return u.Update(func(s *PublishRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PublishRequestUpsertBulk) UpdateUpdatedAt() *PublishRequestUpsertBulk {
	return u.Update(func(s *PublishRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PublishRequestUpsertBulk) SetDeletedAt(v int) *PublishRequestUpsertBulk {
	return u.Update(func(s *PublishRequestUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *PublishRequestUpsertBulk) AddDeletedAt(v int) *PublishRequestUpsertBulk {
	return u.Update(func(s *PublishRequestUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PublishRequestUpsertBulk) UpdateDeletedAt() *PublishRequestUpsertBulk {
	return u.Update(func(s *PublishRequestUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetStatus sets the "status" field.
func (u *PublishRequestUpsertBulk) SetStatus(v publishrequest.Status) *PublishRequestUpsertBulk {
	return u.Update(func(s *PublishRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PublishRequestUpsertBulk) UpdateStatus() *PublishRequestUpsertBulk {
	return u.Update(func(s *PublishRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetReviewerID sets the "reviewer_id" field.
func (u *PublishRequestUpsertBulk) SetReviewerID(v int) *PublishRequestUpsertBulk {
	return u.Update(func(s *PublishRequestUpsert) {
		s.SetReviewerID(v)
	})
}

// UpdateReviewerID sets the "reviewer_id" field to the value that was provided on create.
func (u *PublishRequestUpsertBulk) UpdateReviewerID() *PublishRequestUpsertBulk {
	return u.Update(func(s *PublishRequestUpsert) {
		s.UpdateReviewerID()
	})
}

// ClearReviewerID clears the value of the "reviewer_id" field.
func (u *PublishRequestUpsertBulk) ClearReviewerID() *PublishRequestUpsertBulk {
	return u.Update(func(s *PublishRequestUpsert) {
		s.ClearReviewerID()
	})
}

// SetReviewComment sets the "review_comment" field.
func (u *PublishRequestUpsertBulk) SetReviewComment(v string) *PublishRequestUpsertBulk {
	return u.Update(func(s *PublishRequestUpsert) {
		s.SetReviewComment(v)
	})
}

// UpdateReviewComment sets the "review_comment" field to the value that was provided on create.
func (u *PublishRequestUpsertBulk) UpdateReviewComment() *PublishRequestUpsertBulk {
	return u.Update(func(s *PublishRequestUpsert) {
		s.UpdateReviewComment()
	})
}

// ClearReviewComment clears the value of the "review_comment" field.
func (u *PublishRequestUpsertBulk) ClearReviewComment() *PublishRequestUpsertBulk {
	return u.Update(func(s *PublishRequestUpsert) {
		s.ClearReviewComment()
	})
}

// SetRequestComment sets the "request_comment" field.
func (u *PublishRequestUpsertBulk) SetRequestComment(v string) *PublishRequestUpsertBulk {
	return u.Update(func(s *PublishRequestUpsert) {
		s.SetRequestComment(v)
	})
}

// UpdateRequestComment sets the "request_comment" field to the value that was provided on create.
func (u *PublishRequestUpsertBulk) UpdateRequestComment() *PublishRequestUpsertBulk {
	return u.Update(func(s *PublishRequestUpsert) {
		s.UpdateRequestComment()
	})
}

// ClearRequestComment clears the value of the "request_comment" field.
func (u *PublishRequestUpsertBulk) ClearRequestComment() *PublishRequestUpsertBulk {
	return u.Update(func(s *PublishRequestUpsert) {
		s.ClearRequestComment()
	})
}

// Exec executes the query.
func (u *PublishRequestUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PublishRequestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PublishRequestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PublishRequestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
