// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ldm2060/axonhub/internal/ent/channel"
	"github.com/ldm2060/axonhub/internal/ent/usagemonitorchannel"
	"github.com/ldm2060/axonhub/internal/ent/user"
)

// UsageMonitorChannel is the model entity for the UsageMonitorChannel schema.
type UsageMonitorChannel struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int `json:"deleted_at,omitempty"`
	// Display name for this monitoring channel
	Name string `json:"name,omitempty"`
	// builtin: linked to existing Channel; custom: fully manual; template: from provider template
	Source usagemonitorchannel.Source `json:"source,omitempty"`
	// Provider type for quota template (required when source=template)
	ProviderType usagemonitorchannel.ProviderType `json:"provider_type,omitempty"`
	// FK to Channel table (required when source=builtin)
	ChannelID *int `json:"channel_id,omitempty"`
	// API endpoint for quota query
	APIURL string `json:"api_url,omitempty"`
	// HTTP method for the quota API
	APIMethod usagemonitorchannel.APIMethod `json:"api_method,omitempty"`
	// HTTP request headers as JSON
	APIHeaders map[string]interface{} `json:"api_headers,omitempty"`
	// Request body template for POST
	APIBody string `json:"api_body,omitempty"`
	// API key for authenticating with the provider (sensitive, hidden from GraphQL)
	APIKey string `json:"-"`
	// Polling interval in seconds
	PollInterval int `json:"poll_interval,omitempty"`
	// Array of field configurations
	Fields []map[string]interface{} `json:"fields,omitempty"`
	// Last successful poll timestamp
	LastPollAt *time.Time `json:"last_poll_at,omitempty"`
	// Last poll parsed data for degraded display
	LastPollData map[string]interface{} `json:"last_poll_data,omitempty"`
	// Last poll error message
	LastPollError *string `json:"last_poll_error,omitempty"`
	// Current status of this monitor channel
	Status usagemonitorchannel.Status `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UsageMonitorChannelQuery when eager-loading is set.
	Edges                       UsageMonitorChannelEdges `json:"edges"`
	user_usage_monitor_channels *int
	selectValues                sql.SelectValues
}

// UsageMonitorChannelEdges holds the relations/edges for other nodes in the graph.
type UsageMonitorChannelEdges struct {
	// Channel holds the value of the channel edge.
	Channel *Channel `json:"channel,omitempty"`
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageMonitorChannelEdges) ChannelOrErr() (*Channel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: channel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageMonitorChannelEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageMonitorChannel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usagemonitorchannel.FieldAPIHeaders, usagemonitorchannel.FieldFields, usagemonitorchannel.FieldLastPollData:
			values[i] = new([]byte)
		case usagemonitorchannel.FieldID, usagemonitorchannel.FieldDeletedAt, usagemonitorchannel.FieldChannelID, usagemonitorchannel.FieldPollInterval:
			values[i] = new(sql.NullInt64)
		case usagemonitorchannel.FieldName, usagemonitorchannel.FieldSource, usagemonitorchannel.FieldProviderType, usagemonitorchannel.FieldAPIURL, usagemonitorchannel.FieldAPIMethod, usagemonitorchannel.FieldAPIBody, usagemonitorchannel.FieldAPIKey, usagemonitorchannel.FieldLastPollError, usagemonitorchannel.FieldStatus:
			values[i] = new(sql.NullString)
		case usagemonitorchannel.FieldCreatedAt, usagemonitorchannel.FieldUpdatedAt, usagemonitorchannel.FieldLastPollAt:
			values[i] = new(sql.NullTime)
		case usagemonitorchannel.ForeignKeys[0]: // user_usage_monitor_channels
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageMonitorChannel fields.
func (_m *UsageMonitorChannel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usagemonitorchannel.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case usagemonitorchannel.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usagemonitorchannel.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case usagemonitorchannel.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = int(value.Int64)
			}
		case usagemonitorchannel.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case usagemonitorchannel.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = usagemonitorchannel.Source(value.String)
			}
		case usagemonitorchannel.FieldProviderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_type", values[i])
			} else if value.Valid {
				_m.ProviderType = usagemonitorchannel.ProviderType(value.String)
			}
		case usagemonitorchannel.FieldChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = new(int)
				*_m.ChannelID = int(value.Int64)
			}
		case usagemonitorchannel.FieldAPIURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_url", values[i])
			} else if value.Valid {
				_m.APIURL = value.String
			}
		case usagemonitorchannel.FieldAPIMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_method", values[i])
			} else if value.Valid {
				_m.APIMethod = usagemonitorchannel.APIMethod(value.String)
			}
		case usagemonitorchannel.FieldAPIHeaders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field api_headers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.APIHeaders); err != nil {
					return fmt.Errorf("unmarshal field api_headers: %w", err)
				}
			}
		case usagemonitorchannel.FieldAPIBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_body", values[i])
			} else if value.Valid {
				_m.APIBody = value.String
			}
		case usagemonitorchannel.FieldAPIKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key", values[i])
			} else if value.Valid {
				_m.APIKey = value.String
			}
		case usagemonitorchannel.FieldPollInterval:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field poll_interval", values[i])
			} else if value.Valid {
				_m.PollInterval = int(value.Int64)
			}
		case usagemonitorchannel.FieldFields:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field fields", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Fields); err != nil {
					return fmt.Errorf("unmarshal field fields: %w", err)
				}
			}
		case usagemonitorchannel.FieldLastPollAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_poll_at", values[i])
			} else if value.Valid {
				_m.LastPollAt = new(time.Time)
				*_m.LastPollAt = value.Time
			}
		case usagemonitorchannel.FieldLastPollData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field last_poll_data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.LastPollData); err != nil {
					return fmt.Errorf("unmarshal field last_poll_data: %w", err)
				}
			}
		case usagemonitorchannel.FieldLastPollError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_poll_error", values[i])
			} else if value.Valid {
				_m.LastPollError = new(string)
				*_m.LastPollError = value.String
			}
		case usagemonitorchannel.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = usagemonitorchannel.Status(value.String)
			}
		case usagemonitorchannel.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_usage_monitor_channels", value)
			} else if value.Valid {
				_m.user_usage_monitor_channels = new(int)
				*_m.user_usage_monitor_channels = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsageMonitorChannel.
// This includes values selected through modifiers, order, etc.
func (_m *UsageMonitorChannel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChannel queries the "channel" edge of the UsageMonitorChannel entity.
func (_m *UsageMonitorChannel) QueryChannel() *ChannelQuery {
	return NewUsageMonitorChannelClient(_m.config).QueryChannel(_m)
}

// QueryOwner queries the "owner" edge of the UsageMonitorChannel entity.
func (_m *UsageMonitorChannel) QueryOwner() *UserQuery {
	return NewUsageMonitorChannelClient(_m.config).QueryOwner(_m)
}

// Update returns a builder for updating this UsageMonitorChannel.
// Note that you need to call UsageMonitorChannel.Unwrap() before calling this method if this UsageMonitorChannel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UsageMonitorChannel) Update() *UsageMonitorChannelUpdateOne {
	return NewUsageMonitorChannelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UsageMonitorChannel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UsageMonitorChannel) Unwrap() *UsageMonitorChannel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageMonitorChannel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UsageMonitorChannel) String() string {
	var builder strings.Builder
	builder.WriteString("UsageMonitorChannel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(fmt.Sprintf("%v", _m.Source))
	builder.WriteString(", ")
	builder.WriteString("provider_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderType))
	builder.WriteString(", ")
	if v := _m.ChannelID; v != nil {
		builder.WriteString("channel_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("api_url=")
	builder.WriteString(_m.APIURL)
	builder.WriteString(", ")
	builder.WriteString("api_method=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIMethod))
	builder.WriteString(", ")
	builder.WriteString("api_headers=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIHeaders))
	builder.WriteString(", ")
	builder.WriteString("api_body=")
	builder.WriteString(_m.APIBody)
	builder.WriteString(", ")
	builder.WriteString("api_key=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("poll_interval=")
	builder.WriteString(fmt.Sprintf("%v", _m.PollInterval))
	builder.WriteString(", ")
	builder.WriteString("fields=")
	builder.WriteString(fmt.Sprintf("%v", _m.Fields))
	builder.WriteString(", ")
	if v := _m.LastPollAt; v != nil {
		builder.WriteString("last_poll_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_poll_data=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastPollData))
	builder.WriteString(", ")
	if v := _m.LastPollError; v != nil {
		builder.WriteString("last_poll_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteByte(')')
	return builder.String()
}

// UsageMonitorChannels is a parsable slice of UsageMonitorChannel.
type UsageMonitorChannels []*UsageMonitorChannel
