// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/ldm2060/axonhub/internal/ent/channel"
	"github.com/ldm2060/axonhub/internal/ent/channelusagemonitorbinding"
	"github.com/ldm2060/axonhub/internal/ent/predicate"
	"github.com/ldm2060/axonhub/internal/ent/usagemonitorchannel"
	"github.com/ldm2060/axonhub/internal/ent/user"
)

// UsageMonitorChannelUpdate is the builder for updating UsageMonitorChannel entities.
type UsageMonitorChannelUpdate struct {
	config
	hooks     []Hook
	mutation  *UsageMonitorChannelMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UsageMonitorChannelUpdate builder.
func (_u *UsageMonitorChannelUpdate) Where(ps ...predicate.UsageMonitorChannel) *UsageMonitorChannelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UsageMonitorChannelUpdate) SetUpdatedAt(v time.Time) *UsageMonitorChannelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UsageMonitorChannelUpdate) SetDeletedAt(v int) *UsageMonitorChannelUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdate) SetNillableDeletedAt(v *int) *UsageMonitorChannelUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *UsageMonitorChannelUpdate) AddDeletedAt(v int) *UsageMonitorChannelUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *UsageMonitorChannelUpdate) SetName(v string) *UsageMonitorChannelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdate) SetNillableName(v *string) *UsageMonitorChannelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *UsageMonitorChannelUpdate) SetSource(v usagemonitorchannel.Source) *UsageMonitorChannelUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdate) SetNillableSource(v *usagemonitorchannel.Source) *UsageMonitorChannelUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetProviderType sets the "provider_type" field.
func (_u *UsageMonitorChannelUpdate) SetProviderType(v usagemonitorchannel.ProviderType) *UsageMonitorChannelUpdate {
	_u.mutation.SetProviderType(v)
	return _u
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdate) SetNillableProviderType(v *usagemonitorchannel.ProviderType) *UsageMonitorChannelUpdate {
	if v != nil {
		_u.SetProviderType(*v)
	}
	return _u
}

// ClearProviderType clears the value of the "provider_type" field.
func (_u *UsageMonitorChannelUpdate) ClearProviderType() *UsageMonitorChannelUpdate {
	_u.mutation.ClearProviderType()
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *UsageMonitorChannelUpdate) SetChannelID(v int) *UsageMonitorChannelUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdate) SetNillableChannelID(v *int) *UsageMonitorChannelUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// ClearChannelID clears the value of the "channel_id" field.
func (_u *UsageMonitorChannelUpdate) ClearChannelID() *UsageMonitorChannelUpdate {
	_u.mutation.ClearChannelID()
	return _u
}

// SetAPIURL sets the "api_url" field.
func (_u *UsageMonitorChannelUpdate) SetAPIURL(v string) *UsageMonitorChannelUpdate {
	_u.mutation.SetAPIURL(v)
	return _u
}

// SetNillableAPIURL sets the "api_url" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdate) SetNillableAPIURL(v *string) *UsageMonitorChannelUpdate {
	if v != nil {
		_u.SetAPIURL(*v)
	}
	return _u
}

// SetAPIMethod sets the "api_method" field.
func (_u *UsageMonitorChannelUpdate) SetAPIMethod(v usagemonitorchannel.APIMethod) *UsageMonitorChannelUpdate {
	_u.mutation.SetAPIMethod(v)
	return _u
}

// SetNillableAPIMethod sets the "api_method" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdate) SetNillableAPIMethod(v *usagemonitorchannel.APIMethod) *UsageMonitorChannelUpdate {
	if v != nil {
		_u.SetAPIMethod(*v)
	}
	return _u
}

// SetAPIHeaders sets the "api_headers" field.
func (_u *UsageMonitorChannelUpdate) SetAPIHeaders(v map[string]interface{}) *UsageMonitorChannelUpdate {
	_u.mutation.SetAPIHeaders(v)
	return _u
}

// SetAPIBody sets the "api_body" field.
func (_u *UsageMonitorChannelUpdate) SetAPIBody(v string) *UsageMonitorChannelUpdate {
	_u.mutation.SetAPIBody(v)
	return _u
}

// SetNillableAPIBody sets the "api_body" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdate) SetNillableAPIBody(v *string) *UsageMonitorChannelUpdate {
	if v != nil {
		_u.SetAPIBody(*v)
	}
	return _u
}

// ClearAPIBody clears the value of the "api_body" field.
func (_u *UsageMonitorChannelUpdate) ClearAPIBody() *UsageMonitorChannelUpdate {
	_u.mutation.ClearAPIBody()
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *UsageMonitorChannelUpdate) SetAPIKey(v string) *UsageMonitorChannelUpdate {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdate) SetNillableAPIKey(v *string) *UsageMonitorChannelUpdate {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// ClearAPIKey clears the value of the "api_key" field.
func (_u *UsageMonitorChannelUpdate) ClearAPIKey() *UsageMonitorChannelUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// SetPollInterval sets the "poll_interval" field.
func (_u *UsageMonitorChannelUpdate) SetPollInterval(v int) *UsageMonitorChannelUpdate {
	_u.mutation.ResetPollInterval()
	_u.mutation.SetPollInterval(v)
	return _u
}

// SetNillablePollInterval sets the "poll_interval" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdate) SetNillablePollInterval(v *int) *UsageMonitorChannelUpdate {
	if v != nil {
		_u.SetPollInterval(*v)
	}
	return _u
}

// AddPollInterval adds value to the "poll_interval" field.
func (_u *UsageMonitorChannelUpdate) AddPollInterval(v int) *UsageMonitorChannelUpdate {
	_u.mutation.AddPollInterval(v)
	return _u
}

// SetFields sets the "fields" field.
func (_u *UsageMonitorChannelUpdate) SetFields(v []map[string]interface{}) *UsageMonitorChannelUpdate {
	_u.mutation.SetFields(v)
	return _u
}

// AppendFields appends value to the "fields" field.
func (_u *UsageMonitorChannelUpdate) AppendFields(v []map[string]interface{}) *UsageMonitorChannelUpdate {
	_u.mutation.AppendFields(v)
	return _u
}

// SetVariables sets the "variables" field.
func (_u *UsageMonitorChannelUpdate) SetVariables(v []map[string]interface{}) *UsageMonitorChannelUpdate {
	_u.mutation.SetVariables(v)
	return _u
}

// AppendVariables appends value to the "variables" field.
func (_u *UsageMonitorChannelUpdate) AppendVariables(v []map[string]interface{}) *UsageMonitorChannelUpdate {
	_u.mutation.AppendVariables(v)
	return _u
}

// ClearVariables clears the value of the "variables" field.
func (_u *UsageMonitorChannelUpdate) ClearVariables() *UsageMonitorChannelUpdate {
	_u.mutation.ClearVariables()
	return _u
}

// SetDisplayFields sets the "display_fields" field.
func (_u *UsageMonitorChannelUpdate) SetDisplayFields(v []map[string]interface{}) *UsageMonitorChannelUpdate {
	_u.mutation.SetDisplayFields(v)
	return _u
}

// AppendDisplayFields appends value to the "display_fields" field.
func (_u *UsageMonitorChannelUpdate) AppendDisplayFields(v []map[string]interface{}) *UsageMonitorChannelUpdate {
	_u.mutation.AppendDisplayFields(v)
	return _u
}

// ClearDisplayFields clears the value of the "display_fields" field.
func (_u *UsageMonitorChannelUpdate) ClearDisplayFields() *UsageMonitorChannelUpdate {
	_u.mutation.ClearDisplayFields()
	return _u
}

// SetLastPollAt sets the "last_poll_at" field.
func (_u *UsageMonitorChannelUpdate) SetLastPollAt(v time.Time) *UsageMonitorChannelUpdate {
	_u.mutation.SetLastPollAt(v)
	return _u
}

// SetNillableLastPollAt sets the "last_poll_at" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdate) SetNillableLastPollAt(v *time.Time) *UsageMonitorChannelUpdate {
	if v != nil {
		_u.SetLastPollAt(*v)
	}
	return _u
}

// ClearLastPollAt clears the value of the "last_poll_at" field.
func (_u *UsageMonitorChannelUpdate) ClearLastPollAt() *UsageMonitorChannelUpdate {
	_u.mutation.ClearLastPollAt()
	return _u
}

// SetLastPollData sets the "last_poll_data" field.
func (_u *UsageMonitorChannelUpdate) SetLastPollData(v map[string]interface{}) *UsageMonitorChannelUpdate {
	_u.mutation.SetLastPollData(v)
	return _u
}

// ClearLastPollData clears the value of the "last_poll_data" field.
func (_u *UsageMonitorChannelUpdate) ClearLastPollData() *UsageMonitorChannelUpdate {
	_u.mutation.ClearLastPollData()
	return _u
}

// SetLastPollError sets the "last_poll_error" field.
func (_u *UsageMonitorChannelUpdate) SetLastPollError(v string) *UsageMonitorChannelUpdate {
	_u.mutation.SetLastPollError(v)
	return _u
}

// SetNillableLastPollError sets the "last_poll_error" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdate) SetNillableLastPollError(v *string) *UsageMonitorChannelUpdate {
	if v != nil {
		_u.SetLastPollError(*v)
	}
	return _u
}

// ClearLastPollError clears the value of the "last_poll_error" field.
func (_u *UsageMonitorChannelUpdate) ClearLastPollError() *UsageMonitorChannelUpdate {
	_u.mutation.ClearLastPollError()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UsageMonitorChannelUpdate) SetStatus(v usagemonitorchannel.Status) *UsageMonitorChannelUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdate) SetNillableStatus(v *usagemonitorchannel.Status) *UsageMonitorChannelUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetQuotaStatus sets the "quota_status" field.
func (_u *UsageMonitorChannelUpdate) SetQuotaStatus(v usagemonitorchannel.QuotaStatus) *UsageMonitorChannelUpdate {
	_u.mutation.SetQuotaStatus(v)
	return _u
}

// SetNillableQuotaStatus sets the "quota_status" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdate) SetNillableQuotaStatus(v *usagemonitorchannel.QuotaStatus) *UsageMonitorChannelUpdate {
	if v != nil {
		_u.SetQuotaStatus(*v)
	}
	return _u
}

// ClearQuotaStatus clears the value of the "quota_status" field.
func (_u *UsageMonitorChannelUpdate) ClearQuotaStatus() *UsageMonitorChannelUpdate {
	_u.mutation.ClearQuotaStatus()
	return _u
}

// SetQuotaReady sets the "quota_ready" field.
func (_u *UsageMonitorChannelUpdate) SetQuotaReady(v bool) *UsageMonitorChannelUpdate {
	_u.mutation.SetQuotaReady(v)
	return _u
}

// SetNillableQuotaReady sets the "quota_ready" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdate) SetNillableQuotaReady(v *bool) *UsageMonitorChannelUpdate {
	if v != nil {
		_u.SetQuotaReady(*v)
	}
	return _u
}

// ClearQuotaReady clears the value of the "quota_ready" field.
func (_u *UsageMonitorChannelUpdate) ClearQuotaReady() *UsageMonitorChannelUpdate {
	_u.mutation.ClearQuotaReady()
	return _u
}

// SetQuotaLimits sets the "quota_limits" field.
func (_u *UsageMonitorChannelUpdate) SetQuotaLimits(v []map[string]interface{}) *UsageMonitorChannelUpdate {
	_u.mutation.SetQuotaLimits(v)
	return _u
}

// AppendQuotaLimits appends value to the "quota_limits" field.
func (_u *UsageMonitorChannelUpdate) AppendQuotaLimits(v []map[string]interface{}) *UsageMonitorChannelUpdate {
	_u.mutation.AppendQuotaLimits(v)
	return _u
}

// ClearQuotaLimits clears the value of the "quota_limits" field.
func (_u *UsageMonitorChannelUpdate) ClearQuotaLimits() *UsageMonitorChannelUpdate {
	_u.mutation.ClearQuotaLimits()
	return _u
}

// SetNextResetAt sets the "next_reset_at" field.
func (_u *UsageMonitorChannelUpdate) SetNextResetAt(v time.Time) *UsageMonitorChannelUpdate {
	_u.mutation.SetNextResetAt(v)
	return _u
}

// SetNillableNextResetAt sets the "next_reset_at" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdate) SetNillableNextResetAt(v *time.Time) *UsageMonitorChannelUpdate {
	if v != nil {
		_u.SetNextResetAt(*v)
	}
	return _u
}

// ClearNextResetAt clears the value of the "next_reset_at" field.
func (_u *UsageMonitorChannelUpdate) ClearNextResetAt() *UsageMonitorChannelUpdate {
	_u.mutation.ClearNextResetAt()
	return _u
}

// SetAutoDisableEnabled sets the "auto_disable_enabled" field.
func (_u *UsageMonitorChannelUpdate) SetAutoDisableEnabled(v bool) *UsageMonitorChannelUpdate {
	_u.mutation.SetAutoDisableEnabled(v)
	return _u
}

// SetNillableAutoDisableEnabled sets the "auto_disable_enabled" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdate) SetNillableAutoDisableEnabled(v *bool) *UsageMonitorChannelUpdate {
	if v != nil {
		_u.SetAutoDisableEnabled(*v)
	}
	return _u
}

// SetAutoDisableThreshold sets the "auto_disable_threshold" field.
func (_u *UsageMonitorChannelUpdate) SetAutoDisableThreshold(v float64) *UsageMonitorChannelUpdate {
	_u.mutation.ResetAutoDisableThreshold()
	_u.mutation.SetAutoDisableThreshold(v)
	return _u
}

// SetNillableAutoDisableThreshold sets the "auto_disable_threshold" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdate) SetNillableAutoDisableThreshold(v *float64) *UsageMonitorChannelUpdate {
	if v != nil {
		_u.SetAutoDisableThreshold(*v)
	}
	return _u
}

// AddAutoDisableThreshold adds value to the "auto_disable_threshold" field.
func (_u *UsageMonitorChannelUpdate) AddAutoDisableThreshold(v float64) *UsageMonitorChannelUpdate {
	_u.mutation.AddAutoDisableThreshold(v)
	return _u
}

// ClearAutoDisableThreshold clears the value of the "auto_disable_threshold" field.
func (_u *UsageMonitorChannelUpdate) ClearAutoDisableThreshold() *UsageMonitorChannelUpdate {
	_u.mutation.ClearAutoDisableThreshold()
	return _u
}

// SetAutoEnableThreshold sets the "auto_enable_threshold" field.
func (_u *UsageMonitorChannelUpdate) SetAutoEnableThreshold(v float64) *UsageMonitorChannelUpdate {
	_u.mutation.ResetAutoEnableThreshold()
	_u.mutation.SetAutoEnableThreshold(v)
	return _u
}

// SetNillableAutoEnableThreshold sets the "auto_enable_threshold" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdate) SetNillableAutoEnableThreshold(v *float64) *UsageMonitorChannelUpdate {
	if v != nil {
		_u.SetAutoEnableThreshold(*v)
	}
	return _u
}

// AddAutoEnableThreshold adds value to the "auto_enable_threshold" field.
func (_u *UsageMonitorChannelUpdate) AddAutoEnableThreshold(v float64) *UsageMonitorChannelUpdate {
	_u.mutation.AddAutoEnableThreshold(v)
	return _u
}

// ClearAutoEnableThreshold clears the value of the "auto_enable_threshold" field.
func (_u *UsageMonitorChannelUpdate) ClearAutoEnableThreshold() *UsageMonitorChannelUpdate {
	_u.mutation.ClearAutoEnableThreshold()
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *UsageMonitorChannelUpdate) SetChannel(v *Channel) *UsageMonitorChannelUpdate {
	return _u.SetChannelID(v.ID)
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *UsageMonitorChannelUpdate) SetOwnerID(id int) *UsageMonitorChannelUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *UsageMonitorChannelUpdate) SetOwner(v *User) *UsageMonitorChannelUpdate {
	return _u.SetOwnerID(v.ID)
}

// AddChannelBindingIDs adds the "channel_bindings" edge to the ChannelUsageMonitorBinding entity by IDs.
func (_u *UsageMonitorChannelUpdate) AddChannelBindingIDs(ids ...int) *UsageMonitorChannelUpdate {
	_u.mutation.AddChannelBindingIDs(ids...)
	return _u
}

// AddChannelBindings adds the "channel_bindings" edges to the ChannelUsageMonitorBinding entity.
func (_u *UsageMonitorChannelUpdate) AddChannelBindings(v ...*ChannelUsageMonitorBinding) *UsageMonitorChannelUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChannelBindingIDs(ids...)
}

// Mutation returns the UsageMonitorChannelMutation object of the builder.
func (_u *UsageMonitorChannelUpdate) Mutation() *UsageMonitorChannelMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *UsageMonitorChannelUpdate) ClearChannel() *UsageMonitorChannelUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *UsageMonitorChannelUpdate) ClearOwner() *UsageMonitorChannelUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearChannelBindings clears all "channel_bindings" edges to the ChannelUsageMonitorBinding entity.
func (_u *UsageMonitorChannelUpdate) ClearChannelBindings() *UsageMonitorChannelUpdate {
	_u.mutation.ClearChannelBindings()
	return _u
}

// RemoveChannelBindingIDs removes the "channel_bindings" edge to ChannelUsageMonitorBinding entities by IDs.
func (_u *UsageMonitorChannelUpdate) RemoveChannelBindingIDs(ids ...int) *UsageMonitorChannelUpdate {
	_u.mutation.RemoveChannelBindingIDs(ids...)
	return _u
}

// RemoveChannelBindings removes "channel_bindings" edges to ChannelUsageMonitorBinding entities.
func (_u *UsageMonitorChannelUpdate) RemoveChannelBindings(v ...*ChannelUsageMonitorBinding) *UsageMonitorChannelUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChannelBindingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UsageMonitorChannelUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageMonitorChannelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UsageMonitorChannelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageMonitorChannelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UsageMonitorChannelUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if usagemonitorchannel.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usagemonitorchannel.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usagemonitorchannel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageMonitorChannelUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := usagemonitorchannel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UsageMonitorChannel.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := usagemonitorchannel.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "UsageMonitorChannel.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderType(); ok {
		if err := usagemonitorchannel.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "UsageMonitorChannel.provider_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIURL(); ok {
		if err := usagemonitorchannel.APIURLValidator(v); err != nil {
			return &ValidationError{Name: "api_url", err: fmt.Errorf(`ent: validator failed for field "UsageMonitorChannel.api_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIMethod(); ok {
		if err := usagemonitorchannel.APIMethodValidator(v); err != nil {
			return &ValidationError{Name: "api_method", err: fmt.Errorf(`ent: validator failed for field "UsageMonitorChannel.api_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := usagemonitorchannel.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UsageMonitorChannel.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QuotaStatus(); ok {
		if err := usagemonitorchannel.QuotaStatusValidator(v); err != nil {
			return &ValidationError{Name: "quota_status", err: fmt.Errorf(`ent: validator failed for field "UsageMonitorChannel.quota_status": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UsageMonitorChannel.owner"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UsageMonitorChannelUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UsageMonitorChannelUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UsageMonitorChannelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagemonitorchannel.Table, usagemonitorchannel.Columns, sqlgraph.NewFieldSpec(usagemonitorchannel.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usagemonitorchannel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(usagemonitorchannel.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(usagemonitorchannel.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(usagemonitorchannel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(usagemonitorchannel.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ProviderType(); ok {
		_spec.SetField(usagemonitorchannel.FieldProviderType, field.TypeEnum, value)
	}
	if _u.mutation.ProviderTypeCleared() {
		_spec.ClearField(usagemonitorchannel.FieldProviderType, field.TypeEnum)
	}
	if value, ok := _u.mutation.APIURL(); ok {
		_spec.SetField(usagemonitorchannel.FieldAPIURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIMethod(); ok {
		_spec.SetField(usagemonitorchannel.FieldAPIMethod, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.APIHeaders(); ok {
		_spec.SetField(usagemonitorchannel.FieldAPIHeaders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.APIBody(); ok {
		_spec.SetField(usagemonitorchannel.FieldAPIBody, field.TypeString, value)
	}
	if _u.mutation.APIBodyCleared() {
		_spec.ClearField(usagemonitorchannel.FieldAPIBody, field.TypeString)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(usagemonitorchannel.FieldAPIKey, field.TypeString, value)
	}
	if _u.mutation.APIKeyCleared() {
		_spec.ClearField(usagemonitorchannel.FieldAPIKey, field.TypeString)
	}
	if value, ok := _u.mutation.PollInterval(); ok {
		_spec.SetField(usagemonitorchannel.FieldPollInterval, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPollInterval(); ok {
		_spec.AddField(usagemonitorchannel.FieldPollInterval, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GetFields(); ok {
		_spec.SetField(usagemonitorchannel.FieldFields, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFields(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, usagemonitorchannel.FieldFields, value)
		})
	}
	if value, ok := _u.mutation.Variables(); ok {
		_spec.SetField(usagemonitorchannel.FieldVariables, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedVariables(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, usagemonitorchannel.FieldVariables, value)
		})
	}
	if _u.mutation.VariablesCleared() {
		_spec.ClearField(usagemonitorchannel.FieldVariables, field.TypeJSON)
	}
	if value, ok := _u.mutation.DisplayFields(); ok {
		_spec.SetField(usagemonitorchannel.FieldDisplayFields, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDisplayFields(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, usagemonitorchannel.FieldDisplayFields, value)
		})
	}
	if _u.mutation.DisplayFieldsCleared() {
		_spec.ClearField(usagemonitorchannel.FieldDisplayFields, field.TypeJSON)
	}
	if value, ok := _u.mutation.LastPollAt(); ok {
		_spec.SetField(usagemonitorchannel.FieldLastPollAt, field.TypeTime, value)
	}
	if _u.mutation.LastPollAtCleared() {
		_spec.ClearField(usagemonitorchannel.FieldLastPollAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastPollData(); ok {
		_spec.SetField(usagemonitorchannel.FieldLastPollData, field.TypeJSON, value)
	}
	if _u.mutation.LastPollDataCleared() {
		_spec.ClearField(usagemonitorchannel.FieldLastPollData, field.TypeJSON)
	}
	if value, ok := _u.mutation.LastPollError(); ok {
		_spec.SetField(usagemonitorchannel.FieldLastPollError, field.TypeString, value)
	}
	if _u.mutation.LastPollErrorCleared() {
		_spec.ClearField(usagemonitorchannel.FieldLastPollError, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usagemonitorchannel.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.QuotaStatus(); ok {
		_spec.SetField(usagemonitorchannel.FieldQuotaStatus, field.TypeEnum, value)
	}
	if _u.mutation.QuotaStatusCleared() {
		_spec.ClearField(usagemonitorchannel.FieldQuotaStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.QuotaReady(); ok {
		_spec.SetField(usagemonitorchannel.FieldQuotaReady, field.TypeBool, value)
	}
	if _u.mutation.QuotaReadyCleared() {
		_spec.ClearField(usagemonitorchannel.FieldQuotaReady, field.TypeBool)
	}
	if value, ok := _u.mutation.QuotaLimits(); ok {
		_spec.SetField(usagemonitorchannel.FieldQuotaLimits, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedQuotaLimits(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, usagemonitorchannel.FieldQuotaLimits, value)
		})
	}
	if _u.mutation.QuotaLimitsCleared() {
		_spec.ClearField(usagemonitorchannel.FieldQuotaLimits, field.TypeJSON)
	}
	if value, ok := _u.mutation.NextResetAt(); ok {
		_spec.SetField(usagemonitorchannel.FieldNextResetAt, field.TypeTime, value)
	}
	if _u.mutation.NextResetAtCleared() {
		_spec.ClearField(usagemonitorchannel.FieldNextResetAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AutoDisableEnabled(); ok {
		_spec.SetField(usagemonitorchannel.FieldAutoDisableEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AutoDisableThreshold(); ok {
		_spec.SetField(usagemonitorchannel.FieldAutoDisableThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAutoDisableThreshold(); ok {
		_spec.AddField(usagemonitorchannel.FieldAutoDisableThreshold, field.TypeFloat64, value)
	}
	if _u.mutation.AutoDisableThresholdCleared() {
		_spec.ClearField(usagemonitorchannel.FieldAutoDisableThreshold, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AutoEnableThreshold(); ok {
		_spec.SetField(usagemonitorchannel.FieldAutoEnableThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAutoEnableThreshold(); ok {
		_spec.AddField(usagemonitorchannel.FieldAutoEnableThreshold, field.TypeFloat64, value)
	}
	if _u.mutation.AutoEnableThresholdCleared() {
		_spec.ClearField(usagemonitorchannel.FieldAutoEnableThreshold, field.TypeFloat64)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagemonitorchannel.ChannelTable,
			Columns: []string{usagemonitorchannel.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagemonitorchannel.ChannelTable,
			Columns: []string{usagemonitorchannel.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagemonitorchannel.OwnerTable,
			Columns: []string{usagemonitorchannel.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagemonitorchannel.OwnerTable,
			Columns: []string{usagemonitorchannel.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelBindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usagemonitorchannel.ChannelBindingsTable,
			Columns: []string{usagemonitorchannel.ChannelBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelusagemonitorbinding.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChannelBindingsIDs(); len(nodes) > 0 && !_u.mutation.ChannelBindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usagemonitorchannel.ChannelBindingsTable,
			Columns: []string{usagemonitorchannel.ChannelBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelusagemonitorbinding.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelBindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usagemonitorchannel.ChannelBindingsTable,
			Columns: []string{usagemonitorchannel.ChannelBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelusagemonitorbinding.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagemonitorchannel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UsageMonitorChannelUpdateOne is the builder for updating a single UsageMonitorChannel entity.
type UsageMonitorChannelUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UsageMonitorChannelMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UsageMonitorChannelUpdateOne) SetUpdatedAt(v time.Time) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UsageMonitorChannelUpdateOne) SetDeletedAt(v int) *UsageMonitorChannelUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdateOne) SetNillableDeletedAt(v *int) *UsageMonitorChannelUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *UsageMonitorChannelUpdateOne) AddDeletedAt(v int) *UsageMonitorChannelUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *UsageMonitorChannelUpdateOne) SetName(v string) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdateOne) SetNillableName(v *string) *UsageMonitorChannelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *UsageMonitorChannelUpdateOne) SetSource(v usagemonitorchannel.Source) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdateOne) SetNillableSource(v *usagemonitorchannel.Source) *UsageMonitorChannelUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetProviderType sets the "provider_type" field.
func (_u *UsageMonitorChannelUpdateOne) SetProviderType(v usagemonitorchannel.ProviderType) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetProviderType(v)
	return _u
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdateOne) SetNillableProviderType(v *usagemonitorchannel.ProviderType) *UsageMonitorChannelUpdateOne {
	if v != nil {
		_u.SetProviderType(*v)
	}
	return _u
}

// ClearProviderType clears the value of the "provider_type" field.
func (_u *UsageMonitorChannelUpdateOne) ClearProviderType() *UsageMonitorChannelUpdateOne {
	_u.mutation.ClearProviderType()
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *UsageMonitorChannelUpdateOne) SetChannelID(v int) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdateOne) SetNillableChannelID(v *int) *UsageMonitorChannelUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// ClearChannelID clears the value of the "channel_id" field.
func (_u *UsageMonitorChannelUpdateOne) ClearChannelID() *UsageMonitorChannelUpdateOne {
	_u.mutation.ClearChannelID()
	return _u
}

// SetAPIURL sets the "api_url" field.
func (_u *UsageMonitorChannelUpdateOne) SetAPIURL(v string) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetAPIURL(v)
	return _u
}

// SetNillableAPIURL sets the "api_url" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdateOne) SetNillableAPIURL(v *string) *UsageMonitorChannelUpdateOne {
	if v != nil {
		_u.SetAPIURL(*v)
	}
	return _u
}

// SetAPIMethod sets the "api_method" field.
func (_u *UsageMonitorChannelUpdateOne) SetAPIMethod(v usagemonitorchannel.APIMethod) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetAPIMethod(v)
	return _u
}

// SetNillableAPIMethod sets the "api_method" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdateOne) SetNillableAPIMethod(v *usagemonitorchannel.APIMethod) *UsageMonitorChannelUpdateOne {
	if v != nil {
		_u.SetAPIMethod(*v)
	}
	return _u
}

// SetAPIHeaders sets the "api_headers" field.
func (_u *UsageMonitorChannelUpdateOne) SetAPIHeaders(v map[string]interface{}) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetAPIHeaders(v)
	return _u
}

// SetAPIBody sets the "api_body" field.
func (_u *UsageMonitorChannelUpdateOne) SetAPIBody(v string) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetAPIBody(v)
	return _u
}

// SetNillableAPIBody sets the "api_body" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdateOne) SetNillableAPIBody(v *string) *UsageMonitorChannelUpdateOne {
	if v != nil {
		_u.SetAPIBody(*v)
	}
	return _u
}

// ClearAPIBody clears the value of the "api_body" field.
func (_u *UsageMonitorChannelUpdateOne) ClearAPIBody() *UsageMonitorChannelUpdateOne {
	_u.mutation.ClearAPIBody()
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *UsageMonitorChannelUpdateOne) SetAPIKey(v string) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdateOne) SetNillableAPIKey(v *string) *UsageMonitorChannelUpdateOne {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// ClearAPIKey clears the value of the "api_key" field.
func (_u *UsageMonitorChannelUpdateOne) ClearAPIKey() *UsageMonitorChannelUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// SetPollInterval sets the "poll_interval" field.
func (_u *UsageMonitorChannelUpdateOne) SetPollInterval(v int) *UsageMonitorChannelUpdateOne {
	_u.mutation.ResetPollInterval()
	_u.mutation.SetPollInterval(v)
	return _u
}

// SetNillablePollInterval sets the "poll_interval" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdateOne) SetNillablePollInterval(v *int) *UsageMonitorChannelUpdateOne {
	if v != nil {
		_u.SetPollInterval(*v)
	}
	return _u
}

// AddPollInterval adds value to the "poll_interval" field.
func (_u *UsageMonitorChannelUpdateOne) AddPollInterval(v int) *UsageMonitorChannelUpdateOne {
	_u.mutation.AddPollInterval(v)
	return _u
}

// SetFields sets the "fields" field.
func (_u *UsageMonitorChannelUpdateOne) SetFields(v []map[string]interface{}) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetFields(v)
	return _u
}

// AppendFields appends value to the "fields" field.
func (_u *UsageMonitorChannelUpdateOne) AppendFields(v []map[string]interface{}) *UsageMonitorChannelUpdateOne {
	_u.mutation.AppendFields(v)
	return _u
}

// SetVariables sets the "variables" field.
func (_u *UsageMonitorChannelUpdateOne) SetVariables(v []map[string]interface{}) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetVariables(v)
	return _u
}

// AppendVariables appends value to the "variables" field.
func (_u *UsageMonitorChannelUpdateOne) AppendVariables(v []map[string]interface{}) *UsageMonitorChannelUpdateOne {
	_u.mutation.AppendVariables(v)
	return _u
}

// ClearVariables clears the value of the "variables" field.
func (_u *UsageMonitorChannelUpdateOne) ClearVariables() *UsageMonitorChannelUpdateOne {
	_u.mutation.ClearVariables()
	return _u
}

// SetDisplayFields sets the "display_fields" field.
func (_u *UsageMonitorChannelUpdateOne) SetDisplayFields(v []map[string]interface{}) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetDisplayFields(v)
	return _u
}

// AppendDisplayFields appends value to the "display_fields" field.
func (_u *UsageMonitorChannelUpdateOne) AppendDisplayFields(v []map[string]interface{}) *UsageMonitorChannelUpdateOne {
	_u.mutation.AppendDisplayFields(v)
	return _u
}

// ClearDisplayFields clears the value of the "display_fields" field.
func (_u *UsageMonitorChannelUpdateOne) ClearDisplayFields() *UsageMonitorChannelUpdateOne {
	_u.mutation.ClearDisplayFields()
	return _u
}

// SetLastPollAt sets the "last_poll_at" field.
func (_u *UsageMonitorChannelUpdateOne) SetLastPollAt(v time.Time) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetLastPollAt(v)
	return _u
}

// SetNillableLastPollAt sets the "last_poll_at" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdateOne) SetNillableLastPollAt(v *time.Time) *UsageMonitorChannelUpdateOne {
	if v != nil {
		_u.SetLastPollAt(*v)
	}
	return _u
}

// ClearLastPollAt clears the value of the "last_poll_at" field.
func (_u *UsageMonitorChannelUpdateOne) ClearLastPollAt() *UsageMonitorChannelUpdateOne {
	_u.mutation.ClearLastPollAt()
	return _u
}

// SetLastPollData sets the "last_poll_data" field.
func (_u *UsageMonitorChannelUpdateOne) SetLastPollData(v map[string]interface{}) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetLastPollData(v)
	return _u
}

// ClearLastPollData clears the value of the "last_poll_data" field.
func (_u *UsageMonitorChannelUpdateOne) ClearLastPollData() *UsageMonitorChannelUpdateOne {
	_u.mutation.ClearLastPollData()
	return _u
}

// SetLastPollError sets the "last_poll_error" field.
func (_u *UsageMonitorChannelUpdateOne) SetLastPollError(v string) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetLastPollError(v)
	return _u
}

// SetNillableLastPollError sets the "last_poll_error" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdateOne) SetNillableLastPollError(v *string) *UsageMonitorChannelUpdateOne {
	if v != nil {
		_u.SetLastPollError(*v)
	}
	return _u
}

// ClearLastPollError clears the value of the "last_poll_error" field.
func (_u *UsageMonitorChannelUpdateOne) ClearLastPollError() *UsageMonitorChannelUpdateOne {
	_u.mutation.ClearLastPollError()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UsageMonitorChannelUpdateOne) SetStatus(v usagemonitorchannel.Status) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdateOne) SetNillableStatus(v *usagemonitorchannel.Status) *UsageMonitorChannelUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetQuotaStatus sets the "quota_status" field.
func (_u *UsageMonitorChannelUpdateOne) SetQuotaStatus(v usagemonitorchannel.QuotaStatus) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetQuotaStatus(v)
	return _u
}

// SetNillableQuotaStatus sets the "quota_status" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdateOne) SetNillableQuotaStatus(v *usagemonitorchannel.QuotaStatus) *UsageMonitorChannelUpdateOne {
	if v != nil {
		_u.SetQuotaStatus(*v)
	}
	return _u
}

// ClearQuotaStatus clears the value of the "quota_status" field.
func (_u *UsageMonitorChannelUpdateOne) ClearQuotaStatus() *UsageMonitorChannelUpdateOne {
	_u.mutation.ClearQuotaStatus()
	return _u
}

// SetQuotaReady sets the "quota_ready" field.
func (_u *UsageMonitorChannelUpdateOne) SetQuotaReady(v bool) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetQuotaReady(v)
	return _u
}

// SetNillableQuotaReady sets the "quota_ready" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdateOne) SetNillableQuotaReady(v *bool) *UsageMonitorChannelUpdateOne {
	if v != nil {
		_u.SetQuotaReady(*v)
	}
	return _u
}

// ClearQuotaReady clears the value of the "quota_ready" field.
func (_u *UsageMonitorChannelUpdateOne) ClearQuotaReady() *UsageMonitorChannelUpdateOne {
	_u.mutation.ClearQuotaReady()
	return _u
}

// SetQuotaLimits sets the "quota_limits" field.
func (_u *UsageMonitorChannelUpdateOne) SetQuotaLimits(v []map[string]interface{}) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetQuotaLimits(v)
	return _u
}

// AppendQuotaLimits appends value to the "quota_limits" field.
func (_u *UsageMonitorChannelUpdateOne) AppendQuotaLimits(v []map[string]interface{}) *UsageMonitorChannelUpdateOne {
	_u.mutation.AppendQuotaLimits(v)
	return _u
}

// ClearQuotaLimits clears the value of the "quota_limits" field.
func (_u *UsageMonitorChannelUpdateOne) ClearQuotaLimits() *UsageMonitorChannelUpdateOne {
	_u.mutation.ClearQuotaLimits()
	return _u
}

// SetNextResetAt sets the "next_reset_at" field.
func (_u *UsageMonitorChannelUpdateOne) SetNextResetAt(v time.Time) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetNextResetAt(v)
	return _u
}

// SetNillableNextResetAt sets the "next_reset_at" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdateOne) SetNillableNextResetAt(v *time.Time) *UsageMonitorChannelUpdateOne {
	if v != nil {
		_u.SetNextResetAt(*v)
	}
	return _u
}

// ClearNextResetAt clears the value of the "next_reset_at" field.
func (_u *UsageMonitorChannelUpdateOne) ClearNextResetAt() *UsageMonitorChannelUpdateOne {
	_u.mutation.ClearNextResetAt()
	return _u
}

// SetAutoDisableEnabled sets the "auto_disable_enabled" field.
func (_u *UsageMonitorChannelUpdateOne) SetAutoDisableEnabled(v bool) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetAutoDisableEnabled(v)
	return _u
}

// SetNillableAutoDisableEnabled sets the "auto_disable_enabled" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdateOne) SetNillableAutoDisableEnabled(v *bool) *UsageMonitorChannelUpdateOne {
	if v != nil {
		_u.SetAutoDisableEnabled(*v)
	}
	return _u
}

// SetAutoDisableThreshold sets the "auto_disable_threshold" field.
func (_u *UsageMonitorChannelUpdateOne) SetAutoDisableThreshold(v float64) *UsageMonitorChannelUpdateOne {
	_u.mutation.ResetAutoDisableThreshold()
	_u.mutation.SetAutoDisableThreshold(v)
	return _u
}

// SetNillableAutoDisableThreshold sets the "auto_disable_threshold" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdateOne) SetNillableAutoDisableThreshold(v *float64) *UsageMonitorChannelUpdateOne {
	if v != nil {
		_u.SetAutoDisableThreshold(*v)
	}
	return _u
}

// AddAutoDisableThreshold adds value to the "auto_disable_threshold" field.
func (_u *UsageMonitorChannelUpdateOne) AddAutoDisableThreshold(v float64) *UsageMonitorChannelUpdateOne {
	_u.mutation.AddAutoDisableThreshold(v)
	return _u
}

// ClearAutoDisableThreshold clears the value of the "auto_disable_threshold" field.
func (_u *UsageMonitorChannelUpdateOne) ClearAutoDisableThreshold() *UsageMonitorChannelUpdateOne {
	_u.mutation.ClearAutoDisableThreshold()
	return _u
}

// SetAutoEnableThreshold sets the "auto_enable_threshold" field.
func (_u *UsageMonitorChannelUpdateOne) SetAutoEnableThreshold(v float64) *UsageMonitorChannelUpdateOne {
	_u.mutation.ResetAutoEnableThreshold()
	_u.mutation.SetAutoEnableThreshold(v)
	return _u
}

// SetNillableAutoEnableThreshold sets the "auto_enable_threshold" field if the given value is not nil.
func (_u *UsageMonitorChannelUpdateOne) SetNillableAutoEnableThreshold(v *float64) *UsageMonitorChannelUpdateOne {
	if v != nil {
		_u.SetAutoEnableThreshold(*v)
	}
	return _u
}

// AddAutoEnableThreshold adds value to the "auto_enable_threshold" field.
func (_u *UsageMonitorChannelUpdateOne) AddAutoEnableThreshold(v float64) *UsageMonitorChannelUpdateOne {
	_u.mutation.AddAutoEnableThreshold(v)
	return _u
}

// ClearAutoEnableThreshold clears the value of the "auto_enable_threshold" field.
func (_u *UsageMonitorChannelUpdateOne) ClearAutoEnableThreshold() *UsageMonitorChannelUpdateOne {
	_u.mutation.ClearAutoEnableThreshold()
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *UsageMonitorChannelUpdateOne) SetChannel(v *Channel) *UsageMonitorChannelUpdateOne {
	return _u.SetChannelID(v.ID)
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *UsageMonitorChannelUpdateOne) SetOwnerID(id int) *UsageMonitorChannelUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *UsageMonitorChannelUpdateOne) SetOwner(v *User) *UsageMonitorChannelUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// AddChannelBindingIDs adds the "channel_bindings" edge to the ChannelUsageMonitorBinding entity by IDs.
func (_u *UsageMonitorChannelUpdateOne) AddChannelBindingIDs(ids ...int) *UsageMonitorChannelUpdateOne {
	_u.mutation.AddChannelBindingIDs(ids...)
	return _u
}

// AddChannelBindings adds the "channel_bindings" edges to the ChannelUsageMonitorBinding entity.
func (_u *UsageMonitorChannelUpdateOne) AddChannelBindings(v ...*ChannelUsageMonitorBinding) *UsageMonitorChannelUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChannelBindingIDs(ids...)
}

// Mutation returns the UsageMonitorChannelMutation object of the builder.
func (_u *UsageMonitorChannelUpdateOne) Mutation() *UsageMonitorChannelMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *UsageMonitorChannelUpdateOne) ClearChannel() *UsageMonitorChannelUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *UsageMonitorChannelUpdateOne) ClearOwner() *UsageMonitorChannelUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearChannelBindings clears all "channel_bindings" edges to the ChannelUsageMonitorBinding entity.
func (_u *UsageMonitorChannelUpdateOne) ClearChannelBindings() *UsageMonitorChannelUpdateOne {
	_u.mutation.ClearChannelBindings()
	return _u
}

// RemoveChannelBindingIDs removes the "channel_bindings" edge to ChannelUsageMonitorBinding entities by IDs.
func (_u *UsageMonitorChannelUpdateOne) RemoveChannelBindingIDs(ids ...int) *UsageMonitorChannelUpdateOne {
	_u.mutation.RemoveChannelBindingIDs(ids...)
	return _u
}

// RemoveChannelBindings removes "channel_bindings" edges to ChannelUsageMonitorBinding entities.
func (_u *UsageMonitorChannelUpdateOne) RemoveChannelBindings(v ...*ChannelUsageMonitorBinding) *UsageMonitorChannelUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChannelBindingIDs(ids...)
}

// Where appends a list predicates to the UsageMonitorChannelUpdate builder.
func (_u *UsageMonitorChannelUpdateOne) Where(ps ...predicate.UsageMonitorChannel) *UsageMonitorChannelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UsageMonitorChannelUpdateOne) Select(field string, fields ...string) *UsageMonitorChannelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UsageMonitorChannel entity.
func (_u *UsageMonitorChannelUpdateOne) Save(ctx context.Context) (*UsageMonitorChannel, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageMonitorChannelUpdateOne) SaveX(ctx context.Context) *UsageMonitorChannel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UsageMonitorChannelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageMonitorChannelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UsageMonitorChannelUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if usagemonitorchannel.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usagemonitorchannel.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usagemonitorchannel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageMonitorChannelUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := usagemonitorchannel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UsageMonitorChannel.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := usagemonitorchannel.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "UsageMonitorChannel.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderType(); ok {
		if err := usagemonitorchannel.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "UsageMonitorChannel.provider_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIURL(); ok {
		if err := usagemonitorchannel.APIURLValidator(v); err != nil {
			return &ValidationError{Name: "api_url", err: fmt.Errorf(`ent: validator failed for field "UsageMonitorChannel.api_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIMethod(); ok {
		if err := usagemonitorchannel.APIMethodValidator(v); err != nil {
			return &ValidationError{Name: "api_method", err: fmt.Errorf(`ent: validator failed for field "UsageMonitorChannel.api_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := usagemonitorchannel.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UsageMonitorChannel.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QuotaStatus(); ok {
		if err := usagemonitorchannel.QuotaStatusValidator(v); err != nil {
			return &ValidationError{Name: "quota_status", err: fmt.Errorf(`ent: validator failed for field "UsageMonitorChannel.quota_status": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UsageMonitorChannel.owner"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UsageMonitorChannelUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UsageMonitorChannelUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UsageMonitorChannelUpdateOne) sqlSave(ctx context.Context) (_node *UsageMonitorChannel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagemonitorchannel.Table, usagemonitorchannel.Columns, sqlgraph.NewFieldSpec(usagemonitorchannel.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsageMonitorChannel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usagemonitorchannel.FieldID)
		for _, f := range fields {
			if !usagemonitorchannel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usagemonitorchannel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usagemonitorchannel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(usagemonitorchannel.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(usagemonitorchannel.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(usagemonitorchannel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(usagemonitorchannel.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ProviderType(); ok {
		_spec.SetField(usagemonitorchannel.FieldProviderType, field.TypeEnum, value)
	}
	if _u.mutation.ProviderTypeCleared() {
		_spec.ClearField(usagemonitorchannel.FieldProviderType, field.TypeEnum)
	}
	if value, ok := _u.mutation.APIURL(); ok {
		_spec.SetField(usagemonitorchannel.FieldAPIURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIMethod(); ok {
		_spec.SetField(usagemonitorchannel.FieldAPIMethod, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.APIHeaders(); ok {
		_spec.SetField(usagemonitorchannel.FieldAPIHeaders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.APIBody(); ok {
		_spec.SetField(usagemonitorchannel.FieldAPIBody, field.TypeString, value)
	}
	if _u.mutation.APIBodyCleared() {
		_spec.ClearField(usagemonitorchannel.FieldAPIBody, field.TypeString)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(usagemonitorchannel.FieldAPIKey, field.TypeString, value)
	}
	if _u.mutation.APIKeyCleared() {
		_spec.ClearField(usagemonitorchannel.FieldAPIKey, field.TypeString)
	}
	if value, ok := _u.mutation.PollInterval(); ok {
		_spec.SetField(usagemonitorchannel.FieldPollInterval, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPollInterval(); ok {
		_spec.AddField(usagemonitorchannel.FieldPollInterval, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GetFields(); ok {
		_spec.SetField(usagemonitorchannel.FieldFields, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFields(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, usagemonitorchannel.FieldFields, value)
		})
	}
	if value, ok := _u.mutation.Variables(); ok {
		_spec.SetField(usagemonitorchannel.FieldVariables, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedVariables(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, usagemonitorchannel.FieldVariables, value)
		})
	}
	if _u.mutation.VariablesCleared() {
		_spec.ClearField(usagemonitorchannel.FieldVariables, field.TypeJSON)
	}
	if value, ok := _u.mutation.DisplayFields(); ok {
		_spec.SetField(usagemonitorchannel.FieldDisplayFields, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDisplayFields(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, usagemonitorchannel.FieldDisplayFields, value)
		})
	}
	if _u.mutation.DisplayFieldsCleared() {
		_spec.ClearField(usagemonitorchannel.FieldDisplayFields, field.TypeJSON)
	}
	if value, ok := _u.mutation.LastPollAt(); ok {
		_spec.SetField(usagemonitorchannel.FieldLastPollAt, field.TypeTime, value)
	}
	if _u.mutation.LastPollAtCleared() {
		_spec.ClearField(usagemonitorchannel.FieldLastPollAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastPollData(); ok {
		_spec.SetField(usagemonitorchannel.FieldLastPollData, field.TypeJSON, value)
	}
	if _u.mutation.LastPollDataCleared() {
		_spec.ClearField(usagemonitorchannel.FieldLastPollData, field.TypeJSON)
	}
	if value, ok := _u.mutation.LastPollError(); ok {
		_spec.SetField(usagemonitorchannel.FieldLastPollError, field.TypeString, value)
	}
	if _u.mutation.LastPollErrorCleared() {
		_spec.ClearField(usagemonitorchannel.FieldLastPollError, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usagemonitorchannel.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.QuotaStatus(); ok {
		_spec.SetField(usagemonitorchannel.FieldQuotaStatus, field.TypeEnum, value)
	}
	if _u.mutation.QuotaStatusCleared() {
		_spec.ClearField(usagemonitorchannel.FieldQuotaStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.QuotaReady(); ok {
		_spec.SetField(usagemonitorchannel.FieldQuotaReady, field.TypeBool, value)
	}
	if _u.mutation.QuotaReadyCleared() {
		_spec.ClearField(usagemonitorchannel.FieldQuotaReady, field.TypeBool)
	}
	if value, ok := _u.mutation.QuotaLimits(); ok {
		_spec.SetField(usagemonitorchannel.FieldQuotaLimits, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedQuotaLimits(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, usagemonitorchannel.FieldQuotaLimits, value)
		})
	}
	if _u.mutation.QuotaLimitsCleared() {
		_spec.ClearField(usagemonitorchannel.FieldQuotaLimits, field.TypeJSON)
	}
	if value, ok := _u.mutation.NextResetAt(); ok {
		_spec.SetField(usagemonitorchannel.FieldNextResetAt, field.TypeTime, value)
	}
	if _u.mutation.NextResetAtCleared() {
		_spec.ClearField(usagemonitorchannel.FieldNextResetAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AutoDisableEnabled(); ok {
		_spec.SetField(usagemonitorchannel.FieldAutoDisableEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AutoDisableThreshold(); ok {
		_spec.SetField(usagemonitorchannel.FieldAutoDisableThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAutoDisableThreshold(); ok {
		_spec.AddField(usagemonitorchannel.FieldAutoDisableThreshold, field.TypeFloat64, value)
	}
	if _u.mutation.AutoDisableThresholdCleared() {
		_spec.ClearField(usagemonitorchannel.FieldAutoDisableThreshold, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AutoEnableThreshold(); ok {
		_spec.SetField(usagemonitorchannel.FieldAutoEnableThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAutoEnableThreshold(); ok {
		_spec.AddField(usagemonitorchannel.FieldAutoEnableThreshold, field.TypeFloat64, value)
	}
	if _u.mutation.AutoEnableThresholdCleared() {
		_spec.ClearField(usagemonitorchannel.FieldAutoEnableThreshold, field.TypeFloat64)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagemonitorchannel.ChannelTable,
			Columns: []string{usagemonitorchannel.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagemonitorchannel.ChannelTable,
			Columns: []string{usagemonitorchannel.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagemonitorchannel.OwnerTable,
			Columns: []string{usagemonitorchannel.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagemonitorchannel.OwnerTable,
			Columns: []string{usagemonitorchannel.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelBindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usagemonitorchannel.ChannelBindingsTable,
			Columns: []string{usagemonitorchannel.ChannelBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelusagemonitorbinding.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChannelBindingsIDs(); len(nodes) > 0 && !_u.mutation.ChannelBindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usagemonitorchannel.ChannelBindingsTable,
			Columns: []string{usagemonitorchannel.ChannelBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelusagemonitorbinding.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelBindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usagemonitorchannel.ChannelBindingsTable,
			Columns: []string{usagemonitorchannel.ChannelBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelusagemonitorbinding.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &UsageMonitorChannel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagemonitorchannel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
