// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ldm2060/axonhub/internal/ent/predicate"
	"github.com/ldm2060/axonhub/internal/ent/userusagestats"
)

// UserUsageStatsDelete is the builder for deleting a UserUsageStats entity.
type UserUsageStatsDelete struct {
	config
	hooks    []Hook
	mutation *UserUsageStatsMutation
}

// Where appends a list predicates to the UserUsageStatsDelete builder.
func (_d *UserUsageStatsDelete) Where(ps ...predicate.UserUsageStats) *UserUsageStatsDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserUsageStatsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserUsageStatsDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserUsageStatsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userusagestats.Table, sqlgraph.NewFieldSpec(userusagestats.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserUsageStatsDeleteOne is the builder for deleting a single UserUsageStats entity.
type UserUsageStatsDeleteOne struct {
	_d *UserUsageStatsDelete
}

// Where appends a list predicates to the UserUsageStatsDelete builder.
func (_d *UserUsageStatsDeleteOne) Where(ps ...predicate.UserUsageStats) *UserUsageStatsDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserUsageStatsDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userusagestats.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserUsageStatsDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
