package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/ldm2060/axonhub/internal/contexts"
	"github.com/ldm2060/axonhub/internal/ent"
	"github.com/ldm2060/axonhub/internal/objects"
	"github.com/ldm2060/axonhub/internal/server/biz"
)

// CreateOAuthClient is the resolver for the createOAuthClient field.
func (r *mutationResolver) CreateOAuthClient(ctx context.Context, input CreateOAuthClientInput) (*OAuthClientSecretPayload, error) {
	description := ""
	if input.Description != nil {
		description = *input.Description
	}

	client, secret, err := r.oauthProviderService.CreateClient(ctx, biz.CreateOAuthClientInput{
		Name:         input.Name,
		Description:  description,
		RedirectURIs: input.RedirectUris,
		ClientType:   input.ClientType,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create oauth client: %w", err)
	}

	return &OAuthClientSecretPayload{
		Client:       client,
		ClientSecret: secret,
	}, nil
}

// UpdateOAuthClient is the resolver for the updateOAuthClient field.
func (r *mutationResolver) UpdateOAuthClient(ctx context.Context, id objects.GUID, input UpdateOAuthClientInput) (*ent.OAuthClient, error) {
	client, err := r.oauthProviderService.UpdateClient(ctx, id.ID, biz.UpdateOAuthClientInput{
		Name:         input.Name,
		Description:  input.Description,
		RedirectURIs: input.RedirectUris,
		Status:       input.Status,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to update oauth client: %w", err)
	}

	return client, nil
}

// DeleteOAuthClient is the resolver for the deleteOAuthClient field.
func (r *mutationResolver) DeleteOAuthClient(ctx context.Context, id objects.GUID) (bool, error) {
	if err := r.oauthProviderService.DeleteClient(ctx, id.ID); err != nil {
		return false, fmt.Errorf("failed to delete oauth client: %w", err)
	}

	return true, nil
}

// RotateOAuthClientSecret is the resolver for the rotateOAuthClientSecret field.
func (r *mutationResolver) RotateOAuthClientSecret(ctx context.Context, id objects.GUID) (*OAuthClientSecretPayload, error) {
	client, secret, err := r.oauthProviderService.RotateClientSecret(ctx, id.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to rotate oauth client secret: %w", err)
	}

	return &OAuthClientSecretPayload{
		Client:       client,
		ClientSecret: secret,
	}, nil
}

// ApproveOAuthAuthorization is the resolver for the approveOAuthAuthorization field.
func (r *mutationResolver) ApproveOAuthAuthorization(ctx context.Context, requestID string) (*OAuthAuthorizationDecision, error) {
	user, ok := contexts.GetUser(ctx)
	if !ok || user == nil {
		return nil, fmt.Errorf("permission denied: authentication required")
	}

	redirectURL, err := r.oauthProviderService.ApproveAuthorization(ctx, requestID, user)
	if err != nil {
		return nil, fmt.Errorf("failed to approve oauth authorization: %w", err)
	}

	return &OAuthAuthorizationDecision{RedirectURL: redirectURL}, nil
}

// DenyOAuthAuthorization is the resolver for the denyOAuthAuthorization field.
func (r *mutationResolver) DenyOAuthAuthorization(ctx context.Context, requestID string) (*OAuthAuthorizationDecision, error) {
	redirectURL, err := r.oauthProviderService.DenyAuthorization(ctx, requestID)
	if err != nil {
		return nil, fmt.Errorf("failed to deny oauth authorization: %w", err)
	}

	return &OAuthAuthorizationDecision{RedirectURL: redirectURL}, nil
}

// OauthAuthorizationRequest is the resolver for the oauthAuthorizationRequest field.
func (r *queryResolver) OauthAuthorizationRequest(ctx context.Context, requestID string) (*OAuthAuthorizationRequest, error) {
	info, err := r.oauthProviderService.GetAuthorizationRequest(ctx, requestID)
	if err != nil {
		return nil, fmt.Errorf("failed to load oauth authorization request: %w", err)
	}

	userEmail := ""
	if user, ok := contexts.GetUser(ctx); ok && user != nil {
		userEmail = user.Email
	}

	return &OAuthAuthorizationRequest{
		ClientID:          info.ClientID,
		ClientName:        info.ClientName,
		ClientDescription: info.ClientDescription,
		RedirectURIHost:   info.RedirectURIHost,
		Scopes:            info.Scopes,
		UserEmail:         userEmail,
	}, nil
}
