package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/ldm2060/axonhub/internal/ent"
	"github.com/ldm2060/axonhub/internal/ent/usagemonitorchannel"
	"github.com/ldm2060/axonhub/internal/objects"
	"github.com/ldm2060/axonhub/internal/server/biz"
	"github.com/ldm2060/axonhub/internal/server/biz/usage_monitor"
	"github.com/samber/lo"
)

// ID is the resolver for the id field.
func (r *channelQuotaMonitorBindingResolver) ID(ctx context.Context, obj *biz.ChannelQuotaMonitorBindingView) (*objects.GUID, error) {
	return &objects.GUID{Type: ent.TypeChannelUsageMonitorBinding, ID: obj.ID}, nil
}

// ChannelID is the resolver for the channelID field.
func (r *channelQuotaMonitorBindingResolver) ChannelID(ctx context.Context, obj *biz.ChannelQuotaMonitorBindingView) (*objects.GUID, error) {
	return &objects.GUID{Type: ent.TypeChannel, ID: obj.ChannelID}, nil
}

// UsageMonitorChannelID is the resolver for the usageMonitorChannelID field.
func (r *channelQuotaMonitorBindingResolver) UsageMonitorChannelID(ctx context.Context, obj *biz.ChannelQuotaMonitorBindingView) (*objects.GUID, error) {
	return &objects.GUID{Type: ent.TypeUsageMonitorChannel, ID: obj.UsageMonitorChannelID}, nil
}

// CreateUsageMonitorChannel is the resolver for the createUsageMonitorChannel field.
func (r *mutationResolver) CreateUsageMonitorChannel(ctx context.Context, input usage_monitor.CreateUsageMonitorChannelInput) (*ent.UsageMonitorChannel, error) {
	return r.usageMonitorService.CreateChannel(ctx, input)
}

// UpdateUsageMonitorChannel is the resolver for the updateUsageMonitorChannel field.
func (r *mutationResolver) UpdateUsageMonitorChannel(ctx context.Context, id objects.GUID, input usage_monitor.UpdateUsageMonitorChannelInput) (*ent.UsageMonitorChannel, error) {
	return r.usageMonitorService.UpdateChannel(ctx, id.ID, input)
}

// DeleteUsageMonitorChannel is the resolver for the deleteUsageMonitorChannel field.
func (r *mutationResolver) DeleteUsageMonitorChannel(ctx context.Context, id objects.GUID) (bool, error) {
	if err := r.usageMonitorService.DeleteChannel(ctx, id.ID); err != nil {
		return false, err
	}
	return true, nil
}

// TestUsageMonitorChannel is the resolver for the testUsageMonitorChannel field.
func (r *mutationResolver) TestUsageMonitorChannel(ctx context.Context, input usage_monitor.TestUsageMonitorChannelInput) (*usage_monitor.TestResult, error) {
	return r.usageMonitorService.TestConnection(ctx, input), nil
}

// RefreshUsageMonitorChannel is the resolver for the refreshUsageMonitorChannel field.
func (r *mutationResolver) RefreshUsageMonitorChannel(ctx context.Context, id objects.GUID) (*ent.UsageMonitorChannel, error) {
	return r.usageMonitorService.RefreshChannel(ctx, id.ID)
}

// SaveChannelQuotaMonitorBindings is the resolver for the saveChannelQuotaMonitorBindings field.
func (r *mutationResolver) SaveChannelQuotaMonitorBindings(ctx context.Context, channelID objects.GUID, input biz.SaveChannelQuotaMonitorBindingsInput) ([]*biz.ChannelQuotaMonitorBindingView, error) {
	if err := r.usageMonitorService.SaveChannelQuotaMonitorBindingsAndEvaluate(ctx, channelID.ID, input); err != nil {
		return nil, err
	}
	views, err := r.usageMonitorService.ListChannelQuotaMonitorBindings(ctx, channelID.ID)
	if err != nil {
		return nil, err
	}
	result := make([]*biz.ChannelQuotaMonitorBindingView, len(views))
	for i := range views {
		result[i] = &views[i]
	}
	return result, nil
}

// Value is the resolver for the value field.
func (r *parsedFieldValueResolver) Value(ctx context.Context, obj *usage_monitor.ParsedField) (*string, error) {
	if obj.Value == nil {
		return nil, nil
	}
	str := usage_monitor.FormatFieldValue(obj.Value, obj.Format)
	return &str, nil
}

// Total is the resolver for the total field.
func (r *parsedFieldValueResolver) Total(ctx context.Context, obj *usage_monitor.ParsedField) (*string, error) {
	if obj.Total == nil {
		return nil, nil
	}
	str := usage_monitor.FormatFieldValue(obj.Total, obj.Format)
	return &str, nil
}

// UsageMonitorChannelsList is the resolver for the usageMonitorChannelsList field.
func (r *queryResolver) UsageMonitorChannelsList(ctx context.Context) ([]*ent.UsageMonitorChannel, error) {
	return r.usageMonitorService.ListChannels(ctx)
}

// UsageMonitorChannelByID is the resolver for the usageMonitorChannelById field.
func (r *queryResolver) UsageMonitorChannelByID(ctx context.Context, id objects.GUID) (*ent.UsageMonitorChannel, error) {
	return r.usageMonitorService.GetChannel(ctx, id.ID)
}

// QuotaMonitorTemplates is the resolver for the quotaMonitorTemplates field.
func (r *queryResolver) QuotaMonitorTemplates(ctx context.Context) ([]*usage_monitor.ChannelTemplate, error) {
	templates := usage_monitor.GetChannelTemplates()
	result := make([]*usage_monitor.ChannelTemplate, len(templates))
	for i := range templates {
		result[i] = &templates[i]
	}
	return result, nil
}

// ChannelQuotaMonitorBindings is the resolver for the channelQuotaMonitorBindings field.
func (r *queryResolver) ChannelQuotaMonitorBindings(ctx context.Context, channelID objects.GUID) ([]*biz.ChannelQuotaMonitorBindingView, error) {
	views, err := r.usageMonitorService.ListChannelQuotaMonitorBindings(ctx, channelID.ID)
	if err != nil {
		return nil, err
	}
	result := make([]*biz.ChannelQuotaMonitorBindingView, len(views))
	for i := range views {
		result[i] = &views[i]
	}
	return result, nil
}

// UsageMonitorBindingSummaries is the resolver for the usageMonitorBindingSummaries field.
func (r *queryResolver) UsageMonitorBindingSummaries(ctx context.Context) ([]*biz.UsageMonitorBindingSummary, error) {
	summaries, err := r.usageMonitorService.ListUsageMonitorBindingSummaries(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*biz.UsageMonitorBindingSummary, len(summaries))
	for i := range summaries {
		result[i] = &summaries[i]
	}
	return result, nil
}

// APIMethod is the resolver for the apiMethod field.
func (r *quotaMonitorTemplateResolver) APIMethod(ctx context.Context, obj *usage_monitor.ChannelTemplate) (usagemonitorchannel.APIMethod, error) {
	return usagemonitorchannel.APIMethod(obj.ApiMethod), nil
}

// Fields is the resolver for the fields field (deprecated).
func (r *quotaMonitorTemplateResolver) Fields(ctx context.Context, obj *usage_monitor.ChannelTemplate) ([]*usage_monitor.FieldConfig, error) {
	vars := obj.Variables
	result := make([]*usage_monitor.FieldConfig, len(vars))
	for i, v := range vars {
		fc := &usage_monitor.FieldConfig{
			Key:        v.Key,
			Path:       v.Path,
			Type:       v.Type,
			GroupIndex: v.GroupIndex,
		}
		// DisplayFields may be shorter than Variables; guard against out-of-bounds.
		if i < len(obj.DisplayFields) {
			fc.Label = obj.DisplayFields[i].Label
			fc.Format = obj.DisplayFields[i].Format
			fc.DisplayOrder = obj.DisplayFields[i].DisplayOrder
		}
		result[i] = fc
	}
	return result, nil
}

// Variables is the resolver for the variables field.
func (r *quotaMonitorTemplateResolver) Variables(ctx context.Context, obj *usage_monitor.ChannelTemplate) ([]*Variable, error) {
	result := make([]*Variable, len(obj.Variables))
	for i := range obj.Variables {
		result[i] = &Variable{
			Key:        obj.Variables[i].Key,
			Path:       obj.Variables[i].Path,
			Type:       obj.Variables[i].Type,
			GroupIndex: obj.Variables[i].GroupIndex,
		}
	}
	return result, nil
}

// DisplayFields is the resolver for the displayFields field.
func (r *quotaMonitorTemplateResolver) DisplayFields(ctx context.Context, obj *usage_monitor.ChannelTemplate) ([]*DisplayField, error) {
	result := make([]*DisplayField, len(obj.DisplayFields))
	for i := range obj.DisplayFields {
		df := obj.DisplayFields[i]
		result[i] = &DisplayField{
			Key:          df.Key,
			Label:        df.Label,
			ValueRef:     df.ValueRef,
			Format:       df.Format,
			DisplayOrder: df.DisplayOrder,
		}
		if df.Unit != "" {
			result[i].Unit = &df.Unit
		}
		if df.TotalRef != "" {
			result[i].TotalRef = &df.TotalRef
		}
		if df.Badge != "" {
			result[i].Badge = &df.Badge
		}
		if df.BadgePresets != "" {
			result[i].BadgePresets = &df.BadgePresets
		}
		if df.Group != "" {
			result[i].Group = &df.Group
		}
		if df.GroupLabelRef != "" {
			result[i].GroupLabelRef = &df.GroupLabelRef
		}
	}
	return result, nil
}

// ChannelID is the resolver for the channelID field.
func (r *usageMonitorBindingSummaryResolver) ChannelID(ctx context.Context, obj *biz.UsageMonitorBindingSummary) (*objects.GUID, error) {
	return &objects.GUID{Type: ent.TypeChannel, ID: obj.ChannelID}, nil
}

// UsageMonitorChannelID is the resolver for the usageMonitorChannelID field.
func (r *usageMonitorBindingSummaryResolver) UsageMonitorChannelID(ctx context.Context, obj *biz.UsageMonitorBindingSummary) (*objects.GUID, error) {
	return &objects.GUID{Type: ent.TypeUsageMonitorChannel, ID: obj.UsageMonitorChannelID}, nil
}

// APIHeadersString is the resolver for the apiHeadersString field.
func (r *usageMonitorChannelResolver) APIHeadersString(ctx context.Context, obj *ent.UsageMonitorChannel) (string, error) {
	if obj.APIHeaders == nil {
		return "{}", nil
	}
	bytes, err := json.Marshal(obj.APIHeaders)
	if err != nil {
		return "", fmt.Errorf("failed to marshal api headers: %w", err)
	}
	return string(bytes), nil
}

// ParsedData is the resolver for the parsedData field.
func (r *usageMonitorChannelResolver) ParsedData(ctx context.Context, obj *ent.UsageMonitorChannel) ([]*usage_monitor.ParsedField, error) {
	if obj.LastPollData == nil {
		return nil, nil
	}

	// Extract fields array from lastPollData
	fieldsRaw, ok := obj.LastPollData["fields"]
	if !ok {
		return nil, nil
	}

	// Marshal and unmarshal to convert to ParsedField slice
	bytes, err := json.Marshal(fieldsRaw)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal poll data fields: %w", err)
	}

	var fields []*usage_monitor.ParsedField
	if err := json.Unmarshal(bytes, &fields); err != nil {
		return nil, fmt.Errorf("failed to unmarshal poll data fields: %w", err)
	}

	return fields, nil
}

// APIKey is the resolver for the apiKey field.
func (r *usageMonitorChannelResolver) APIKey(ctx context.Context, obj *ent.UsageMonitorChannel) (*string, error) {
	if obj.APIKey == "" {
		return nil, nil
	}
	masked := "••••••••"
	return &masked, nil
}

// Variables is the resolver for the variables field.
func (r *usageMonitorChannelResolver) Variables(ctx context.Context, obj *ent.UsageMonitorChannel) ([]*Variable, error) {
	if len(obj.Variables) > 0 {
		return mapSliceToStructSlice[Variable](obj.Variables), nil
	}
	// Fallback: convert from legacy fields
	var fcs []usage_monitor.FieldConfig
	raw, _ := json.Marshal(obj.Fields)
	_ = json.Unmarshal(raw, &fcs)
	vars := usage_monitor.VariablesFromFieldConfigs(fcs)
	return mapSliceToStructSlice[Variable](structSliceToMapSlice(vars)), nil
}

// DisplayFields is the resolver for the displayFields field.
func (r *usageMonitorChannelResolver) DisplayFields(ctx context.Context, obj *ent.UsageMonitorChannel) ([]*DisplayField, error) {
	enrichFromTemplate := func(dfs []usage_monitor.DisplayField) {
		if obj.Source != usagemonitorchannel.SourceTemplate || obj.ProviderType == "" {
			return
		}
		tmpl := usage_monitor.GetChannelTemplate(string(obj.ProviderType))
		if tmpl == nil {
			return
		}
		tmplDFMap := make(map[string]usage_monitor.DisplayField, len(tmpl.DisplayFields))
		for _, df := range tmpl.DisplayFields {
			tmplDFMap[df.Key] = df
		}
		for i := range dfs {
			tdf, ok := tmplDFMap[dfs[i].Key]
			if !ok {
				continue
			}
			if dfs[i].ValueRef == dfs[i].Key && tdf.ValueRef != "" && tdf.ValueRef != tdf.Key {
				dfs[i].ValueRef = tdf.ValueRef
			}
			if dfs[i].Badge == "" && tdf.Badge != "" {
				dfs[i].Badge = tdf.Badge
			}
			if dfs[i].BadgePresets == "" && tdf.BadgePresets != "" {
				dfs[i].BadgePresets = tdf.BadgePresets
			}
			if dfs[i].Group == "" && tdf.Group != "" {
				dfs[i].Group = tdf.Group
			}
			if dfs[i].GroupLabelRef == "" && tdf.GroupLabelRef != "" {
				dfs[i].GroupLabelRef = tdf.GroupLabelRef
			}
		}
	}

	if len(obj.DisplayFields) > 0 {
		var dfs []usage_monitor.DisplayField
		raw, _ := json.Marshal(obj.DisplayFields)
		_ = json.Unmarshal(raw, &dfs)
		enrichFromTemplate(dfs)
		return mapSliceToStructSlice[DisplayField](structSliceToMapSlice(dfs)), nil
	}
	// Fallback: convert from legacy fields
	var fcs []usage_monitor.FieldConfig
	raw, _ := json.Marshal(obj.Fields)
	_ = json.Unmarshal(raw, &fcs)
	dfs := usage_monitor.DisplayFieldsFromFieldConfigs(fcs)
	enrichFromTemplate(dfs)
	return mapSliceToStructSlice[DisplayField](structSliceToMapSlice(dfs)), nil
}

// Source is the resolver for the source field.
func (r *createUsageMonitorChannelInputResolver) Source(ctx context.Context, obj *usage_monitor.CreateUsageMonitorChannelInput, data usagemonitorchannel.Source) error {
	obj.Source = string(data)
	return nil
}

// ChannelID is the resolver for the channelId field.
func (r *createUsageMonitorChannelInputResolver) ChannelID(ctx context.Context, obj *usage_monitor.CreateUsageMonitorChannelInput, data *objects.GUID) error {
	if data != nil {
		str := fmt.Sprintf("%d", data.ID)
		obj.ChannelID = &str
	}
	return nil
}

// ProviderType is the resolver for the providerType field.
func (r *createUsageMonitorChannelInputResolver) ProviderType(ctx context.Context, obj *usage_monitor.CreateUsageMonitorChannelInput, data *usagemonitorchannel.ProviderType) error {
	if data != nil {
		obj.ProviderType = lo.ToPtr(string(*data))
	}
	return nil
}

// APIMethod is the resolver for the apiMethod field.
func (r *createUsageMonitorChannelInputResolver) APIMethod(ctx context.Context, obj *usage_monitor.CreateUsageMonitorChannelInput, data *usagemonitorchannel.APIMethod) error {
	if data != nil {
		obj.ApiMethod = string(*data)
	}
	return nil
}

// Variables is the resolver for the variables field.
func (r *createUsageMonitorChannelInputResolver) Variables(ctx context.Context, obj *usage_monitor.CreateUsageMonitorChannelInput, data []*VariableInput) error {
	if data != nil {
		vars := make([]usage_monitor.Variable, len(data))
		for i, v := range data {
			vars[i] = usage_monitor.Variable{
				Key:        v.Key,
				Path:       v.Path,
				Type:       v.Type,
				GroupIndex: v.GroupIndex,
			}
		}
		obj.Variables = vars
	}
	return nil
}

// DisplayFields is the resolver for the displayFields field.
func (r *createUsageMonitorChannelInputResolver) DisplayFields(ctx context.Context, obj *usage_monitor.CreateUsageMonitorChannelInput, data []*DisplayFieldInput) error {
	if data != nil {
		dfs := make([]usage_monitor.DisplayField, len(data))
		for i, v := range data {
			dfs[i] = usage_monitor.DisplayField{
				Key:           v.Key,
				Label:         v.Label,
				ValueRef:      v.ValueRef,
				Format:        v.Format,
				Unit:          lo.FromPtr(v.Unit),
				TotalRef:      lo.FromPtr(v.TotalRef),
				DisplayOrder:  v.DisplayOrder,
				Badge:         lo.FromPtr(v.Badge),
				BadgePresets:  lo.FromPtr(v.BadgePresets),
				Group:         lo.FromPtr(v.Group),
				GroupLabelRef: lo.FromPtr(v.GroupLabelRef),
			}
		}
		obj.DisplayFields = dfs
	}
	return nil
}

// APIMethod is the resolver for the apiMethod field.
func (r *testUsageMonitorChannelInputResolver) APIMethod(ctx context.Context, obj *usage_monitor.TestUsageMonitorChannelInput, data usagemonitorchannel.APIMethod) error {
	obj.ApiMethod = string(data)
	return nil
}

// Variables is the resolver for the variables field.
func (r *testUsageMonitorChannelInputResolver) Variables(ctx context.Context, obj *usage_monitor.TestUsageMonitorChannelInput, data []*VariableInput) error {
	if data != nil {
		vars := make([]usage_monitor.Variable, len(data))
		for i, v := range data {
			vars[i] = usage_monitor.Variable{
				Key:        v.Key,
				Path:       v.Path,
				Type:       v.Type,
				GroupIndex: v.GroupIndex,
			}
		}
		obj.Variables = vars
	}
	return nil
}

// DisplayFields is the resolver for the displayFields field.
func (r *testUsageMonitorChannelInputResolver) DisplayFields(ctx context.Context, obj *usage_monitor.TestUsageMonitorChannelInput, data []*DisplayFieldInput) error {
	if data != nil {
		dfs := make([]usage_monitor.DisplayField, len(data))
		for i, v := range data {
			dfs[i] = usage_monitor.DisplayField{
				Key:           v.Key,
				Label:         v.Label,
				ValueRef:      v.ValueRef,
				Format:        v.Format,
				Unit:          lo.FromPtr(v.Unit),
				TotalRef:      lo.FromPtr(v.TotalRef),
				DisplayOrder:  v.DisplayOrder,
				Badge:         lo.FromPtr(v.Badge),
				BadgePresets:  lo.FromPtr(v.BadgePresets),
				Group:         lo.FromPtr(v.Group),
				GroupLabelRef: lo.FromPtr(v.GroupLabelRef),
			}
		}
		obj.DisplayFields = dfs
	}
	return nil
}

// APIMethod is the resolver for the apiMethod field.
func (r *updateUsageMonitorChannelInputResolver) APIMethod(ctx context.Context, obj *usage_monitor.UpdateUsageMonitorChannelInput, data *usagemonitorchannel.APIMethod) error {
	if data != nil {
		str := string(*data)
		obj.ApiMethod = &str
	}
	return nil
}

// Variables is the resolver for the variables field.
func (r *updateUsageMonitorChannelInputResolver) Variables(ctx context.Context, obj *usage_monitor.UpdateUsageMonitorChannelInput, data []*VariableInput) error {
	if data != nil {
		vars := make([]usage_monitor.Variable, len(data))
		for i, v := range data {
			vars[i] = usage_monitor.Variable{
				Key:        v.Key,
				Path:       v.Path,
				Type:       v.Type,
				GroupIndex: v.GroupIndex,
			}
		}
		obj.Variables = &vars
	}
	return nil
}

// DisplayFields is the resolver for the displayFields field.
func (r *updateUsageMonitorChannelInputResolver) DisplayFields(ctx context.Context, obj *usage_monitor.UpdateUsageMonitorChannelInput, data []*DisplayFieldInput) error {
	if data != nil {
		dfs := make([]usage_monitor.DisplayField, len(data))
		for i, v := range data {
			dfs[i] = usage_monitor.DisplayField{
				Key:           v.Key,
				Label:         v.Label,
				ValueRef:      v.ValueRef,
				Format:        v.Format,
				Unit:          lo.FromPtr(v.Unit),
				TotalRef:      lo.FromPtr(v.TotalRef),
				DisplayOrder:  v.DisplayOrder,
				Badge:         lo.FromPtr(v.Badge),
				BadgePresets:  lo.FromPtr(v.BadgePresets),
				Group:         lo.FromPtr(v.Group),
				GroupLabelRef: lo.FromPtr(v.GroupLabelRef),
			}
		}
		obj.DisplayFields = &dfs
	}
	return nil
}

// Status is the resolver for the status field.
func (r *updateUsageMonitorChannelInputResolver) Status(ctx context.Context, obj *usage_monitor.UpdateUsageMonitorChannelInput, data *usagemonitorchannel.Status) error {
	if data != nil {
		str := string(*data)
		obj.Status = &str
	}
	return nil
}

// ChannelQuotaMonitorBinding returns ChannelQuotaMonitorBindingResolver implementation.
func (r *Resolver) ChannelQuotaMonitorBinding() ChannelQuotaMonitorBindingResolver {
	return &channelQuotaMonitorBindingResolver{r}
}

// ParsedFieldValue returns ParsedFieldValueResolver implementation.
func (r *Resolver) ParsedFieldValue() ParsedFieldValueResolver { return &parsedFieldValueResolver{r} }

// QuotaMonitorTemplate returns QuotaMonitorTemplateResolver implementation.
func (r *Resolver) QuotaMonitorTemplate() QuotaMonitorTemplateResolver {
	return &quotaMonitorTemplateResolver{r}
}

// UsageMonitorBindingSummary returns UsageMonitorBindingSummaryResolver implementation.
func (r *Resolver) UsageMonitorBindingSummary() UsageMonitorBindingSummaryResolver {
	return &usageMonitorBindingSummaryResolver{r}
}

// CreateUsageMonitorChannelInput returns CreateUsageMonitorChannelInputResolver implementation.
func (r *Resolver) CreateUsageMonitorChannelInput() CreateUsageMonitorChannelInputResolver {
	return &createUsageMonitorChannelInputResolver{r}
}

// TestUsageMonitorChannelInput returns TestUsageMonitorChannelInputResolver implementation.
func (r *Resolver) TestUsageMonitorChannelInput() TestUsageMonitorChannelInputResolver {
	return &testUsageMonitorChannelInputResolver{r}
}

// UpdateUsageMonitorChannelInput returns UpdateUsageMonitorChannelInputResolver implementation.
func (r *Resolver) UpdateUsageMonitorChannelInput() UpdateUsageMonitorChannelInputResolver {
	return &updateUsageMonitorChannelInputResolver{r}
}

type channelQuotaMonitorBindingResolver struct{ *Resolver }
type parsedFieldValueResolver struct{ *Resolver }
type quotaMonitorTemplateResolver struct{ *Resolver }
type usageMonitorBindingSummaryResolver struct{ *Resolver }
type createUsageMonitorChannelInputResolver struct{ *Resolver }
type testUsageMonitorChannelInputResolver struct{ *Resolver }
type updateUsageMonitorChannelInputResolver struct{ *Resolver }
