package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/ldm2060/axonhub/internal/ent"
	"github.com/ldm2060/axonhub/internal/ent/usagemonitorchannel"
	"github.com/ldm2060/axonhub/internal/objects"
	"github.com/ldm2060/axonhub/internal/server/biz/usage_monitor"
)

// CreateUsageMonitorChannel is the resolver for the createUsageMonitorChannel field.
func (r *mutationResolver) CreateUsageMonitorChannel(ctx context.Context, input usage_monitor.CreateUsageMonitorChannelInput) (*ent.UsageMonitorChannel, error) {
	return r.usageMonitorService.CreateChannel(ctx, input)
}

// UpdateUsageMonitorChannel is the resolver for the updateUsageMonitorChannel field.
func (r *mutationResolver) UpdateUsageMonitorChannel(ctx context.Context, id objects.GUID, input usage_monitor.UpdateUsageMonitorChannelInput) (*ent.UsageMonitorChannel, error) {
	return r.usageMonitorService.UpdateChannel(ctx, id.ID, input)
}

// DeleteUsageMonitorChannel is the resolver for the deleteUsageMonitorChannel field.
func (r *mutationResolver) DeleteUsageMonitorChannel(ctx context.Context, id objects.GUID) (bool, error) {
	if err := r.usageMonitorService.DeleteChannel(ctx, id.ID); err != nil {
		return false, err
	}
	return true, nil
}

// TestUsageMonitorChannel is the resolver for the testUsageMonitorChannel field.
func (r *mutationResolver) TestUsageMonitorChannel(ctx context.Context, input usage_monitor.TestUsageMonitorChannelInput) (*usage_monitor.TestResult, error) {
	return r.usageMonitorService.TestConnection(ctx, input), nil
}

// RefreshUsageMonitorChannel is the resolver for the refreshUsageMonitorChannel field.
func (r *mutationResolver) RefreshUsageMonitorChannel(ctx context.Context, id objects.GUID) (*ent.UsageMonitorChannel, error) {
	return r.usageMonitorService.RefreshChannel(ctx, id.ID)
}

// Value is the resolver for the value field.
func (r *parsedFieldValueResolver) Value(ctx context.Context, obj *usage_monitor.ParsedField) (*string, error) {
	if obj.Value == nil {
		return nil, nil
	}
	str := fmt.Sprintf("%v", obj.Value)
	return &str, nil
}

// Total is the resolver for the total field.
func (r *parsedFieldValueResolver) Total(ctx context.Context, obj *usage_monitor.ParsedField) (*string, error) {
	if obj.Total == nil {
		return nil, nil
	}
	str := fmt.Sprintf("%v", obj.Total)
	return &str, nil
}

// UsageMonitorChannelsList is the resolver for the usageMonitorChannelsList field.
func (r *queryResolver) UsageMonitorChannelsList(ctx context.Context) ([]*ent.UsageMonitorChannel, error) {
	return r.usageMonitorService.ListChannels(ctx)
}

// UsageMonitorChannelByID is the resolver for the usageMonitorChannelById field.
func (r *queryResolver) UsageMonitorChannelByID(ctx context.Context, id objects.GUID) (*ent.UsageMonitorChannel, error) {
	return r.usageMonitorService.GetChannel(ctx, id.ID)
}

// APIHeadersString is the resolver for the apiHeadersString field.
func (r *usageMonitorChannelResolver) APIHeadersString(ctx context.Context, obj *ent.UsageMonitorChannel) (string, error) {
	if obj.APIHeaders == nil {
		return "{}", nil
	}
	bytes, err := json.Marshal(obj.APIHeaders)
	if err != nil {
		return "", fmt.Errorf("failed to marshal api headers: %w", err)
	}
	return string(bytes), nil
}

// ParsedData is the resolver for the parsedData field.
func (r *usageMonitorChannelResolver) ParsedData(ctx context.Context, obj *ent.UsageMonitorChannel) ([]*usage_monitor.ParsedField, error) {
	if obj.LastPollData == nil {
		return nil, nil
	}

	// Extract fields array from lastPollData
	fieldsRaw, ok := obj.LastPollData["fields"]
	if !ok {
		return nil, nil
	}

	// Marshal and unmarshal to convert to ParsedField slice
	bytes, err := json.Marshal(fieldsRaw)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal poll data fields: %w", err)
	}

	var fields []*usage_monitor.ParsedField
	if err := json.Unmarshal(bytes, &fields); err != nil {
		return nil, fmt.Errorf("failed to unmarshal poll data fields: %w", err)
	}

	return fields, nil
}

// Source is the resolver for the source field.
func (r *createUsageMonitorChannelInputResolver) Source(ctx context.Context, obj *usage_monitor.CreateUsageMonitorChannelInput, data usagemonitorchannel.Source) error {
	obj.Source = string(data)
	return nil
}

// ChannelID is the resolver for the channelId field.
func (r *createUsageMonitorChannelInputResolver) ChannelID(ctx context.Context, obj *usage_monitor.CreateUsageMonitorChannelInput, data *objects.GUID) error {
	if data != nil {
		str := fmt.Sprintf("%d", data.ID)
		obj.ChannelID = &str
	}
	return nil
}

// APIMethod is the resolver for the apiMethod field.
func (r *createUsageMonitorChannelInputResolver) APIMethod(ctx context.Context, obj *usage_monitor.CreateUsageMonitorChannelInput, data usagemonitorchannel.APIMethod) error {
	obj.ApiMethod = string(data)
	return nil
}

// APIMethod is the resolver for the apiMethod field.
func (r *testUsageMonitorChannelInputResolver) APIMethod(ctx context.Context, obj *usage_monitor.TestUsageMonitorChannelInput, data usagemonitorchannel.APIMethod) error {
	obj.ApiMethod = string(data)
	return nil
}

// APIMethod is the resolver for the apiMethod field.
func (r *updateUsageMonitorChannelInputResolver) APIMethod(ctx context.Context, obj *usage_monitor.UpdateUsageMonitorChannelInput, data *usagemonitorchannel.APIMethod) error {
	if data != nil {
		str := string(*data)
		obj.ApiMethod = &str
	}
	return nil
}

// Status is the resolver for the status field.
func (r *updateUsageMonitorChannelInputResolver) Status(ctx context.Context, obj *usage_monitor.UpdateUsageMonitorChannelInput, data *usagemonitorchannel.Status) error {
	if data != nil {
		str := string(*data)
		obj.Status = &str
	}
	return nil
}

// ParsedFieldValue returns ParsedFieldValueResolver implementation.
func (r *Resolver) ParsedFieldValue() ParsedFieldValueResolver { return &parsedFieldValueResolver{r} }

// CreateUsageMonitorChannelInput returns CreateUsageMonitorChannelInputResolver implementation.
func (r *Resolver) CreateUsageMonitorChannelInput() CreateUsageMonitorChannelInputResolver {
	return &createUsageMonitorChannelInputResolver{r}
}

// TestUsageMonitorChannelInput returns TestUsageMonitorChannelInputResolver implementation.
func (r *Resolver) TestUsageMonitorChannelInput() TestUsageMonitorChannelInputResolver {
	return &testUsageMonitorChannelInputResolver{r}
}

// UpdateUsageMonitorChannelInput returns UpdateUsageMonitorChannelInputResolver implementation.
func (r *Resolver) UpdateUsageMonitorChannelInput() UpdateUsageMonitorChannelInputResolver {
	return &updateUsageMonitorChannelInputResolver{r}
}

type parsedFieldValueResolver struct{ *Resolver }
type createUsageMonitorChannelInputResolver struct{ *Resolver }
type testUsageMonitorChannelInputResolver struct{ *Resolver }
type updateUsageMonitorChannelInputResolver struct{ *Resolver }
