// Code generated by ent, DO NOT EDIT.

package usagemonitorchannel

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the usagemonitorchannel type in the database.
	Label = "usage_monitor_channel"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldProviderType holds the string denoting the provider_type field in the database.
	FieldProviderType = "provider_type"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldAPIURL holds the string denoting the api_url field in the database.
	FieldAPIURL = "api_url"
	// FieldAPIMethod holds the string denoting the api_method field in the database.
	FieldAPIMethod = "api_method"
	// FieldAPIHeaders holds the string denoting the api_headers field in the database.
	FieldAPIHeaders = "api_headers"
	// FieldAPIBody holds the string denoting the api_body field in the database.
	FieldAPIBody = "api_body"
	// FieldAPIKey holds the string denoting the api_key field in the database.
	FieldAPIKey = "api_key"
	// FieldPollInterval holds the string denoting the poll_interval field in the database.
	FieldPollInterval = "poll_interval"
	// FieldFields holds the string denoting the fields field in the database.
	FieldFields = "fields"
	// FieldVariables holds the string denoting the variables field in the database.
	FieldVariables = "variables"
	// FieldDisplayFields holds the string denoting the display_fields field in the database.
	FieldDisplayFields = "display_fields"
	// FieldLastPollAt holds the string denoting the last_poll_at field in the database.
	FieldLastPollAt = "last_poll_at"
	// FieldLastPollData holds the string denoting the last_poll_data field in the database.
	FieldLastPollData = "last_poll_data"
	// FieldLastPollError holds the string denoting the last_poll_error field in the database.
	FieldLastPollError = "last_poll_error"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldQuotaStatus holds the string denoting the quota_status field in the database.
	FieldQuotaStatus = "quota_status"
	// FieldQuotaReady holds the string denoting the quota_ready field in the database.
	FieldQuotaReady = "quota_ready"
	// FieldQuotaLimits holds the string denoting the quota_limits field in the database.
	FieldQuotaLimits = "quota_limits"
	// FieldNextResetAt holds the string denoting the next_reset_at field in the database.
	FieldNextResetAt = "next_reset_at"
	// EdgeChannel holds the string denoting the channel edge name in mutations.
	EdgeChannel = "channel"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// Table holds the table name of the usagemonitorchannel in the database.
	Table = "usage_monitor_channels"
	// ChannelTable is the table that holds the channel relation/edge.
	ChannelTable = "usage_monitor_channels"
	// ChannelInverseTable is the table name for the Channel entity.
	// It exists in this package in order to avoid circular dependency with the "channel" package.
	ChannelInverseTable = "channels"
	// ChannelColumn is the table column denoting the channel relation/edge.
	ChannelColumn = "channel_id"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "usage_monitor_channels"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_usage_monitor_channels"
)

// Columns holds all SQL columns for usagemonitorchannel fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldSource,
	FieldProviderType,
	FieldChannelID,
	FieldAPIURL,
	FieldAPIMethod,
	FieldAPIHeaders,
	FieldAPIBody,
	FieldAPIKey,
	FieldPollInterval,
	FieldFields,
	FieldVariables,
	FieldDisplayFields,
	FieldLastPollAt,
	FieldLastPollData,
	FieldLastPollError,
	FieldStatus,
	FieldQuotaStatus,
	FieldQuotaReady,
	FieldQuotaLimits,
	FieldNextResetAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "usage_monitor_channels"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_usage_monitor_channels",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/ldm2060/axonhub/internal/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt int
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// APIURLValidator is a validator for the "api_url" field. It is called by the builders before save.
	APIURLValidator func(string) error
	// DefaultPollInterval holds the default value on creation for the "poll_interval" field.
	DefaultPollInterval int
	// DefaultVariables holds the default value on creation for the "variables" field.
	DefaultVariables []map[string]interface{}
	// DefaultDisplayFields holds the default value on creation for the "display_fields" field.
	DefaultDisplayFields []map[string]interface{}
	// DefaultQuotaReady holds the default value on creation for the "quota_ready" field.
	DefaultQuotaReady bool
)

// Source defines the type for the "source" enum field.
type Source string

// Source values.
const (
	SourceBuiltin  Source = "builtin"
	SourceCustom   Source = "custom"
	SourceTemplate Source = "template"
)

func (s Source) String() string {
	return string(s)
}

// SourceValidator is a validator for the "source" field enum values. It is called by the builders before save.
func SourceValidator(s Source) error {
	switch s {
	case SourceBuiltin, SourceCustom, SourceTemplate:
		return nil
	default:
		return fmt.Errorf("usagemonitorchannel: invalid enum value for source field: %q", s)
	}
}

// ProviderType defines the type for the "provider_type" enum field.
type ProviderType string

// ProviderType values.
const (
	ProviderTypeClaudecode    ProviderType = "claudecode"
	ProviderTypeCodex         ProviderType = "codex"
	ProviderTypeGithubCopilot ProviderType = "github_copilot"
	ProviderTypeNanogpt       ProviderType = "nanogpt"
	ProviderTypeWafer         ProviderType = "wafer"
	ProviderTypeSynthetic     ProviderType = "synthetic"
	ProviderTypeNeuralwatt    ProviderType = "neuralwatt"
	ProviderTypeZhipu         ProviderType = "zhipu"
	ProviderTypeAntigravity   ProviderType = "antigravity"
	ProviderTypeApertis       ProviderType = "apertis"
)

func (pt ProviderType) String() string {
	return string(pt)
}

// ProviderTypeValidator is a validator for the "provider_type" field enum values. It is called by the builders before save.
func ProviderTypeValidator(pt ProviderType) error {
	switch pt {
	case ProviderTypeClaudecode, ProviderTypeCodex, ProviderTypeGithubCopilot, ProviderTypeNanogpt, ProviderTypeWafer, ProviderTypeSynthetic, ProviderTypeNeuralwatt, ProviderTypeZhipu, ProviderTypeAntigravity, ProviderTypeApertis:
		return nil
	default:
		return fmt.Errorf("usagemonitorchannel: invalid enum value for provider_type field: %q", pt)
	}
}

// APIMethod defines the type for the "api_method" enum field.
type APIMethod string

// APIMethodGET is the default value of the APIMethod enum.
const DefaultAPIMethod = APIMethodGET

// APIMethod values.
const (
	APIMethodGET  APIMethod = "GET"
	APIMethodPOST APIMethod = "POST"
)

func (am APIMethod) String() string {
	return string(am)
}

// APIMethodValidator is a validator for the "api_method" field enum values. It is called by the builders before save.
func APIMethodValidator(am APIMethod) error {
	switch am {
	case APIMethodGET, APIMethodPOST:
		return nil
	default:
		return fmt.Errorf("usagemonitorchannel: invalid enum value for api_method field: %q", am)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive Status = "active"
	StatusPaused Status = "paused"
	StatusError  Status = "error"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusPaused, StatusError:
		return nil
	default:
		return fmt.Errorf("usagemonitorchannel: invalid enum value for status field: %q", s)
	}
}

// QuotaStatus defines the type for the "quota_status" enum field.
type QuotaStatus string

// QuotaStatus values.
const (
	QuotaStatusAvailable QuotaStatus = "available"
	QuotaStatusWarning   QuotaStatus = "warning"
	QuotaStatusExhausted QuotaStatus = "exhausted"
	QuotaStatusUnknown   QuotaStatus = "unknown"
)

func (qs QuotaStatus) String() string {
	return string(qs)
}

// QuotaStatusValidator is a validator for the "quota_status" field enum values. It is called by the builders before save.
func QuotaStatusValidator(qs QuotaStatus) error {
	switch qs {
	case QuotaStatusAvailable, QuotaStatusWarning, QuotaStatusExhausted, QuotaStatusUnknown:
		return nil
	default:
		return fmt.Errorf("usagemonitorchannel: invalid enum value for quota_status field: %q", qs)
	}
}

// OrderOption defines the ordering options for the UsageMonitorChannel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByProviderType orders the results by the provider_type field.
func ByProviderType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderType, opts...).ToFunc()
}

// ByChannelID orders the results by the channel_id field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByAPIURL orders the results by the api_url field.
func ByAPIURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIURL, opts...).ToFunc()
}

// ByAPIMethod orders the results by the api_method field.
func ByAPIMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIMethod, opts...).ToFunc()
}

// ByAPIBody orders the results by the api_body field.
func ByAPIBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIBody, opts...).ToFunc()
}

// ByAPIKey orders the results by the api_key field.
func ByAPIKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKey, opts...).ToFunc()
}

// ByPollInterval orders the results by the poll_interval field.
func ByPollInterval(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPollInterval, opts...).ToFunc()
}

// ByLastPollAt orders the results by the last_poll_at field.
func ByLastPollAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastPollAt, opts...).ToFunc()
}

// ByLastPollError orders the results by the last_poll_error field.
func ByLastPollError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastPollError, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByQuotaStatus orders the results by the quota_status field.
func ByQuotaStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaStatus, opts...).ToFunc()
}

// ByQuotaReady orders the results by the quota_ready field.
func ByQuotaReady(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaReady, opts...).ToFunc()
}

// ByNextResetAt orders the results by the next_reset_at field.
func ByNextResetAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextResetAt, opts...).ToFunc()
}

// ByChannelField orders the results by channel field.
func ByChannelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelStep(), sql.OrderByField(field, opts...))
	}
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}
func newChannelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
	)
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Source) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Source) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Source(str)
	if err := SourceValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Source", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e ProviderType) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *ProviderType) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = ProviderType(str)
	if err := ProviderTypeValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid ProviderType", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e APIMethod) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *APIMethod) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = APIMethod(str)
	if err := APIMethodValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid APIMethod", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Status) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Status) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Status(str)
	if err := StatusValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e QuotaStatus) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *QuotaStatus) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = QuotaStatus(str)
	if err := QuotaStatusValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid QuotaStatus", str)
	}
	return nil
}
