// Code generated by ent, DO NOT EDIT.

package usagemonitorchannel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ldm2060/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldName, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldChannelID, v))
}

// APIURL applies equality check predicate on the "api_url" field. It's identical to APIURLEQ.
func APIURL(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldAPIURL, v))
}

// APIBody applies equality check predicate on the "api_body" field. It's identical to APIBodyEQ.
func APIBody(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldAPIBody, v))
}

// APIKey applies equality check predicate on the "api_key" field. It's identical to APIKeyEQ.
func APIKey(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldAPIKey, v))
}

// PollInterval applies equality check predicate on the "poll_interval" field. It's identical to PollIntervalEQ.
func PollInterval(v int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldPollInterval, v))
}

// LastPollAt applies equality check predicate on the "last_poll_at" field. It's identical to LastPollAtEQ.
func LastPollAt(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldLastPollAt, v))
}

// LastPollError applies equality check predicate on the "last_poll_error" field. It's identical to LastPollErrorEQ.
func LastPollError(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldLastPollError, v))
}

// QuotaReady applies equality check predicate on the "quota_ready" field. It's identical to QuotaReadyEQ.
func QuotaReady(v bool) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldQuotaReady, v))
}

// NextResetAt applies equality check predicate on the "next_reset_at" field. It's identical to NextResetAtEQ.
func NextResetAt(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldNextResetAt, v))
}

// AutoDisableEnabled applies equality check predicate on the "auto_disable_enabled" field. It's identical to AutoDisableEnabledEQ.
func AutoDisableEnabled(v bool) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldAutoDisableEnabled, v))
}

// AutoDisableThreshold applies equality check predicate on the "auto_disable_threshold" field. It's identical to AutoDisableThresholdEQ.
func AutoDisableThreshold(v float64) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldAutoDisableThreshold, v))
}

// AutoEnableThreshold applies equality check predicate on the "auto_enable_threshold" field. It's identical to AutoEnableThresholdEQ.
func AutoEnableThreshold(v float64) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldAutoEnableThreshold, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLTE(FieldDeletedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldContainsFold(FieldName, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v Source) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v Source) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...Source) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...Source) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotIn(FieldSource, vs...))
}

// ProviderTypeEQ applies the EQ predicate on the "provider_type" field.
func ProviderTypeEQ(v ProviderType) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldProviderType, v))
}

// ProviderTypeNEQ applies the NEQ predicate on the "provider_type" field.
func ProviderTypeNEQ(v ProviderType) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNEQ(FieldProviderType, v))
}

// ProviderTypeIn applies the In predicate on the "provider_type" field.
func ProviderTypeIn(vs ...ProviderType) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIn(FieldProviderType, vs...))
}

// ProviderTypeNotIn applies the NotIn predicate on the "provider_type" field.
func ProviderTypeNotIn(vs ...ProviderType) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotIn(FieldProviderType, vs...))
}

// ProviderTypeIsNil applies the IsNil predicate on the "provider_type" field.
func ProviderTypeIsNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIsNull(FieldProviderType))
}

// ProviderTypeNotNil applies the NotNil predicate on the "provider_type" field.
func ProviderTypeNotNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotNull(FieldProviderType))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotIn(FieldChannelID, vs...))
}

// ChannelIDIsNil applies the IsNil predicate on the "channel_id" field.
func ChannelIDIsNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIsNull(FieldChannelID))
}

// ChannelIDNotNil applies the NotNil predicate on the "channel_id" field.
func ChannelIDNotNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotNull(FieldChannelID))
}

// APIURLEQ applies the EQ predicate on the "api_url" field.
func APIURLEQ(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldAPIURL, v))
}

// APIURLNEQ applies the NEQ predicate on the "api_url" field.
func APIURLNEQ(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNEQ(FieldAPIURL, v))
}

// APIURLIn applies the In predicate on the "api_url" field.
func APIURLIn(vs ...string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIn(FieldAPIURL, vs...))
}

// APIURLNotIn applies the NotIn predicate on the "api_url" field.
func APIURLNotIn(vs ...string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotIn(FieldAPIURL, vs...))
}

// APIURLGT applies the GT predicate on the "api_url" field.
func APIURLGT(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGT(FieldAPIURL, v))
}

// APIURLGTE applies the GTE predicate on the "api_url" field.
func APIURLGTE(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGTE(FieldAPIURL, v))
}

// APIURLLT applies the LT predicate on the "api_url" field.
func APIURLLT(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLT(FieldAPIURL, v))
}

// APIURLLTE applies the LTE predicate on the "api_url" field.
func APIURLLTE(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLTE(FieldAPIURL, v))
}

// APIURLContains applies the Contains predicate on the "api_url" field.
func APIURLContains(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldContains(FieldAPIURL, v))
}

// APIURLHasPrefix applies the HasPrefix predicate on the "api_url" field.
func APIURLHasPrefix(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldHasPrefix(FieldAPIURL, v))
}

// APIURLHasSuffix applies the HasSuffix predicate on the "api_url" field.
func APIURLHasSuffix(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldHasSuffix(FieldAPIURL, v))
}

// APIURLEqualFold applies the EqualFold predicate on the "api_url" field.
func APIURLEqualFold(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEqualFold(FieldAPIURL, v))
}

// APIURLContainsFold applies the ContainsFold predicate on the "api_url" field.
func APIURLContainsFold(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldContainsFold(FieldAPIURL, v))
}

// APIMethodEQ applies the EQ predicate on the "api_method" field.
func APIMethodEQ(v APIMethod) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldAPIMethod, v))
}

// APIMethodNEQ applies the NEQ predicate on the "api_method" field.
func APIMethodNEQ(v APIMethod) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNEQ(FieldAPIMethod, v))
}

// APIMethodIn applies the In predicate on the "api_method" field.
func APIMethodIn(vs ...APIMethod) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIn(FieldAPIMethod, vs...))
}

// APIMethodNotIn applies the NotIn predicate on the "api_method" field.
func APIMethodNotIn(vs ...APIMethod) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotIn(FieldAPIMethod, vs...))
}

// APIBodyEQ applies the EQ predicate on the "api_body" field.
func APIBodyEQ(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldAPIBody, v))
}

// APIBodyNEQ applies the NEQ predicate on the "api_body" field.
func APIBodyNEQ(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNEQ(FieldAPIBody, v))
}

// APIBodyIn applies the In predicate on the "api_body" field.
func APIBodyIn(vs ...string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIn(FieldAPIBody, vs...))
}

// APIBodyNotIn applies the NotIn predicate on the "api_body" field.
func APIBodyNotIn(vs ...string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotIn(FieldAPIBody, vs...))
}

// APIBodyGT applies the GT predicate on the "api_body" field.
func APIBodyGT(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGT(FieldAPIBody, v))
}

// APIBodyGTE applies the GTE predicate on the "api_body" field.
func APIBodyGTE(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGTE(FieldAPIBody, v))
}

// APIBodyLT applies the LT predicate on the "api_body" field.
func APIBodyLT(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLT(FieldAPIBody, v))
}

// APIBodyLTE applies the LTE predicate on the "api_body" field.
func APIBodyLTE(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLTE(FieldAPIBody, v))
}

// APIBodyContains applies the Contains predicate on the "api_body" field.
func APIBodyContains(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldContains(FieldAPIBody, v))
}

// APIBodyHasPrefix applies the HasPrefix predicate on the "api_body" field.
func APIBodyHasPrefix(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldHasPrefix(FieldAPIBody, v))
}

// APIBodyHasSuffix applies the HasSuffix predicate on the "api_body" field.
func APIBodyHasSuffix(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldHasSuffix(FieldAPIBody, v))
}

// APIBodyIsNil applies the IsNil predicate on the "api_body" field.
func APIBodyIsNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIsNull(FieldAPIBody))
}

// APIBodyNotNil applies the NotNil predicate on the "api_body" field.
func APIBodyNotNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotNull(FieldAPIBody))
}

// APIBodyEqualFold applies the EqualFold predicate on the "api_body" field.
func APIBodyEqualFold(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEqualFold(FieldAPIBody, v))
}

// APIBodyContainsFold applies the ContainsFold predicate on the "api_body" field.
func APIBodyContainsFold(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldContainsFold(FieldAPIBody, v))
}

// APIKeyEQ applies the EQ predicate on the "api_key" field.
func APIKeyEQ(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldAPIKey, v))
}

// APIKeyNEQ applies the NEQ predicate on the "api_key" field.
func APIKeyNEQ(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNEQ(FieldAPIKey, v))
}

// APIKeyIn applies the In predicate on the "api_key" field.
func APIKeyIn(vs ...string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIn(FieldAPIKey, vs...))
}

// APIKeyNotIn applies the NotIn predicate on the "api_key" field.
func APIKeyNotIn(vs ...string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotIn(FieldAPIKey, vs...))
}

// APIKeyGT applies the GT predicate on the "api_key" field.
func APIKeyGT(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGT(FieldAPIKey, v))
}

// APIKeyGTE applies the GTE predicate on the "api_key" field.
func APIKeyGTE(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGTE(FieldAPIKey, v))
}

// APIKeyLT applies the LT predicate on the "api_key" field.
func APIKeyLT(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLT(FieldAPIKey, v))
}

// APIKeyLTE applies the LTE predicate on the "api_key" field.
func APIKeyLTE(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLTE(FieldAPIKey, v))
}

// APIKeyContains applies the Contains predicate on the "api_key" field.
func APIKeyContains(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldContains(FieldAPIKey, v))
}

// APIKeyHasPrefix applies the HasPrefix predicate on the "api_key" field.
func APIKeyHasPrefix(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldHasPrefix(FieldAPIKey, v))
}

// APIKeyHasSuffix applies the HasSuffix predicate on the "api_key" field.
func APIKeyHasSuffix(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldHasSuffix(FieldAPIKey, v))
}

// APIKeyIsNil applies the IsNil predicate on the "api_key" field.
func APIKeyIsNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIsNull(FieldAPIKey))
}

// APIKeyNotNil applies the NotNil predicate on the "api_key" field.
func APIKeyNotNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotNull(FieldAPIKey))
}

// APIKeyEqualFold applies the EqualFold predicate on the "api_key" field.
func APIKeyEqualFold(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEqualFold(FieldAPIKey, v))
}

// APIKeyContainsFold applies the ContainsFold predicate on the "api_key" field.
func APIKeyContainsFold(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldContainsFold(FieldAPIKey, v))
}

// PollIntervalEQ applies the EQ predicate on the "poll_interval" field.
func PollIntervalEQ(v int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldPollInterval, v))
}

// PollIntervalNEQ applies the NEQ predicate on the "poll_interval" field.
func PollIntervalNEQ(v int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNEQ(FieldPollInterval, v))
}

// PollIntervalIn applies the In predicate on the "poll_interval" field.
func PollIntervalIn(vs ...int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIn(FieldPollInterval, vs...))
}

// PollIntervalNotIn applies the NotIn predicate on the "poll_interval" field.
func PollIntervalNotIn(vs ...int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotIn(FieldPollInterval, vs...))
}

// PollIntervalGT applies the GT predicate on the "poll_interval" field.
func PollIntervalGT(v int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGT(FieldPollInterval, v))
}

// PollIntervalGTE applies the GTE predicate on the "poll_interval" field.
func PollIntervalGTE(v int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGTE(FieldPollInterval, v))
}

// PollIntervalLT applies the LT predicate on the "poll_interval" field.
func PollIntervalLT(v int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLT(FieldPollInterval, v))
}

// PollIntervalLTE applies the LTE predicate on the "poll_interval" field.
func PollIntervalLTE(v int) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLTE(FieldPollInterval, v))
}

// VariablesIsNil applies the IsNil predicate on the "variables" field.
func VariablesIsNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIsNull(FieldVariables))
}

// VariablesNotNil applies the NotNil predicate on the "variables" field.
func VariablesNotNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotNull(FieldVariables))
}

// DisplayFieldsIsNil applies the IsNil predicate on the "display_fields" field.
func DisplayFieldsIsNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIsNull(FieldDisplayFields))
}

// DisplayFieldsNotNil applies the NotNil predicate on the "display_fields" field.
func DisplayFieldsNotNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotNull(FieldDisplayFields))
}

// LastPollAtEQ applies the EQ predicate on the "last_poll_at" field.
func LastPollAtEQ(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldLastPollAt, v))
}

// LastPollAtNEQ applies the NEQ predicate on the "last_poll_at" field.
func LastPollAtNEQ(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNEQ(FieldLastPollAt, v))
}

// LastPollAtIn applies the In predicate on the "last_poll_at" field.
func LastPollAtIn(vs ...time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIn(FieldLastPollAt, vs...))
}

// LastPollAtNotIn applies the NotIn predicate on the "last_poll_at" field.
func LastPollAtNotIn(vs ...time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotIn(FieldLastPollAt, vs...))
}

// LastPollAtGT applies the GT predicate on the "last_poll_at" field.
func LastPollAtGT(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGT(FieldLastPollAt, v))
}

// LastPollAtGTE applies the GTE predicate on the "last_poll_at" field.
func LastPollAtGTE(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGTE(FieldLastPollAt, v))
}

// LastPollAtLT applies the LT predicate on the "last_poll_at" field.
func LastPollAtLT(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLT(FieldLastPollAt, v))
}

// LastPollAtLTE applies the LTE predicate on the "last_poll_at" field.
func LastPollAtLTE(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLTE(FieldLastPollAt, v))
}

// LastPollAtIsNil applies the IsNil predicate on the "last_poll_at" field.
func LastPollAtIsNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIsNull(FieldLastPollAt))
}

// LastPollAtNotNil applies the NotNil predicate on the "last_poll_at" field.
func LastPollAtNotNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotNull(FieldLastPollAt))
}

// LastPollDataIsNil applies the IsNil predicate on the "last_poll_data" field.
func LastPollDataIsNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIsNull(FieldLastPollData))
}

// LastPollDataNotNil applies the NotNil predicate on the "last_poll_data" field.
func LastPollDataNotNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotNull(FieldLastPollData))
}

// LastPollErrorEQ applies the EQ predicate on the "last_poll_error" field.
func LastPollErrorEQ(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldLastPollError, v))
}

// LastPollErrorNEQ applies the NEQ predicate on the "last_poll_error" field.
func LastPollErrorNEQ(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNEQ(FieldLastPollError, v))
}

// LastPollErrorIn applies the In predicate on the "last_poll_error" field.
func LastPollErrorIn(vs ...string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIn(FieldLastPollError, vs...))
}

// LastPollErrorNotIn applies the NotIn predicate on the "last_poll_error" field.
func LastPollErrorNotIn(vs ...string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotIn(FieldLastPollError, vs...))
}

// LastPollErrorGT applies the GT predicate on the "last_poll_error" field.
func LastPollErrorGT(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGT(FieldLastPollError, v))
}

// LastPollErrorGTE applies the GTE predicate on the "last_poll_error" field.
func LastPollErrorGTE(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGTE(FieldLastPollError, v))
}

// LastPollErrorLT applies the LT predicate on the "last_poll_error" field.
func LastPollErrorLT(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLT(FieldLastPollError, v))
}

// LastPollErrorLTE applies the LTE predicate on the "last_poll_error" field.
func LastPollErrorLTE(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLTE(FieldLastPollError, v))
}

// LastPollErrorContains applies the Contains predicate on the "last_poll_error" field.
func LastPollErrorContains(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldContains(FieldLastPollError, v))
}

// LastPollErrorHasPrefix applies the HasPrefix predicate on the "last_poll_error" field.
func LastPollErrorHasPrefix(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldHasPrefix(FieldLastPollError, v))
}

// LastPollErrorHasSuffix applies the HasSuffix predicate on the "last_poll_error" field.
func LastPollErrorHasSuffix(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldHasSuffix(FieldLastPollError, v))
}

// LastPollErrorIsNil applies the IsNil predicate on the "last_poll_error" field.
func LastPollErrorIsNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIsNull(FieldLastPollError))
}

// LastPollErrorNotNil applies the NotNil predicate on the "last_poll_error" field.
func LastPollErrorNotNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotNull(FieldLastPollError))
}

// LastPollErrorEqualFold applies the EqualFold predicate on the "last_poll_error" field.
func LastPollErrorEqualFold(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEqualFold(FieldLastPollError, v))
}

// LastPollErrorContainsFold applies the ContainsFold predicate on the "last_poll_error" field.
func LastPollErrorContainsFold(v string) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldContainsFold(FieldLastPollError, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotIn(FieldStatus, vs...))
}

// QuotaStatusEQ applies the EQ predicate on the "quota_status" field.
func QuotaStatusEQ(v QuotaStatus) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldQuotaStatus, v))
}

// QuotaStatusNEQ applies the NEQ predicate on the "quota_status" field.
func QuotaStatusNEQ(v QuotaStatus) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNEQ(FieldQuotaStatus, v))
}

// QuotaStatusIn applies the In predicate on the "quota_status" field.
func QuotaStatusIn(vs ...QuotaStatus) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIn(FieldQuotaStatus, vs...))
}

// QuotaStatusNotIn applies the NotIn predicate on the "quota_status" field.
func QuotaStatusNotIn(vs ...QuotaStatus) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotIn(FieldQuotaStatus, vs...))
}

// QuotaStatusIsNil applies the IsNil predicate on the "quota_status" field.
func QuotaStatusIsNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIsNull(FieldQuotaStatus))
}

// QuotaStatusNotNil applies the NotNil predicate on the "quota_status" field.
func QuotaStatusNotNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotNull(FieldQuotaStatus))
}

// QuotaReadyEQ applies the EQ predicate on the "quota_ready" field.
func QuotaReadyEQ(v bool) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldQuotaReady, v))
}

// QuotaReadyNEQ applies the NEQ predicate on the "quota_ready" field.
func QuotaReadyNEQ(v bool) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNEQ(FieldQuotaReady, v))
}

// QuotaReadyIsNil applies the IsNil predicate on the "quota_ready" field.
func QuotaReadyIsNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIsNull(FieldQuotaReady))
}

// QuotaReadyNotNil applies the NotNil predicate on the "quota_ready" field.
func QuotaReadyNotNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotNull(FieldQuotaReady))
}

// QuotaLimitsIsNil applies the IsNil predicate on the "quota_limits" field.
func QuotaLimitsIsNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIsNull(FieldQuotaLimits))
}

// QuotaLimitsNotNil applies the NotNil predicate on the "quota_limits" field.
func QuotaLimitsNotNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotNull(FieldQuotaLimits))
}

// NextResetAtEQ applies the EQ predicate on the "next_reset_at" field.
func NextResetAtEQ(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldNextResetAt, v))
}

// NextResetAtNEQ applies the NEQ predicate on the "next_reset_at" field.
func NextResetAtNEQ(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNEQ(FieldNextResetAt, v))
}

// NextResetAtIn applies the In predicate on the "next_reset_at" field.
func NextResetAtIn(vs ...time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIn(FieldNextResetAt, vs...))
}

// NextResetAtNotIn applies the NotIn predicate on the "next_reset_at" field.
func NextResetAtNotIn(vs ...time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotIn(FieldNextResetAt, vs...))
}

// NextResetAtGT applies the GT predicate on the "next_reset_at" field.
func NextResetAtGT(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGT(FieldNextResetAt, v))
}

// NextResetAtGTE applies the GTE predicate on the "next_reset_at" field.
func NextResetAtGTE(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGTE(FieldNextResetAt, v))
}

// NextResetAtLT applies the LT predicate on the "next_reset_at" field.
func NextResetAtLT(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLT(FieldNextResetAt, v))
}

// NextResetAtLTE applies the LTE predicate on the "next_reset_at" field.
func NextResetAtLTE(v time.Time) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLTE(FieldNextResetAt, v))
}

// NextResetAtIsNil applies the IsNil predicate on the "next_reset_at" field.
func NextResetAtIsNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIsNull(FieldNextResetAt))
}

// NextResetAtNotNil applies the NotNil predicate on the "next_reset_at" field.
func NextResetAtNotNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotNull(FieldNextResetAt))
}

// AutoDisableEnabledEQ applies the EQ predicate on the "auto_disable_enabled" field.
func AutoDisableEnabledEQ(v bool) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldAutoDisableEnabled, v))
}

// AutoDisableEnabledNEQ applies the NEQ predicate on the "auto_disable_enabled" field.
func AutoDisableEnabledNEQ(v bool) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNEQ(FieldAutoDisableEnabled, v))
}

// AutoDisableThresholdEQ applies the EQ predicate on the "auto_disable_threshold" field.
func AutoDisableThresholdEQ(v float64) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldAutoDisableThreshold, v))
}

// AutoDisableThresholdNEQ applies the NEQ predicate on the "auto_disable_threshold" field.
func AutoDisableThresholdNEQ(v float64) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNEQ(FieldAutoDisableThreshold, v))
}

// AutoDisableThresholdIn applies the In predicate on the "auto_disable_threshold" field.
func AutoDisableThresholdIn(vs ...float64) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIn(FieldAutoDisableThreshold, vs...))
}

// AutoDisableThresholdNotIn applies the NotIn predicate on the "auto_disable_threshold" field.
func AutoDisableThresholdNotIn(vs ...float64) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotIn(FieldAutoDisableThreshold, vs...))
}

// AutoDisableThresholdGT applies the GT predicate on the "auto_disable_threshold" field.
func AutoDisableThresholdGT(v float64) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGT(FieldAutoDisableThreshold, v))
}

// AutoDisableThresholdGTE applies the GTE predicate on the "auto_disable_threshold" field.
func AutoDisableThresholdGTE(v float64) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGTE(FieldAutoDisableThreshold, v))
}

// AutoDisableThresholdLT applies the LT predicate on the "auto_disable_threshold" field.
func AutoDisableThresholdLT(v float64) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLT(FieldAutoDisableThreshold, v))
}

// AutoDisableThresholdLTE applies the LTE predicate on the "auto_disable_threshold" field.
func AutoDisableThresholdLTE(v float64) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLTE(FieldAutoDisableThreshold, v))
}

// AutoDisableThresholdIsNil applies the IsNil predicate on the "auto_disable_threshold" field.
func AutoDisableThresholdIsNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIsNull(FieldAutoDisableThreshold))
}

// AutoDisableThresholdNotNil applies the NotNil predicate on the "auto_disable_threshold" field.
func AutoDisableThresholdNotNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotNull(FieldAutoDisableThreshold))
}

// AutoEnableThresholdEQ applies the EQ predicate on the "auto_enable_threshold" field.
func AutoEnableThresholdEQ(v float64) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldEQ(FieldAutoEnableThreshold, v))
}

// AutoEnableThresholdNEQ applies the NEQ predicate on the "auto_enable_threshold" field.
func AutoEnableThresholdNEQ(v float64) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNEQ(FieldAutoEnableThreshold, v))
}

// AutoEnableThresholdIn applies the In predicate on the "auto_enable_threshold" field.
func AutoEnableThresholdIn(vs ...float64) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIn(FieldAutoEnableThreshold, vs...))
}

// AutoEnableThresholdNotIn applies the NotIn predicate on the "auto_enable_threshold" field.
func AutoEnableThresholdNotIn(vs ...float64) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotIn(FieldAutoEnableThreshold, vs...))
}

// AutoEnableThresholdGT applies the GT predicate on the "auto_enable_threshold" field.
func AutoEnableThresholdGT(v float64) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGT(FieldAutoEnableThreshold, v))
}

// AutoEnableThresholdGTE applies the GTE predicate on the "auto_enable_threshold" field.
func AutoEnableThresholdGTE(v float64) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldGTE(FieldAutoEnableThreshold, v))
}

// AutoEnableThresholdLT applies the LT predicate on the "auto_enable_threshold" field.
func AutoEnableThresholdLT(v float64) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLT(FieldAutoEnableThreshold, v))
}

// AutoEnableThresholdLTE applies the LTE predicate on the "auto_enable_threshold" field.
func AutoEnableThresholdLTE(v float64) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldLTE(FieldAutoEnableThreshold, v))
}

// AutoEnableThresholdIsNil applies the IsNil predicate on the "auto_enable_threshold" field.
func AutoEnableThresholdIsNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldIsNull(FieldAutoEnableThreshold))
}

// AutoEnableThresholdNotNil applies the NotNil predicate on the "auto_enable_threshold" field.
func AutoEnableThresholdNotNil() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.FieldNotNull(FieldAutoEnableThreshold))
}

// HasChannel applies the HasEdge predicate on the "channel" edge.
func HasChannel() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChannelWith applies the HasEdge predicate on the "channel" edge with a given conditions (other predicates).
func HasChannelWith(preds ...predicate.Channel) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(func(s *sql.Selector) {
		step := newChannelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsageMonitorChannel) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsageMonitorChannel) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsageMonitorChannel) predicate.UsageMonitorChannel {
	return predicate.UsageMonitorChannel(sql.NotPredicates(p))
}
