package biz

import (
	"context"
	"fmt"
	"os"
	"runtime"
	"strings"

	"github.com/ldm2060/axonhub/internal/build"
	"github.com/ldm2060/axonhub/llm/transformer/kimicode"
)

// KimiCodeIdentity resolves one stable identity for all Kimi device flow,
// catalog, refresh, and runtime requests generated by this AxonHub install.
func (s *SystemService) KimiCodeIdentity(ctx context.Context) (kimicode.Identity, error) {
	deviceID, err := s.KimiCodeDeviceID(ctx)
	if err != nil {
		return kimicode.Identity{}, err
	}
	version := strings.TrimSpace(build.Version)
	if version == "" || version == "dev" {
		version = "development"
	}
	hostname, err := os.Hostname()
	if err != nil {
		hostname = "unknown"
	}
	osVersion := runtime.GOOS + " " + runtime.GOARCH
	return kimicode.Identity{
		Version: version, Hostname: hostname, DeviceModel: osVersion,
		OSVersion: osVersion, DeviceID: deviceID, UserAgent: fmt.Sprintf("AxonHub/%s", version),
	}, nil
}
