package biz

import (
	"context"
	"fmt"
	"os"

	"github.com/ldm2060/axonhub/llm/transformer/kimicode"
)

// KimiCodeIdentity resolves one stable identity for all Kimi device flow,
// catalog, refresh, and runtime requests generated by this AxonHub install.
func (s *SystemService) KimiCodeIdentity(ctx context.Context) (kimicode.Identity, error) {
	deviceID, err := s.KimiCodeDeviceID(ctx)
	if err != nil {
		return kimicode.Identity{}, err
	}
	hostname, err := os.Hostname()
	if err != nil {
		hostname = "unknown"
	}
	platform, err := resolveKimiCodePlatform(ctx)
	if err != nil {
		return kimicode.Identity{}, err
	}
	identity := kimicode.Identity{
		UserAgentProduct: kimicode.CLIUserAgentProduct,
		Version:          kimicode.CLIVersion,
		Hostname:         hostname,
		DeviceModel:      formatKimiCodeDeviceModel(platform),
		OSVersion:        platform.OSRelease,
		DeviceID:         deviceID,
	}
	if err := kimicode.ValidateIdentity(identity); err != nil {
		return kimicode.Identity{}, fmt.Errorf("build Kimi Code identity: %w", err)
	}
	return identity, nil
}
