// Code generated by ent, DO NOT EDIT.

package channelusagemonitorbinding

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ldm2060/axonhub/internal/objects"
)

const (
	// Label holds the string label denoting the channelusagemonitorbinding type in the database.
	Label = "channel_usage_monitor_binding"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldUsageMonitorChannelID holds the string denoting the usage_monitor_channel_id field in the database.
	FieldUsageMonitorChannelID = "usage_monitor_channel_id"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldTriggerStatuses holds the string denoting the trigger_statuses field in the database.
	FieldTriggerStatuses = "trigger_statuses"
	// FieldConditions holds the string denoting the conditions field in the database.
	FieldConditions = "conditions"
	// FieldLastTriggeredAt holds the string denoting the last_triggered_at field in the database.
	FieldLastTriggeredAt = "last_triggered_at"
	// FieldLastTriggerReason holds the string denoting the last_trigger_reason field in the database.
	FieldLastTriggerReason = "last_trigger_reason"
	// EdgeChannel holds the string denoting the channel edge name in mutations.
	EdgeChannel = "channel"
	// EdgeUsageMonitorChannel holds the string denoting the usage_monitor_channel edge name in mutations.
	EdgeUsageMonitorChannel = "usage_monitor_channel"
	// Table holds the table name of the channelusagemonitorbinding in the database.
	Table = "channel_usage_monitor_bindings"
	// ChannelTable is the table that holds the channel relation/edge.
	ChannelTable = "channel_usage_monitor_bindings"
	// ChannelInverseTable is the table name for the Channel entity.
	// It exists in this package in order to avoid circular dependency with the "channel" package.
	ChannelInverseTable = "channels"
	// ChannelColumn is the table column denoting the channel relation/edge.
	ChannelColumn = "channel_id"
	// UsageMonitorChannelTable is the table that holds the usage_monitor_channel relation/edge.
	UsageMonitorChannelTable = "channel_usage_monitor_bindings"
	// UsageMonitorChannelInverseTable is the table name for the UsageMonitorChannel entity.
	// It exists in this package in order to avoid circular dependency with the "usagemonitorchannel" package.
	UsageMonitorChannelInverseTable = "usage_monitor_channels"
	// UsageMonitorChannelColumn is the table column denoting the usage_monitor_channel relation/edge.
	UsageMonitorChannelColumn = "usage_monitor_channel_id"
)

// Columns holds all SQL columns for channelusagemonitorbinding fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldChannelID,
	FieldUsageMonitorChannelID,
	FieldEnabled,
	FieldTriggerStatuses,
	FieldConditions,
	FieldLastTriggeredAt,
	FieldLastTriggerReason,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/ldm2060/axonhub/internal/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt int
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultTriggerStatuses holds the default value on creation for the "trigger_statuses" field.
	DefaultTriggerStatuses []string
	// DefaultConditions holds the default value on creation for the "conditions" field.
	DefaultConditions []objects.QuotaMonitorBindingCondition
)

// OrderOption defines the ordering options for the ChannelUsageMonitorBinding queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByChannelID orders the results by the channel_id field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByUsageMonitorChannelID orders the results by the usage_monitor_channel_id field.
func ByUsageMonitorChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageMonitorChannelID, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByLastTriggeredAt orders the results by the last_triggered_at field.
func ByLastTriggeredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastTriggeredAt, opts...).ToFunc()
}

// ByLastTriggerReason orders the results by the last_trigger_reason field.
func ByLastTriggerReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastTriggerReason, opts...).ToFunc()
}

// ByChannelField orders the results by channel field.
func ByChannelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelStep(), sql.OrderByField(field, opts...))
	}
}

// ByUsageMonitorChannelField orders the results by usage_monitor_channel field.
func ByUsageMonitorChannelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsageMonitorChannelStep(), sql.OrderByField(field, opts...))
	}
}
func newChannelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
	)
}
func newUsageMonitorChannelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsageMonitorChannelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UsageMonitorChannelTable, UsageMonitorChannelColumn),
	)
}
