// Code generated by ent, DO NOT EDIT.

package channelusagemonitorbinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ldm2060/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldEQ(FieldDeletedAt, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldEQ(FieldChannelID, v))
}

// UsageMonitorChannelID applies equality check predicate on the "usage_monitor_channel_id" field. It's identical to UsageMonitorChannelIDEQ.
func UsageMonitorChannelID(v int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldEQ(FieldUsageMonitorChannelID, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldEQ(FieldEnabled, v))
}

// LastTriggeredAt applies equality check predicate on the "last_triggered_at" field. It's identical to LastTriggeredAtEQ.
func LastTriggeredAt(v time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldEQ(FieldLastTriggeredAt, v))
}

// LastTriggerReason applies equality check predicate on the "last_trigger_reason" field. It's identical to LastTriggerReasonEQ.
func LastTriggerReason(v string) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldEQ(FieldLastTriggerReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldLTE(FieldDeletedAt, v))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldNotIn(FieldChannelID, vs...))
}

// UsageMonitorChannelIDEQ applies the EQ predicate on the "usage_monitor_channel_id" field.
func UsageMonitorChannelIDEQ(v int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldEQ(FieldUsageMonitorChannelID, v))
}

// UsageMonitorChannelIDNEQ applies the NEQ predicate on the "usage_monitor_channel_id" field.
func UsageMonitorChannelIDNEQ(v int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldNEQ(FieldUsageMonitorChannelID, v))
}

// UsageMonitorChannelIDIn applies the In predicate on the "usage_monitor_channel_id" field.
func UsageMonitorChannelIDIn(vs ...int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldIn(FieldUsageMonitorChannelID, vs...))
}

// UsageMonitorChannelIDNotIn applies the NotIn predicate on the "usage_monitor_channel_id" field.
func UsageMonitorChannelIDNotIn(vs ...int) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldNotIn(FieldUsageMonitorChannelID, vs...))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldNEQ(FieldEnabled, v))
}

// LastTriggeredAtEQ applies the EQ predicate on the "last_triggered_at" field.
func LastTriggeredAtEQ(v time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldEQ(FieldLastTriggeredAt, v))
}

// LastTriggeredAtNEQ applies the NEQ predicate on the "last_triggered_at" field.
func LastTriggeredAtNEQ(v time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldNEQ(FieldLastTriggeredAt, v))
}

// LastTriggeredAtIn applies the In predicate on the "last_triggered_at" field.
func LastTriggeredAtIn(vs ...time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldIn(FieldLastTriggeredAt, vs...))
}

// LastTriggeredAtNotIn applies the NotIn predicate on the "last_triggered_at" field.
func LastTriggeredAtNotIn(vs ...time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldNotIn(FieldLastTriggeredAt, vs...))
}

// LastTriggeredAtGT applies the GT predicate on the "last_triggered_at" field.
func LastTriggeredAtGT(v time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldGT(FieldLastTriggeredAt, v))
}

// LastTriggeredAtGTE applies the GTE predicate on the "last_triggered_at" field.
func LastTriggeredAtGTE(v time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldGTE(FieldLastTriggeredAt, v))
}

// LastTriggeredAtLT applies the LT predicate on the "last_triggered_at" field.
func LastTriggeredAtLT(v time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldLT(FieldLastTriggeredAt, v))
}

// LastTriggeredAtLTE applies the LTE predicate on the "last_triggered_at" field.
func LastTriggeredAtLTE(v time.Time) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldLTE(FieldLastTriggeredAt, v))
}

// LastTriggeredAtIsNil applies the IsNil predicate on the "last_triggered_at" field.
func LastTriggeredAtIsNil() predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldIsNull(FieldLastTriggeredAt))
}

// LastTriggeredAtNotNil applies the NotNil predicate on the "last_triggered_at" field.
func LastTriggeredAtNotNil() predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldNotNull(FieldLastTriggeredAt))
}

// LastTriggerReasonEQ applies the EQ predicate on the "last_trigger_reason" field.
func LastTriggerReasonEQ(v string) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldEQ(FieldLastTriggerReason, v))
}

// LastTriggerReasonNEQ applies the NEQ predicate on the "last_trigger_reason" field.
func LastTriggerReasonNEQ(v string) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldNEQ(FieldLastTriggerReason, v))
}

// LastTriggerReasonIn applies the In predicate on the "last_trigger_reason" field.
func LastTriggerReasonIn(vs ...string) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldIn(FieldLastTriggerReason, vs...))
}

// LastTriggerReasonNotIn applies the NotIn predicate on the "last_trigger_reason" field.
func LastTriggerReasonNotIn(vs ...string) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldNotIn(FieldLastTriggerReason, vs...))
}

// LastTriggerReasonGT applies the GT predicate on the "last_trigger_reason" field.
func LastTriggerReasonGT(v string) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldGT(FieldLastTriggerReason, v))
}

// LastTriggerReasonGTE applies the GTE predicate on the "last_trigger_reason" field.
func LastTriggerReasonGTE(v string) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldGTE(FieldLastTriggerReason, v))
}

// LastTriggerReasonLT applies the LT predicate on the "last_trigger_reason" field.
func LastTriggerReasonLT(v string) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldLT(FieldLastTriggerReason, v))
}

// LastTriggerReasonLTE applies the LTE predicate on the "last_trigger_reason" field.
func LastTriggerReasonLTE(v string) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldLTE(FieldLastTriggerReason, v))
}

// LastTriggerReasonContains applies the Contains predicate on the "last_trigger_reason" field.
func LastTriggerReasonContains(v string) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldContains(FieldLastTriggerReason, v))
}

// LastTriggerReasonHasPrefix applies the HasPrefix predicate on the "last_trigger_reason" field.
func LastTriggerReasonHasPrefix(v string) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldHasPrefix(FieldLastTriggerReason, v))
}

// LastTriggerReasonHasSuffix applies the HasSuffix predicate on the "last_trigger_reason" field.
func LastTriggerReasonHasSuffix(v string) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldHasSuffix(FieldLastTriggerReason, v))
}

// LastTriggerReasonIsNil applies the IsNil predicate on the "last_trigger_reason" field.
func LastTriggerReasonIsNil() predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldIsNull(FieldLastTriggerReason))
}

// LastTriggerReasonNotNil applies the NotNil predicate on the "last_trigger_reason" field.
func LastTriggerReasonNotNil() predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldNotNull(FieldLastTriggerReason))
}

// LastTriggerReasonEqualFold applies the EqualFold predicate on the "last_trigger_reason" field.
func LastTriggerReasonEqualFold(v string) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldEqualFold(FieldLastTriggerReason, v))
}

// LastTriggerReasonContainsFold applies the ContainsFold predicate on the "last_trigger_reason" field.
func LastTriggerReasonContainsFold(v string) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.FieldContainsFold(FieldLastTriggerReason, v))
}

// HasChannel applies the HasEdge predicate on the "channel" edge.
func HasChannel() predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChannelWith applies the HasEdge predicate on the "channel" edge with a given conditions (other predicates).
func HasChannelWith(preds ...predicate.Channel) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(func(s *sql.Selector) {
		step := newChannelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsageMonitorChannel applies the HasEdge predicate on the "usage_monitor_channel" edge.
func HasUsageMonitorChannel() predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UsageMonitorChannelTable, UsageMonitorChannelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageMonitorChannelWith applies the HasEdge predicate on the "usage_monitor_channel" edge with a given conditions (other predicates).
func HasUsageMonitorChannelWith(preds ...predicate.UsageMonitorChannel) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(func(s *sql.Selector) {
		step := newUsageMonitorChannelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChannelUsageMonitorBinding) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChannelUsageMonitorBinding) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChannelUsageMonitorBinding) predicate.ChannelUsageMonitorBinding {
	return predicate.ChannelUsageMonitorBinding(sql.NotPredicates(p))
}
