// Code generated by ent, DO NOT EDIT.

package channel

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ldm2060/axonhub/internal/objects"
)

const (
	// Label holds the string label denoting the channel type in the database.
	Label = "channel"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldBaseURL holds the string denoting the base_url field in the database.
	FieldBaseURL = "base_url"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCredentials holds the string denoting the credentials field in the database.
	FieldCredentials = "credentials"
	// FieldDisabledAPIKeys holds the string denoting the disabled_api_keys field in the database.
	FieldDisabledAPIKeys = "disabled_api_keys"
	// FieldSupportedModels holds the string denoting the supported_models field in the database.
	FieldSupportedModels = "supported_models"
	// FieldManualModels holds the string denoting the manual_models field in the database.
	FieldManualModels = "manual_models"
	// FieldAutoSyncSupportedModels holds the string denoting the auto_sync_supported_models field in the database.
	FieldAutoSyncSupportedModels = "auto_sync_supported_models"
	// FieldAutoSyncModelPattern holds the string denoting the auto_sync_model_pattern field in the database.
	FieldAutoSyncModelPattern = "auto_sync_model_pattern"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldDefaultTestModel holds the string denoting the default_test_model field in the database.
	FieldDefaultTestModel = "default_test_model"
	// FieldPolicies holds the string denoting the policies field in the database.
	FieldPolicies = "policies"
	// FieldSettings holds the string denoting the settings field in the database.
	FieldSettings = "settings"
	// FieldOrderingWeight holds the string denoting the ordering_weight field in the database.
	FieldOrderingWeight = "ordering_weight"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldEndpoints holds the string denoting the endpoints field in the database.
	FieldEndpoints = "endpoints"
	// FieldClientRestriction holds the string denoting the client_restriction field in the database.
	FieldClientRestriction = "client_restriction"
	// FieldAutoDisableConfig holds the string denoting the auto_disable_config field in the database.
	FieldAutoDisableConfig = "auto_disable_config"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldVisibility holds the string denoting the visibility field in the database.
	FieldVisibility = "visibility"
	// FieldSharedWith holds the string denoting the shared_with field in the database.
	FieldSharedWith = "shared_with"
	// FieldQuotaBindingReady holds the string denoting the quota_binding_ready field in the database.
	FieldQuotaBindingReady = "quota_binding_ready"
	// FieldQuotaMultiMonitorStrategy holds the string denoting the quota_multi_monitor_strategy field in the database.
	FieldQuotaMultiMonitorStrategy = "quota_multi_monitor_strategy"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeRequests holds the string denoting the requests edge name in mutations.
	EdgeRequests = "requests"
	// EdgeExecutions holds the string denoting the executions edge name in mutations.
	EdgeExecutions = "executions"
	// EdgeUsageLogs holds the string denoting the usage_logs edge name in mutations.
	EdgeUsageLogs = "usage_logs"
	// EdgeChannelProbes holds the string denoting the channel_probes edge name in mutations.
	EdgeChannelProbes = "channel_probes"
	// EdgeChannelModelPrices holds the string denoting the channel_model_prices edge name in mutations.
	EdgeChannelModelPrices = "channel_model_prices"
	// EdgeProviderQuotaStatus holds the string denoting the provider_quota_status edge name in mutations.
	EdgeProviderQuotaStatus = "provider_quota_status"
	// EdgeUsageMonitorChannels holds the string denoting the usage_monitor_channels edge name in mutations.
	EdgeUsageMonitorChannels = "usage_monitor_channels"
	// EdgeQuotaMonitorBindings holds the string denoting the quota_monitor_bindings edge name in mutations.
	EdgeQuotaMonitorBindings = "quota_monitor_bindings"
	// Table holds the table name of the channel in the database.
	Table = "channels"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "channels"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "owner_id"
	// RequestsTable is the table that holds the requests relation/edge.
	RequestsTable = "requests"
	// RequestsInverseTable is the table name for the Request entity.
	// It exists in this package in order to avoid circular dependency with the "request" package.
	RequestsInverseTable = "requests"
	// RequestsColumn is the table column denoting the requests relation/edge.
	RequestsColumn = "channel_id"
	// ExecutionsTable is the table that holds the executions relation/edge.
	ExecutionsTable = "request_executions"
	// ExecutionsInverseTable is the table name for the RequestExecution entity.
	// It exists in this package in order to avoid circular dependency with the "requestexecution" package.
	ExecutionsInverseTable = "request_executions"
	// ExecutionsColumn is the table column denoting the executions relation/edge.
	ExecutionsColumn = "channel_id"
	// UsageLogsTable is the table that holds the usage_logs relation/edge.
	UsageLogsTable = "usage_logs"
	// UsageLogsInverseTable is the table name for the UsageLog entity.
	// It exists in this package in order to avoid circular dependency with the "usagelog" package.
	UsageLogsInverseTable = "usage_logs"
	// UsageLogsColumn is the table column denoting the usage_logs relation/edge.
	UsageLogsColumn = "channel_id"
	// ChannelProbesTable is the table that holds the channel_probes relation/edge.
	ChannelProbesTable = "channel_probes"
	// ChannelProbesInverseTable is the table name for the ChannelProbe entity.
	// It exists in this package in order to avoid circular dependency with the "channelprobe" package.
	ChannelProbesInverseTable = "channel_probes"
	// ChannelProbesColumn is the table column denoting the channel_probes relation/edge.
	ChannelProbesColumn = "channel_id"
	// ChannelModelPricesTable is the table that holds the channel_model_prices relation/edge.
	ChannelModelPricesTable = "channel_model_prices"
	// ChannelModelPricesInverseTable is the table name for the ChannelModelPrice entity.
	// It exists in this package in order to avoid circular dependency with the "channelmodelprice" package.
	ChannelModelPricesInverseTable = "channel_model_prices"
	// ChannelModelPricesColumn is the table column denoting the channel_model_prices relation/edge.
	ChannelModelPricesColumn = "channel_id"
	// ProviderQuotaStatusTable is the table that holds the provider_quota_status relation/edge.
	ProviderQuotaStatusTable = "provider_quota_status"
	// ProviderQuotaStatusInverseTable is the table name for the ProviderQuotaStatus entity.
	// It exists in this package in order to avoid circular dependency with the "providerquotastatus" package.
	ProviderQuotaStatusInverseTable = "provider_quota_status"
	// ProviderQuotaStatusColumn is the table column denoting the provider_quota_status relation/edge.
	ProviderQuotaStatusColumn = "channel_id"
	// UsageMonitorChannelsTable is the table that holds the usage_monitor_channels relation/edge.
	UsageMonitorChannelsTable = "usage_monitor_channels"
	// UsageMonitorChannelsInverseTable is the table name for the UsageMonitorChannel entity.
	// It exists in this package in order to avoid circular dependency with the "usagemonitorchannel" package.
	UsageMonitorChannelsInverseTable = "usage_monitor_channels"
	// UsageMonitorChannelsColumn is the table column denoting the usage_monitor_channels relation/edge.
	UsageMonitorChannelsColumn = "channel_id"
	// QuotaMonitorBindingsTable is the table that holds the quota_monitor_bindings relation/edge.
	QuotaMonitorBindingsTable = "channel_usage_monitor_bindings"
	// QuotaMonitorBindingsInverseTable is the table name for the ChannelUsageMonitorBinding entity.
	// It exists in this package in order to avoid circular dependency with the "channelusagemonitorbinding" package.
	QuotaMonitorBindingsInverseTable = "channel_usage_monitor_bindings"
	// QuotaMonitorBindingsColumn is the table column denoting the quota_monitor_bindings relation/edge.
	QuotaMonitorBindingsColumn = "channel_id"
)

// Columns holds all SQL columns for channel fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldType,
	FieldBaseURL,
	FieldName,
	FieldStatus,
	FieldCredentials,
	FieldDisabledAPIKeys,
	FieldSupportedModels,
	FieldManualModels,
	FieldAutoSyncSupportedModels,
	FieldAutoSyncModelPattern,
	FieldTags,
	FieldDefaultTestModel,
	FieldPolicies,
	FieldSettings,
	FieldOrderingWeight,
	FieldErrorMessage,
	FieldRemark,
	FieldEndpoints,
	FieldClientRestriction,
	FieldAutoDisableConfig,
	FieldOwnerID,
	FieldVisibility,
	FieldSharedWith,
	FieldQuotaBindingReady,
	FieldQuotaMultiMonitorStrategy,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/ldm2060/axonhub/internal/ent/runtime"
var (
	Hooks        [2]ent.Hook
	Interceptors [1]ent.Interceptor
	Policy       ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt int
	// DefaultDisabledAPIKeys holds the default value on creation for the "disabled_api_keys" field.
	DefaultDisabledAPIKeys []objects.DisabledAPIKey
	// DefaultManualModels holds the default value on creation for the "manual_models" field.
	DefaultManualModels []string
	// DefaultAutoSyncSupportedModels holds the default value on creation for the "auto_sync_supported_models" field.
	DefaultAutoSyncSupportedModels bool
	// DefaultAutoSyncModelPattern holds the default value on creation for the "auto_sync_model_pattern" field.
	DefaultAutoSyncModelPattern string
	// DefaultTags holds the default value on creation for the "tags" field.
	DefaultTags []string
	// DefaultPolicies holds the default value on creation for the "policies" field.
	DefaultPolicies objects.ChannelPolicies
	// DefaultSettings holds the default value on creation for the "settings" field.
	DefaultSettings *objects.ChannelSettings
	// DefaultOrderingWeight holds the default value on creation for the "ordering_weight" field.
	DefaultOrderingWeight int
	// DefaultEndpoints holds the default value on creation for the "endpoints" field.
	DefaultEndpoints []objects.ChannelEndpoint
	// DefaultQuotaBindingReady holds the default value on creation for the "quota_binding_ready" field.
	DefaultQuotaBindingReady bool
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeOpenai              Type = "openai"
	TypeOpenaiResponses     Type = "openai_responses"
	TypeAtlascloud          Type = "atlascloud"
	TypeCodex               Type = "codex"
	TypeVercel              Type = "vercel"
	TypeAnthropic           Type = "anthropic"
	TypeAnthropicAWS        Type = "anthropic_aws"
	TypeAnthropicGcp        Type = "anthropic_gcp"
	TypeGeminiOpenai        Type = "gemini_openai"
	TypeGemini              Type = "gemini"
	TypeGeminiVertex        Type = "gemini_vertex"
	TypeDeepseek            Type = "deepseek"
	TypeDeepseekAnthropic   Type = "deepseek_anthropic"
	TypeDeepinfra           Type = "deepinfra"
	TypeQiniu               Type = "qiniu"
	TypeFireworks           Type = "fireworks"
	TypeDoubao              Type = "doubao"
	TypeDoubaoAnthropic     Type = "doubao_anthropic"
	TypeMoonshot            Type = "moonshot"
	TypeMoonshotAnthropic   Type = "moonshot_anthropic"
	TypeZhipu               Type = "zhipu"
	TypeZai                 Type = "zai"
	TypeZhipuAnthropic      Type = "zhipu_anthropic"
	TypeZaiAnthropic        Type = "zai_anthropic"
	TypeAnthropicFake       Type = "anthropic_fake"
	TypeOpenaiFake          Type = "openai_fake"
	TypeOpenrouter          Type = "openrouter"
	TypeXiaomi              Type = "xiaomi"
	TypeXiaomiAnthropic     Type = "xiaomi_anthropic"
	TypeXai                 Type = "xai"
	TypePpio                Type = "ppio"
	TypeSiliconflow         Type = "siliconflow"
	TypeVolcengine          Type = "volcengine"
	TypeVolcengineAnthropic Type = "volcengine_anthropic"
	TypeLongcat             Type = "longcat"
	TypeLongcatAnthropic    Type = "longcat_anthropic"
	TypeMinimax             Type = "minimax"
	TypeMinimaxAnthropic    Type = "minimax_anthropic"
	TypeAihubmix            Type = "aihubmix"
	TypeAihubmixAnthropic   Type = "aihubmix_anthropic"
	TypeBurncloud           Type = "burncloud"
	TypeModelscope          Type = "modelscope"
	TypeBailian             Type = "bailian"
	TypeBailianAnthropic    Type = "bailian_anthropic"
	TypeMoonshotCoding      Type = "moonshot_coding"
	TypeJina                Type = "jina"
	TypeGithub              Type = "github"
	TypeGithubCopilot       Type = "github_copilot"
	TypeClaudecode          Type = "claudecode"
	TypeCerebras            Type = "cerebras"
	TypeAntigravity         Type = "antigravity"
	TypeNanogpt             Type = "nanogpt"
	TypeNanogptResponses    Type = "nanogpt_responses"
	TypeOpencodeGo          Type = "opencode_go"
	TypeOpencodeGoAnthropic Type = "opencode_go_anthropic"
	TypeOllama              Type = "ollama"
	TypeEvolink             Type = "evolink"
	TypeEvolinkAnthropic    Type = "evolink_anthropic"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeOpenai, TypeOpenaiResponses, TypeAtlascloud, TypeCodex, TypeVercel, TypeAnthropic, TypeAnthropicAWS, TypeAnthropicGcp, TypeGeminiOpenai, TypeGemini, TypeGeminiVertex, TypeDeepseek, TypeDeepseekAnthropic, TypeDeepinfra, TypeQiniu, TypeFireworks, TypeDoubao, TypeDoubaoAnthropic, TypeMoonshot, TypeMoonshotAnthropic, TypeZhipu, TypeZai, TypeZhipuAnthropic, TypeZaiAnthropic, TypeAnthropicFake, TypeOpenaiFake, TypeOpenrouter, TypeXiaomi, TypeXiaomiAnthropic, TypeXai, TypePpio, TypeSiliconflow, TypeVolcengine, TypeVolcengineAnthropic, TypeLongcat, TypeLongcatAnthropic, TypeMinimax, TypeMinimaxAnthropic, TypeAihubmix, TypeAihubmixAnthropic, TypeBurncloud, TypeModelscope, TypeBailian, TypeBailianAnthropic, TypeMoonshotCoding, TypeJina, TypeGithub, TypeGithubCopilot, TypeClaudecode, TypeCerebras, TypeAntigravity, TypeNanogpt, TypeNanogptResponses, TypeOpencodeGo, TypeOpencodeGoAnthropic, TypeOllama, TypeEvolink, TypeEvolinkAnthropic:
		return nil
	default:
		return fmt.Errorf("channel: invalid enum value for type field: %q", _type)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusDisabled is the default value of the Status enum.
const DefaultStatus = StatusDisabled

// Status values.
const (
	StatusEnabled  Status = "enabled"
	StatusDisabled Status = "disabled"
	StatusArchived Status = "archived"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusEnabled, StatusDisabled, StatusArchived:
		return nil
	default:
		return fmt.Errorf("channel: invalid enum value for status field: %q", s)
	}
}

// ClientRestriction defines the type for the "client_restriction" enum field.
type ClientRestriction string

// ClientRestriction values.
const (
	ClientRestrictionOff     ClientRestriction = "off"
	ClientRestrictionLenient ClientRestriction = "lenient"
	ClientRestrictionStrict  ClientRestriction = "strict"
)

func (cr ClientRestriction) String() string {
	return string(cr)
}

// ClientRestrictionValidator is a validator for the "client_restriction" field enum values. It is called by the builders before save.
func ClientRestrictionValidator(cr ClientRestriction) error {
	switch cr {
	case ClientRestrictionOff, ClientRestrictionLenient, ClientRestrictionStrict:
		return nil
	default:
		return fmt.Errorf("channel: invalid enum value for client_restriction field: %q", cr)
	}
}

// Visibility defines the type for the "visibility" enum field.
type Visibility string

// VisibilityPrivate is the default value of the Visibility enum.
const DefaultVisibility = VisibilityPrivate

// Visibility values.
const (
	VisibilityPrivate   Visibility = "private"
	VisibilityShared    Visibility = "shared"
	VisibilityPublished Visibility = "published"
)

func (v Visibility) String() string {
	return string(v)
}

// VisibilityValidator is a validator for the "visibility" field enum values. It is called by the builders before save.
func VisibilityValidator(v Visibility) error {
	switch v {
	case VisibilityPrivate, VisibilityShared, VisibilityPublished:
		return nil
	default:
		return fmt.Errorf("channel: invalid enum value for visibility field: %q", v)
	}
}

// QuotaMultiMonitorStrategy defines the type for the "quota_multi_monitor_strategy" enum field.
type QuotaMultiMonitorStrategy string

// QuotaMultiMonitorStrategyAny is the default value of the QuotaMultiMonitorStrategy enum.
const DefaultQuotaMultiMonitorStrategy = QuotaMultiMonitorStrategyAny

// QuotaMultiMonitorStrategy values.
const (
	QuotaMultiMonitorStrategyAny QuotaMultiMonitorStrategy = "any"
	QuotaMultiMonitorStrategyAll QuotaMultiMonitorStrategy = "all"
)

func (qmms QuotaMultiMonitorStrategy) String() string {
	return string(qmms)
}

// QuotaMultiMonitorStrategyValidator is a validator for the "quota_multi_monitor_strategy" field enum values. It is called by the builders before save.
func QuotaMultiMonitorStrategyValidator(qmms QuotaMultiMonitorStrategy) error {
	switch qmms {
	case QuotaMultiMonitorStrategyAny, QuotaMultiMonitorStrategyAll:
		return nil
	default:
		return fmt.Errorf("channel: invalid enum value for quota_multi_monitor_strategy field: %q", qmms)
	}
}

// OrderOption defines the ordering options for the Channel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByBaseURL orders the results by the base_url field.
func ByBaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseURL, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAutoSyncSupportedModels orders the results by the auto_sync_supported_models field.
func ByAutoSyncSupportedModels(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoSyncSupportedModels, opts...).ToFunc()
}

// ByAutoSyncModelPattern orders the results by the auto_sync_model_pattern field.
func ByAutoSyncModelPattern(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoSyncModelPattern, opts...).ToFunc()
}

// ByDefaultTestModel orders the results by the default_test_model field.
func ByDefaultTestModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultTestModel, opts...).ToFunc()
}

// ByOrderingWeight orders the results by the ordering_weight field.
func ByOrderingWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderingWeight, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByClientRestriction orders the results by the client_restriction field.
func ByClientRestriction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientRestriction, opts...).ToFunc()
}

// ByOwnerID orders the results by the owner_id field.
func ByOwnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerID, opts...).ToFunc()
}

// ByVisibility orders the results by the visibility field.
func ByVisibility(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVisibility, opts...).ToFunc()
}

// ByQuotaBindingReady orders the results by the quota_binding_ready field.
func ByQuotaBindingReady(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaBindingReady, opts...).ToFunc()
}

// ByQuotaMultiMonitorStrategy orders the results by the quota_multi_monitor_strategy field.
func ByQuotaMultiMonitorStrategy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaMultiMonitorStrategy, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}

// ByRequestsCount orders the results by requests count.
func ByRequestsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRequestsStep(), opts...)
	}
}

// ByRequests orders the results by requests terms.
func ByRequests(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRequestsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByExecutionsCount orders the results by executions count.
func ByExecutionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newExecutionsStep(), opts...)
	}
}

// ByExecutions orders the results by executions terms.
func ByExecutions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExecutionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUsageLogsCount orders the results by usage_logs count.
func ByUsageLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUsageLogsStep(), opts...)
	}
}

// ByUsageLogs orders the results by usage_logs terms.
func ByUsageLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsageLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByChannelProbesCount orders the results by channel_probes count.
func ByChannelProbesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChannelProbesStep(), opts...)
	}
}

// ByChannelProbes orders the results by channel_probes terms.
func ByChannelProbes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelProbesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByChannelModelPricesCount orders the results by channel_model_prices count.
func ByChannelModelPricesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChannelModelPricesStep(), opts...)
	}
}

// ByChannelModelPrices orders the results by channel_model_prices terms.
func ByChannelModelPrices(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelModelPricesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProviderQuotaStatusField orders the results by provider_quota_status field.
func ByProviderQuotaStatusField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProviderQuotaStatusStep(), sql.OrderByField(field, opts...))
	}
}

// ByUsageMonitorChannelsCount orders the results by usage_monitor_channels count.
func ByUsageMonitorChannelsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUsageMonitorChannelsStep(), opts...)
	}
}

// ByUsageMonitorChannels orders the results by usage_monitor_channels terms.
func ByUsageMonitorChannels(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsageMonitorChannelsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByQuotaMonitorBindingsCount orders the results by quota_monitor_bindings count.
func ByQuotaMonitorBindingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newQuotaMonitorBindingsStep(), opts...)
	}
}

// ByQuotaMonitorBindings orders the results by quota_monitor_bindings terms.
func ByQuotaMonitorBindings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newQuotaMonitorBindingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
	)
}
func newRequestsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RequestsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RequestsTable, RequestsColumn),
	)
}
func newExecutionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExecutionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ExecutionsTable, ExecutionsColumn),
	)
}
func newUsageLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsageLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
	)
}
func newChannelProbesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelProbesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChannelProbesTable, ChannelProbesColumn),
	)
}
func newChannelModelPricesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelModelPricesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChannelModelPricesTable, ChannelModelPricesColumn),
	)
}
func newProviderQuotaStatusStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProviderQuotaStatusInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, ProviderQuotaStatusTable, ProviderQuotaStatusColumn),
	)
}
func newUsageMonitorChannelsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsageMonitorChannelsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UsageMonitorChannelsTable, UsageMonitorChannelsColumn),
	)
}
func newQuotaMonitorBindingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(QuotaMonitorBindingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, QuotaMonitorBindingsTable, QuotaMonitorBindingsColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Type) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Type) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Type(str)
	if err := TypeValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Type", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Status) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Status) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Status(str)
	if err := StatusValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e ClientRestriction) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *ClientRestriction) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = ClientRestriction(str)
	if err := ClientRestrictionValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid ClientRestriction", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Visibility) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Visibility) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Visibility(str)
	if err := VisibilityValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Visibility", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e QuotaMultiMonitorStrategy) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *QuotaMultiMonitorStrategy) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = QuotaMultiMonitorStrategy(str)
	if err := QuotaMultiMonitorStrategyValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid QuotaMultiMonitorStrategy", str)
	}
	return nil
}
